/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.rolling.restart.sample.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RollingRestartSampleEntry service. Represents a row in the &quot;RollingRestartSampleEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.rolling.restart.sample.model.impl.RollingRestartSampleEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.rolling.restart.sample.model.impl.RollingRestartSampleEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RollingRestartSampleEntry
 * @generated
 */
@ProviderType
public interface RollingRestartSampleEntryModel
	extends BaseModel<RollingRestartSampleEntry>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a rolling restart sample entry model instance should use the {@link RollingRestartSampleEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this rolling restart sample entry.
	 *
	 * @return the primary key of this rolling restart sample entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this rolling restart sample entry.
	 *
	 * @param primaryKey the primary key of this rolling restart sample entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this rolling restart sample entry.
	 *
	 * @return the mvcc version of this rolling restart sample entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this rolling restart sample entry.
	 *
	 * @param mvccVersion the mvcc version of this rolling restart sample entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the entry ID of this rolling restart sample entry.
	 *
	 * @return the entry ID of this rolling restart sample entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this rolling restart sample entry.
	 *
	 * @param entryId the entry ID of this rolling restart sample entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the company ID of this rolling restart sample entry.
	 *
	 * @return the company ID of this rolling restart sample entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this rolling restart sample entry.
	 *
	 * @param companyId the company ID of this rolling restart sample entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this rolling restart sample entry.
	 *
	 * @return the user ID of this rolling restart sample entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this rolling restart sample entry.
	 *
	 * @param userId the user ID of this rolling restart sample entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this rolling restart sample entry.
	 *
	 * @return the user uuid of this rolling restart sample entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this rolling restart sample entry.
	 *
	 * @param userUuid the user uuid of this rolling restart sample entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this rolling restart sample entry.
	 *
	 * @return the create date of this rolling restart sample entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this rolling restart sample entry.
	 *
	 * @param createDate the create date of this rolling restart sample entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this rolling restart sample entry.
	 *
	 * @return the modified date of this rolling restart sample entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this rolling restart sample entry.
	 *
	 * @param modifiedDate the modified date of this rolling restart sample entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this rolling restart sample entry.
	 *
	 * @return the name of this rolling restart sample entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this rolling restart sample entry.
	 *
	 * @param name the name of this rolling restart sample entry
	 */
	public void setName(String name);

	/**
	 * Returns the description of this rolling restart sample entry.
	 *
	 * @return the description of this rolling restart sample entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this rolling restart sample entry.
	 *
	 * @param description the description of this rolling restart sample entry
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this rolling restart sample entry.
	 *
	 * @return the status of this rolling restart sample entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this rolling restart sample entry.
	 *
	 * @param status the status of this rolling restart sample entry
	 */
	public void setStatus(int status);

}