/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.message.boards.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.message.boards.model.MBMessage;
import com.liferay.message.boards.model.MBMessageModel;
import com.liferay.message.boards.model.MBMessageSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the MBMessage service. Represents a row in the &quot;MBMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>MBMessageModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MBMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MBMessageImpl
 * @generated
 */
@JSON(strict = true)
public class MBMessageModelImpl
	extends BaseModelImpl<MBMessage> implements MBMessageModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a message-boards message model instance should use the <code>MBMessage</code> interface instead.
	 */
	public static final String TABLE_NAME = "MBMessage";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"messageId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"categoryId", Types.BIGINT}, {"threadId", Types.BIGINT},
		{"rootMessageId", Types.BIGINT}, {"parentMessageId", Types.BIGINT},
		{"treePath", Types.VARCHAR}, {"subject", Types.VARCHAR},
		{"urlSubject", Types.VARCHAR}, {"body", Types.CLOB},
		{"format", Types.VARCHAR}, {"anonymous", Types.BOOLEAN},
		{"priority", Types.DOUBLE}, {"allowPingbacks", Types.BOOLEAN},
		{"answer", Types.BOOLEAN}, {"lastPublishDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("messageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("categoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("threadId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("rootMessageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentMessageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("treePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("urlSubject", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("body", Types.CLOB);
		TABLE_COLUMNS_MAP.put("format", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("anonymous", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("priority", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("allowPingbacks", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("answer", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table MBMessage (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,messageId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,categoryId LONG,threadId LONG,rootMessageId LONG,parentMessageId LONG,treePath STRING null,subject VARCHAR(75) null,urlSubject VARCHAR(255) null,body TEXT null,format VARCHAR(75) null,anonymous BOOLEAN,priority DOUBLE,allowPingbacks BOOLEAN,answer BOOLEAN,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,primary key (messageId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table MBMessage";

	public static final String ORDER_BY_JPQL =
		" ORDER BY mbMessage.createDate ASC, mbMessage.messageId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY MBMessage.createDate ASC, MBMessage.messageId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long MVCCVERSION_COLUMN_BITMASK = 1L;

	public static final long CTCOLLECTIONID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long MESSAGEID_COLUMN_BITMASK = 8L;

	public static final long GROUPID_COLUMN_BITMASK = 16L;

	public static final long COMPANYID_COLUMN_BITMASK = 32L;

	public static final long USERID_COLUMN_BITMASK = 64L;

	public static final long USERNAME_COLUMN_BITMASK = 128L;

	public static final long CREATEDATE_COLUMN_BITMASK = 256L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 512L;

	public static final long CLASSNAMEID_COLUMN_BITMASK = 1024L;

	public static final long CLASSPK_COLUMN_BITMASK = 2048L;

	public static final long CATEGORYID_COLUMN_BITMASK = 4096L;

	public static final long THREADID_COLUMN_BITMASK = 8192L;

	public static final long ROOTMESSAGEID_COLUMN_BITMASK = 16384L;

	public static final long PARENTMESSAGEID_COLUMN_BITMASK = 32768L;

	public static final long TREEPATH_COLUMN_BITMASK = 65536L;

	public static final long SUBJECT_COLUMN_BITMASK = 131072L;

	public static final long URLSUBJECT_COLUMN_BITMASK = 262144L;

	public static final long BODY_COLUMN_BITMASK = 524288L;

	public static final long FORMAT_COLUMN_BITMASK = 1048576L;

	public static final long ANONYMOUS_COLUMN_BITMASK = 2097152L;

	public static final long PRIORITY_COLUMN_BITMASK = 4194304L;

	public static final long ALLOWPINGBACKS_COLUMN_BITMASK = 8388608L;

	public static final long ANSWER_COLUMN_BITMASK = 16777216L;

	public static final long LASTPUBLISHDATE_COLUMN_BITMASK = 33554432L;

	public static final long STATUS_COLUMN_BITMASK = 67108864L;

	public static final long STATUSBYUSERID_COLUMN_BITMASK = 134217728L;

	public static final long STATUSBYUSERNAME_COLUMN_BITMASK = 268435456L;

	public static final long STATUSDATE_COLUMN_BITMASK = 536870912L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MBMessage toModel(MBMessageSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MBMessage model = new MBMessageImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setCtCollectionId(soapModel.getCtCollectionId());
		model.setUuid(soapModel.getUuid());
		model.setMessageId(soapModel.getMessageId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setCategoryId(soapModel.getCategoryId());
		model.setThreadId(soapModel.getThreadId());
		model.setRootMessageId(soapModel.getRootMessageId());
		model.setParentMessageId(soapModel.getParentMessageId());
		model.setTreePath(soapModel.getTreePath());
		model.setSubject(soapModel.getSubject());
		model.setUrlSubject(soapModel.getUrlSubject());
		model.setBody(soapModel.getBody());
		model.setFormat(soapModel.getFormat());
		model.setAnonymous(soapModel.isAnonymous());
		model.setPriority(soapModel.getPriority());
		model.setAllowPingbacks(soapModel.isAllowPingbacks());
		model.setAnswer(soapModel.isAnswer());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MBMessage> toModels(MBMessageSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MBMessage> models = new ArrayList<MBMessage>(soapModels.length);

		for (MBMessageSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public MBMessageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _messageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMessageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _messageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MBMessage.class;
	}

	@Override
	public String getModelClassName() {
		return MBMessage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<MBMessage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<MBMessage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MBMessage, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((MBMessage)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<MBMessage, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<MBMessage, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(MBMessage)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<MBMessage, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<MBMessage, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, MBMessage>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			MBMessage.class.getClassLoader(), MBMessage.class,
			ModelWrapper.class);

		try {
			Constructor<MBMessage> constructor =
				(Constructor<MBMessage>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	public <T> T getAttribute(String attribute) {
		Function<MBMessage, Object> function = _attributeGetterFunctions.get(
			attribute);

		if (function == null) {
			return null;
		}

		return (T)function.apply((MBMessage)this);
	}

	public <T> T getCacheModelAttribute(String attribute) {
		Function<MBMessageCacheModel, Object> function =
			_cacheModelGetterFunctions.get(attribute);

		if (function == null) {
			return null;
		}

		if (_mbMessageCacheModel == null) {
			return null;
		}

		return (T)function.apply(_mbMessageCacheModel);
	}

	private static final Map<String, Function<MBMessage, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<MBMessage, Object>>
		_attributeSetterBiConsumers;
	private static final Map<String, Function<MBMessageCacheModel, Object>>
		_cacheModelGetterFunctions;

	static {
		Map<String, Function<MBMessage, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<MBMessage, Object>>();
		Map<String, BiConsumer<MBMessage, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<MBMessage, ?>>();
		Map<String, Function<MBMessageCacheModel, Object>>
			cacheModelGetterFunctions =
				new LinkedHashMap
					<String, Function<MBMessageCacheModel, Object>>();

		attributeGetterFunctions.put("mvccVersion", MBMessage::getMvccVersion);

		cacheModelGetterFunctions.put(
			"mvccVersion",
			mbMessageCacheModel -> mbMessageCacheModel.mvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<MBMessage, Long>)MBMessage::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", MBMessage::getCtCollectionId);

		cacheModelGetterFunctions.put(
			"ctCollectionId",
			mbMessageCacheModel -> mbMessageCacheModel.ctCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<MBMessage, Long>)MBMessage::setCtCollectionId);
		attributeGetterFunctions.put("uuid", MBMessage::getUuid);

		cacheModelGetterFunctions.put(
			"uuid", mbMessageCacheModel -> mbMessageCacheModel.uuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<MBMessage, String>)MBMessage::setUuid);
		attributeGetterFunctions.put("messageId", MBMessage::getMessageId);

		cacheModelGetterFunctions.put(
			"messageId", mbMessageCacheModel -> mbMessageCacheModel.messageId);
		attributeSetterBiConsumers.put(
			"messageId", (BiConsumer<MBMessage, Long>)MBMessage::setMessageId);
		attributeGetterFunctions.put("groupId", MBMessage::getGroupId);

		cacheModelGetterFunctions.put(
			"groupId", mbMessageCacheModel -> mbMessageCacheModel.groupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<MBMessage, Long>)MBMessage::setGroupId);
		attributeGetterFunctions.put("companyId", MBMessage::getCompanyId);

		cacheModelGetterFunctions.put(
			"companyId", mbMessageCacheModel -> mbMessageCacheModel.companyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<MBMessage, Long>)MBMessage::setCompanyId);
		attributeGetterFunctions.put("userId", MBMessage::getUserId);

		cacheModelGetterFunctions.put(
			"userId", mbMessageCacheModel -> mbMessageCacheModel.userId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<MBMessage, Long>)MBMessage::setUserId);
		attributeGetterFunctions.put("userName", MBMessage::getUserName);

		cacheModelGetterFunctions.put(
			"userName", mbMessageCacheModel -> mbMessageCacheModel.userName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<MBMessage, String>)MBMessage::setUserName);
		attributeGetterFunctions.put("createDate", MBMessage::getCreateDate);

		cacheModelGetterFunctions.put(
			"createDate",
			mbMessageCacheModel -> mbMessageCacheModel.createDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<MBMessage, Date>)MBMessage::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", MBMessage::getModifiedDate);

		cacheModelGetterFunctions.put(
			"modifiedDate",
			mbMessageCacheModel -> mbMessageCacheModel.modifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<MBMessage, Date>)MBMessage::setModifiedDate);
		attributeGetterFunctions.put("classNameId", MBMessage::getClassNameId);

		cacheModelGetterFunctions.put(
			"classNameId",
			mbMessageCacheModel -> mbMessageCacheModel.classNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<MBMessage, Long>)MBMessage::setClassNameId);
		attributeGetterFunctions.put("classPK", MBMessage::getClassPK);

		cacheModelGetterFunctions.put(
			"classPK", mbMessageCacheModel -> mbMessageCacheModel.classPK);
		attributeSetterBiConsumers.put(
			"classPK", (BiConsumer<MBMessage, Long>)MBMessage::setClassPK);
		attributeGetterFunctions.put("categoryId", MBMessage::getCategoryId);

		cacheModelGetterFunctions.put(
			"categoryId",
			mbMessageCacheModel -> mbMessageCacheModel.categoryId);
		attributeSetterBiConsumers.put(
			"categoryId",
			(BiConsumer<MBMessage, Long>)MBMessage::setCategoryId);
		attributeGetterFunctions.put("threadId", MBMessage::getThreadId);

		cacheModelGetterFunctions.put(
			"threadId", mbMessageCacheModel -> mbMessageCacheModel.threadId);
		attributeSetterBiConsumers.put(
			"threadId", (BiConsumer<MBMessage, Long>)MBMessage::setThreadId);
		attributeGetterFunctions.put(
			"rootMessageId", MBMessage::getRootMessageId);

		cacheModelGetterFunctions.put(
			"rootMessageId",
			mbMessageCacheModel -> mbMessageCacheModel.rootMessageId);
		attributeSetterBiConsumers.put(
			"rootMessageId",
			(BiConsumer<MBMessage, Long>)MBMessage::setRootMessageId);
		attributeGetterFunctions.put(
			"parentMessageId", MBMessage::getParentMessageId);

		cacheModelGetterFunctions.put(
			"parentMessageId",
			mbMessageCacheModel -> mbMessageCacheModel.parentMessageId);
		attributeSetterBiConsumers.put(
			"parentMessageId",
			(BiConsumer<MBMessage, Long>)MBMessage::setParentMessageId);
		attributeGetterFunctions.put("treePath", MBMessage::getTreePath);

		cacheModelGetterFunctions.put(
			"treePath", mbMessageCacheModel -> mbMessageCacheModel.treePath);
		attributeSetterBiConsumers.put(
			"treePath", (BiConsumer<MBMessage, String>)MBMessage::setTreePath);
		attributeGetterFunctions.put("subject", MBMessage::getSubject);

		cacheModelGetterFunctions.put(
			"subject", mbMessageCacheModel -> mbMessageCacheModel.subject);
		attributeSetterBiConsumers.put(
			"subject", (BiConsumer<MBMessage, String>)MBMessage::setSubject);
		attributeGetterFunctions.put("urlSubject", MBMessage::getUrlSubject);

		cacheModelGetterFunctions.put(
			"urlSubject",
			mbMessageCacheModel -> mbMessageCacheModel.urlSubject);
		attributeSetterBiConsumers.put(
			"urlSubject",
			(BiConsumer<MBMessage, String>)MBMessage::setUrlSubject);
		attributeGetterFunctions.put("body", MBMessage::getBody);

		cacheModelGetterFunctions.put(
			"body", mbMessageCacheModel -> mbMessageCacheModel.body);
		attributeSetterBiConsumers.put(
			"body", (BiConsumer<MBMessage, String>)MBMessage::setBody);
		attributeGetterFunctions.put("format", MBMessage::getFormat);

		cacheModelGetterFunctions.put(
			"format", mbMessageCacheModel -> mbMessageCacheModel.format);
		attributeSetterBiConsumers.put(
			"format", (BiConsumer<MBMessage, String>)MBMessage::setFormat);
		attributeGetterFunctions.put("anonymous", MBMessage::getAnonymous);

		cacheModelGetterFunctions.put(
			"anonymous", mbMessageCacheModel -> mbMessageCacheModel.anonymous);
		attributeSetterBiConsumers.put(
			"anonymous",
			(BiConsumer<MBMessage, Boolean>)MBMessage::setAnonymous);
		attributeGetterFunctions.put("priority", MBMessage::getPriority);

		cacheModelGetterFunctions.put(
			"priority", mbMessageCacheModel -> mbMessageCacheModel.priority);
		attributeSetterBiConsumers.put(
			"priority", (BiConsumer<MBMessage, Double>)MBMessage::setPriority);
		attributeGetterFunctions.put(
			"allowPingbacks", MBMessage::getAllowPingbacks);

		cacheModelGetterFunctions.put(
			"allowPingbacks",
			mbMessageCacheModel -> mbMessageCacheModel.allowPingbacks);
		attributeSetterBiConsumers.put(
			"allowPingbacks",
			(BiConsumer<MBMessage, Boolean>)MBMessage::setAllowPingbacks);
		attributeGetterFunctions.put("answer", MBMessage::getAnswer);

		cacheModelGetterFunctions.put(
			"answer", mbMessageCacheModel -> mbMessageCacheModel.answer);
		attributeSetterBiConsumers.put(
			"answer", (BiConsumer<MBMessage, Boolean>)MBMessage::setAnswer);
		attributeGetterFunctions.put(
			"lastPublishDate", MBMessage::getLastPublishDate);

		cacheModelGetterFunctions.put(
			"lastPublishDate",
			mbMessageCacheModel -> mbMessageCacheModel.lastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<MBMessage, Date>)MBMessage::setLastPublishDate);
		attributeGetterFunctions.put("status", MBMessage::getStatus);

		cacheModelGetterFunctions.put(
			"status", mbMessageCacheModel -> mbMessageCacheModel.status);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<MBMessage, Integer>)MBMessage::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", MBMessage::getStatusByUserId);

		cacheModelGetterFunctions.put(
			"statusByUserId",
			mbMessageCacheModel -> mbMessageCacheModel.statusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<MBMessage, Long>)MBMessage::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", MBMessage::getStatusByUserName);

		cacheModelGetterFunctions.put(
			"statusByUserName",
			mbMessageCacheModel -> mbMessageCacheModel.statusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<MBMessage, String>)MBMessage::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", MBMessage::getStatusDate);

		cacheModelGetterFunctions.put(
			"statusDate",
			mbMessageCacheModel -> mbMessageCacheModel.statusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<MBMessage, Date>)MBMessage::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
		_cacheModelGetterFunctions = Collections.unmodifiableMap(
			cacheModelGetterFunctions);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_columnBitmask |= MVCCVERSION_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		_columnBitmask |= CTCOLLECTIONID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getCacheModelAttribute("uuid");
	}

	@JSON
	@Override
	public long getMessageId() {
		return _messageId;
	}

	@Override
	public void setMessageId(long messageId) {
		_columnBitmask |= MESSAGEID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_messageId = messageId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return getCacheModelAttribute("groupId");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return getCacheModelAttribute("companyId");
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return getCacheModelAttribute("userId");
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_columnBitmask |= USERNAME_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask |= CREATEDATE_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask |= MODIFIEDDATE_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return getCacheModelAttribute("classNameId");
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return getCacheModelAttribute("classPK");
	}

	@JSON
	@Override
	public long getCategoryId() {
		return _categoryId;
	}

	@Override
	public void setCategoryId(long categoryId) {
		_columnBitmask |= CATEGORYID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_categoryId = categoryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalCategoryId() {
		return getCacheModelAttribute("categoryId");
	}

	@JSON
	@Override
	public long getThreadId() {
		return _threadId;
	}

	@Override
	public void setThreadId(long threadId) {
		_columnBitmask |= THREADID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_threadId = threadId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalThreadId() {
		return getCacheModelAttribute("threadId");
	}

	@JSON
	@Override
	public long getRootMessageId() {
		return _rootMessageId;
	}

	@Override
	public void setRootMessageId(long rootMessageId) {
		_columnBitmask |= ROOTMESSAGEID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_rootMessageId = rootMessageId;
	}

	@JSON
	@Override
	public long getParentMessageId() {
		return _parentMessageId;
	}

	@Override
	public void setParentMessageId(long parentMessageId) {
		_columnBitmask |= PARENTMESSAGEID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_parentMessageId = parentMessageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalParentMessageId() {
		return getCacheModelAttribute("parentMessageId");
	}

	@JSON
	@Override
	public String getTreePath() {
		if (_treePath == null) {
			return "";
		}
		else {
			return _treePath;
		}
	}

	@Override
	public void setTreePath(String treePath) {
		_columnBitmask |= TREEPATH_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_treePath = treePath;
	}

	@JSON
	@Override
	public String getSubject() {
		if (_subject == null) {
			return "";
		}
		else {
			return _subject;
		}
	}

	@Override
	public void setSubject(String subject) {
		_columnBitmask |= SUBJECT_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_subject = subject;
	}

	@JSON
	@Override
	public String getUrlSubject() {
		if (_urlSubject == null) {
			return "";
		}
		else {
			return _urlSubject;
		}
	}

	@Override
	public void setUrlSubject(String urlSubject) {
		_columnBitmask |= URLSUBJECT_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_urlSubject = urlSubject;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalUrlSubject() {
		return getCacheModelAttribute("urlSubject");
	}

	@JSON
	@Override
	public String getBody() {
		if (_body == null) {
			return "";
		}
		else {
			return _body;
		}
	}

	@Override
	public void setBody(String body) {
		_columnBitmask |= BODY_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_body = body;
	}

	@JSON
	@Override
	public String getFormat() {
		if (_format == null) {
			return "";
		}
		else {
			return _format;
		}
	}

	@Override
	public void setFormat(String format) {
		_columnBitmask |= FORMAT_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_format = format;
	}

	@JSON
	@Override
	public boolean getAnonymous() {
		return _anonymous;
	}

	@JSON
	@Override
	public boolean isAnonymous() {
		return _anonymous;
	}

	@Override
	public void setAnonymous(boolean anonymous) {
		_columnBitmask |= ANONYMOUS_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_anonymous = anonymous;
	}

	@JSON
	@Override
	public double getPriority() {
		return _priority;
	}

	@Override
	public void setPriority(double priority) {
		_columnBitmask |= PRIORITY_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_priority = priority;
	}

	@JSON
	@Override
	public boolean getAllowPingbacks() {
		return _allowPingbacks;
	}

	@JSON
	@Override
	public boolean isAllowPingbacks() {
		return _allowPingbacks;
	}

	@Override
	public void setAllowPingbacks(boolean allowPingbacks) {
		_columnBitmask |= ALLOWPINGBACKS_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_allowPingbacks = allowPingbacks;
	}

	@JSON
	@Override
	public boolean getAnswer() {
		return _answer;
	}

	@JSON
	@Override
	public boolean isAnswer() {
		return _answer;
	}

	@Override
	public void setAnswer(boolean answer) {
		_columnBitmask |= ANSWER_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_answer = answer;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public boolean getOriginalAnswer() {
		return getCacheModelAttribute("answer");
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_columnBitmask |= LASTPUBLISHDATE_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return getCacheModelAttribute("status");
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_columnBitmask |= STATUSBYUSERID_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_columnBitmask |= STATUSBYUSERNAME_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_columnBitmask |= STATUSDATE_COLUMN_BITMASK;

		if (!isNew() && (_mbMessageCacheModel == null)) {
			_mbMessageCacheModel = (MBMessageCacheModel)toCacheModel();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(MBMessage.class.getName()),
			getClassNameId());
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), MBMessage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MBMessage toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, MBMessage>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MBMessageImpl mbMessageImpl = new MBMessageImpl();

		mbMessageImpl.setMvccVersion(getMvccVersion());
		mbMessageImpl.setCtCollectionId(getCtCollectionId());
		mbMessageImpl.setUuid(getUuid());
		mbMessageImpl.setMessageId(getMessageId());
		mbMessageImpl.setGroupId(getGroupId());
		mbMessageImpl.setCompanyId(getCompanyId());
		mbMessageImpl.setUserId(getUserId());
		mbMessageImpl.setUserName(getUserName());
		mbMessageImpl.setCreateDate(getCreateDate());
		mbMessageImpl.setModifiedDate(getModifiedDate());
		mbMessageImpl.setClassNameId(getClassNameId());
		mbMessageImpl.setClassPK(getClassPK());
		mbMessageImpl.setCategoryId(getCategoryId());
		mbMessageImpl.setThreadId(getThreadId());
		mbMessageImpl.setRootMessageId(getRootMessageId());
		mbMessageImpl.setParentMessageId(getParentMessageId());
		mbMessageImpl.setTreePath(getTreePath());
		mbMessageImpl.setSubject(getSubject());
		mbMessageImpl.setUrlSubject(getUrlSubject());
		mbMessageImpl.setBody(getBody());
		mbMessageImpl.setFormat(getFormat());
		mbMessageImpl.setAnonymous(isAnonymous());
		mbMessageImpl.setPriority(getPriority());
		mbMessageImpl.setAllowPingbacks(isAllowPingbacks());
		mbMessageImpl.setAnswer(isAnswer());
		mbMessageImpl.setLastPublishDate(getLastPublishDate());
		mbMessageImpl.setStatus(getStatus());
		mbMessageImpl.setStatusByUserId(getStatusByUserId());
		mbMessageImpl.setStatusByUserName(getStatusByUserName());
		mbMessageImpl.setStatusDate(getStatusDate());

		mbMessageImpl.resetOriginalValues();

		return mbMessageImpl;
	}

	@Override
	public int compareTo(MBMessage mbMessage) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), mbMessage.getCreateDate());

		if (value != 0) {
			return value;
		}

		if (getMessageId() < mbMessage.getMessageId()) {
			value = -1;
		}
		else if (getMessageId() > mbMessage.getMessageId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof MBMessage)) {
			return false;
		}

		MBMessage mbMessage = (MBMessage)object;

		long primaryKey = mbMessage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;

		_columnBitmask = 0;

		_mbMessageCacheModel = null;
	}

	@Override
	public CacheModel<MBMessage> toCacheModel() {
		MBMessageCacheModel mbMessageCacheModel = new MBMessageCacheModel();

		mbMessageCacheModel.mvccVersion = getMvccVersion();

		mbMessageCacheModel.ctCollectionId = getCtCollectionId();

		mbMessageCacheModel.uuid = getUuid();

		String uuid = mbMessageCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			mbMessageCacheModel.uuid = null;
		}

		mbMessageCacheModel.messageId = getMessageId();

		mbMessageCacheModel.groupId = getGroupId();

		mbMessageCacheModel.companyId = getCompanyId();

		mbMessageCacheModel.userId = getUserId();

		mbMessageCacheModel.userName = getUserName();

		String userName = mbMessageCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			mbMessageCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			mbMessageCacheModel.createDate = createDate.getTime();
		}
		else {
			mbMessageCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			mbMessageCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			mbMessageCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		mbMessageCacheModel.classNameId = getClassNameId();

		mbMessageCacheModel.classPK = getClassPK();

		mbMessageCacheModel.categoryId = getCategoryId();

		mbMessageCacheModel.threadId = getThreadId();

		mbMessageCacheModel.rootMessageId = getRootMessageId();

		mbMessageCacheModel.parentMessageId = getParentMessageId();

		mbMessageCacheModel.treePath = getTreePath();

		String treePath = mbMessageCacheModel.treePath;

		if ((treePath != null) && (treePath.length() == 0)) {
			mbMessageCacheModel.treePath = null;
		}

		mbMessageCacheModel.subject = getSubject();

		String subject = mbMessageCacheModel.subject;

		if ((subject != null) && (subject.length() == 0)) {
			mbMessageCacheModel.subject = null;
		}

		mbMessageCacheModel.urlSubject = getUrlSubject();

		String urlSubject = mbMessageCacheModel.urlSubject;

		if ((urlSubject != null) && (urlSubject.length() == 0)) {
			mbMessageCacheModel.urlSubject = null;
		}

		mbMessageCacheModel.body = getBody();

		String body = mbMessageCacheModel.body;

		if ((body != null) && (body.length() == 0)) {
			mbMessageCacheModel.body = null;
		}

		mbMessageCacheModel.format = getFormat();

		String format = mbMessageCacheModel.format;

		if ((format != null) && (format.length() == 0)) {
			mbMessageCacheModel.format = null;
		}

		mbMessageCacheModel.anonymous = isAnonymous();

		mbMessageCacheModel.priority = getPriority();

		mbMessageCacheModel.allowPingbacks = isAllowPingbacks();

		mbMessageCacheModel.answer = isAnswer();

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			mbMessageCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			mbMessageCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		mbMessageCacheModel.status = getStatus();

		mbMessageCacheModel.statusByUserId = getStatusByUserId();

		mbMessageCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = mbMessageCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			mbMessageCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			mbMessageCacheModel.statusDate = statusDate.getTime();
		}
		else {
			mbMessageCacheModel.statusDate = Long.MIN_VALUE;
		}

		return mbMessageCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<MBMessage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<MBMessage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MBMessage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((MBMessage)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<MBMessage, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<MBMessage, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<MBMessage, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((MBMessage)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, MBMessage>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _messageId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private long _categoryId;
	private long _threadId;
	private long _rootMessageId;
	private long _parentMessageId;
	private String _treePath;
	private String _subject;
	private String _urlSubject;
	private String _body;
	private String _format;
	private boolean _anonymous;
	private double _priority;
	private boolean _allowPingbacks;
	private boolean _answer;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private MBMessage _escapedModel;
	private MBMessageCacheModel _mbMessageCacheModel;

}