/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.journal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.journal.model.JournalArticle;
import com.liferay.journal.model.JournalArticleModel;
import com.liferay.journal.model.JournalArticleSoap;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.MathUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the JournalArticle service. Represents a row in the &quot;JournalArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>JournalArticleModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JournalArticleImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see JournalArticleImpl
 * @generated
 */
@JSON(strict = true)
public class JournalArticleModelImpl
	extends BaseModelImpl<JournalArticle> implements JournalArticleModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a journal article model instance should use the <code>JournalArticle</code> interface instead.
	 */
	public static final String TABLE_NAME = "JournalArticle";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"resourcePrimKey", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"folderId", Types.BIGINT},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"treePath", Types.VARCHAR}, {"articleId", Types.VARCHAR},
		{"version", Types.DOUBLE}, {"urlTitle", Types.VARCHAR},
		{"content", Types.CLOB}, {"DDMStructureKey", Types.VARCHAR},
		{"DDMTemplateKey", Types.VARCHAR}, {"defaultLanguageId", Types.VARCHAR},
		{"layoutUuid", Types.VARCHAR}, {"displayDate", Types.TIMESTAMP},
		{"expirationDate", Types.TIMESTAMP}, {"reviewDate", Types.TIMESTAMP},
		{"indexable", Types.BOOLEAN}, {"smallImage", Types.BOOLEAN},
		{"smallImageId", Types.BIGINT}, {"smallImageURL", Types.VARCHAR},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourcePrimKey", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("folderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("treePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("articleId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("urlTitle", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("content", Types.CLOB);
		TABLE_COLUMNS_MAP.put("DDMStructureKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DDMTemplateKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("defaultLanguageId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("layoutUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("displayDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("reviewDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("indexable", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("smallImage", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("smallImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("smallImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table JournalArticle (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,id_ LONG not null,resourcePrimKey LONG,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,folderId LONG,classNameId LONG,classPK LONG,treePath STRING null,articleId VARCHAR(75) null,version DOUBLE,urlTitle VARCHAR(255) null,content TEXT null,DDMStructureKey VARCHAR(75) null,DDMTemplateKey VARCHAR(75) null,defaultLanguageId VARCHAR(75) null,layoutUuid VARCHAR(75) null,displayDate DATE null,expirationDate DATE null,reviewDate DATE null,indexable BOOLEAN,smallImage BOOLEAN,smallImageId LONG,smallImageURL STRING null,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,primary key (id_, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table JournalArticle";

	public static final String ORDER_BY_JPQL =
		" ORDER BY journalArticle.articleId ASC, journalArticle.version DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY JournalArticle.articleId ASC, JournalArticle.version DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long DDMSTRUCTUREKEY_COLUMN_BITMASK = 1L;

	public static final long DDMTEMPLATEKEY_COLUMN_BITMASK = 2L;

	public static final long ARTICLEID_COLUMN_BITMASK = 4L;

	public static final long CLASSNAMEID_COLUMN_BITMASK = 8L;

	public static final long CLASSPK_COLUMN_BITMASK = 16L;

	public static final long COMPANYID_COLUMN_BITMASK = 32L;

	public static final long DISPLAYDATE_COLUMN_BITMASK = 64L;

	public static final long EXPIRATIONDATE_COLUMN_BITMASK = 128L;

	public static final long FOLDERID_COLUMN_BITMASK = 256L;

	public static final long GROUPID_COLUMN_BITMASK = 512L;

	public static final long INDEXABLE_COLUMN_BITMASK = 1024L;

	public static final long LAYOUTUUID_COLUMN_BITMASK = 2048L;

	public static final long RESOURCEPRIMKEY_COLUMN_BITMASK = 4096L;

	public static final long SMALLIMAGEID_COLUMN_BITMASK = 8192L;

	public static final long STATUS_COLUMN_BITMASK = 16384L;

	public static final long URLTITLE_COLUMN_BITMASK = 32768L;

	public static final long USERID_COLUMN_BITMASK = 65536L;

	public static final long UUID_COLUMN_BITMASK = 131072L;

	public static final long VERSION_COLUMN_BITMASK = 262144L;

	public static final int MVCCVERSION_COLUMN_INDEX = 0;

	public static final int CTCOLLECTIONID_COLUMN_INDEX = 1;

	public static final int UUID_COLUMN_INDEX = 2;

	public static final int ID_COLUMN_INDEX = 3;

	public static final int RESOURCEPRIMKEY_COLUMN_INDEX = 4;

	public static final int GROUPID_COLUMN_INDEX = 5;

	public static final int COMPANYID_COLUMN_INDEX = 6;

	public static final int USERID_COLUMN_INDEX = 7;

	public static final int USERNAME_COLUMN_INDEX = 8;

	public static final int CREATEDATE_COLUMN_INDEX = 9;

	public static final int MODIFIEDDATE_COLUMN_INDEX = 10;

	public static final int FOLDERID_COLUMN_INDEX = 11;

	public static final int CLASSNAMEID_COLUMN_INDEX = 12;

	public static final int CLASSPK_COLUMN_INDEX = 13;

	public static final int TREEPATH_COLUMN_INDEX = 14;

	public static final int ARTICLEID_COLUMN_INDEX = 15;

	public static final int VERSION_COLUMN_INDEX = 16;

	public static final int URLTITLE_COLUMN_INDEX = 17;

	public static final int CONTENT_COLUMN_INDEX = 18;

	public static final int DDMSTRUCTUREKEY_COLUMN_INDEX = 19;

	public static final int DDMTEMPLATEKEY_COLUMN_INDEX = 20;

	public static final int DEFAULTLANGUAGEID_COLUMN_INDEX = 21;

	public static final int LAYOUTUUID_COLUMN_INDEX = 22;

	public static final int DISPLAYDATE_COLUMN_INDEX = 23;

	public static final int EXPIRATIONDATE_COLUMN_INDEX = 24;

	public static final int REVIEWDATE_COLUMN_INDEX = 25;

	public static final int INDEXABLE_COLUMN_INDEX = 26;

	public static final int SMALLIMAGE_COLUMN_INDEX = 27;

	public static final int SMALLIMAGEID_COLUMN_INDEX = 28;

	public static final int SMALLIMAGEURL_COLUMN_INDEX = 29;

	public static final int LASTPUBLISHDATE_COLUMN_INDEX = 30;

	public static final int STATUS_COLUMN_INDEX = 31;

	public static final int STATUSBYUSERID_COLUMN_INDEX = 32;

	public static final int STATUSBYUSERNAME_COLUMN_INDEX = 33;

	public static final int STATUSDATE_COLUMN_INDEX = 34;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static JournalArticle toModel(JournalArticleSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		JournalArticle model = new JournalArticleImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setCtCollectionId(soapModel.getCtCollectionId());
		model.setUuid(soapModel.getUuid());
		model.setId(soapModel.getId());
		model.setResourcePrimKey(soapModel.getResourcePrimKey());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setFolderId(soapModel.getFolderId());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setTreePath(soapModel.getTreePath());
		model.setArticleId(soapModel.getArticleId());
		model.setVersion(soapModel.getVersion());
		model.setUrlTitle(soapModel.getUrlTitle());
		model.setContent(soapModel.getContent());
		model.setDDMStructureKey(soapModel.getDDMStructureKey());
		model.setDDMTemplateKey(soapModel.getDDMTemplateKey());
		model.setDefaultLanguageId(soapModel.getDefaultLanguageId());
		model.setLayoutUuid(soapModel.getLayoutUuid());
		model.setDisplayDate(soapModel.getDisplayDate());
		model.setExpirationDate(soapModel.getExpirationDate());
		model.setReviewDate(soapModel.getReviewDate());
		model.setIndexable(soapModel.isIndexable());
		model.setSmallImage(soapModel.isSmallImage());
		model.setSmallImageId(soapModel.getSmallImageId());
		model.setSmallImageURL(soapModel.getSmallImageURL());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<JournalArticle> toModels(
		JournalArticleSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<JournalArticle> models = new ArrayList<JournalArticle>(
			soapModels.length);

		for (JournalArticleSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public JournalArticleModelImpl() {
		Arrays.fill(_originalValues, INITIAL_MARKER);
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return JournalArticle.class;
	}

	@Override
	public String getModelClassName() {
		return JournalArticle.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<JournalArticle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<JournalArticle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JournalArticle, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((JournalArticle)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<JournalArticle, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<JournalArticle, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(JournalArticle)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<JournalArticle, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<JournalArticle, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, JournalArticle>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			JournalArticle.class.getClassLoader(), JournalArticle.class,
			ModelWrapper.class);

		try {
			Constructor<JournalArticle> constructor =
				(Constructor<JournalArticle>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<JournalArticle, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<JournalArticle, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<JournalArticle, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<JournalArticle, Object>>();
		Map<String, BiConsumer<JournalArticle, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<JournalArticle, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", JournalArticle::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<JournalArticle, Long>)JournalArticle::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", JournalArticle::getCtCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<JournalArticle, Long>)
				JournalArticle::setCtCollectionId);
		attributeGetterFunctions.put("uuid", JournalArticle::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<JournalArticle, String>)JournalArticle::setUuid);
		attributeGetterFunctions.put("id", JournalArticle::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<JournalArticle, Long>)JournalArticle::setId);
		attributeGetterFunctions.put(
			"resourcePrimKey", JournalArticle::getResourcePrimKey);
		attributeSetterBiConsumers.put(
			"resourcePrimKey",
			(BiConsumer<JournalArticle, Long>)
				JournalArticle::setResourcePrimKey);
		attributeGetterFunctions.put("groupId", JournalArticle::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<JournalArticle, Long>)JournalArticle::setGroupId);
		attributeGetterFunctions.put("companyId", JournalArticle::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<JournalArticle, Long>)JournalArticle::setCompanyId);
		attributeGetterFunctions.put("userId", JournalArticle::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<JournalArticle, Long>)JournalArticle::setUserId);
		attributeGetterFunctions.put("userName", JournalArticle::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<JournalArticle, String>)JournalArticle::setUserName);
		attributeGetterFunctions.put(
			"createDate", JournalArticle::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<JournalArticle, Date>)JournalArticle::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", JournalArticle::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<JournalArticle, Date>)JournalArticle::setModifiedDate);
		attributeGetterFunctions.put("folderId", JournalArticle::getFolderId);
		attributeSetterBiConsumers.put(
			"folderId",
			(BiConsumer<JournalArticle, Long>)JournalArticle::setFolderId);
		attributeGetterFunctions.put(
			"classNameId", JournalArticle::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<JournalArticle, Long>)JournalArticle::setClassNameId);
		attributeGetterFunctions.put("classPK", JournalArticle::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<JournalArticle, Long>)JournalArticle::setClassPK);
		attributeGetterFunctions.put("treePath", JournalArticle::getTreePath);
		attributeSetterBiConsumers.put(
			"treePath",
			(BiConsumer<JournalArticle, String>)JournalArticle::setTreePath);
		attributeGetterFunctions.put("articleId", JournalArticle::getArticleId);
		attributeSetterBiConsumers.put(
			"articleId",
			(BiConsumer<JournalArticle, String>)JournalArticle::setArticleId);
		attributeGetterFunctions.put("version", JournalArticle::getVersion);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<JournalArticle, Double>)JournalArticle::setVersion);
		attributeGetterFunctions.put("urlTitle", JournalArticle::getUrlTitle);
		attributeSetterBiConsumers.put(
			"urlTitle",
			(BiConsumer<JournalArticle, String>)JournalArticle::setUrlTitle);
		attributeGetterFunctions.put("content", JournalArticle::getContent);
		attributeSetterBiConsumers.put(
			"content",
			(BiConsumer<JournalArticle, String>)JournalArticle::setContent);
		attributeGetterFunctions.put(
			"DDMStructureKey", JournalArticle::getDDMStructureKey);
		attributeSetterBiConsumers.put(
			"DDMStructureKey",
			(BiConsumer<JournalArticle, String>)
				JournalArticle::setDDMStructureKey);
		attributeGetterFunctions.put(
			"DDMTemplateKey", JournalArticle::getDDMTemplateKey);
		attributeSetterBiConsumers.put(
			"DDMTemplateKey",
			(BiConsumer<JournalArticle, String>)
				JournalArticle::setDDMTemplateKey);
		attributeGetterFunctions.put(
			"defaultLanguageId", JournalArticle::getDefaultLanguageId);
		attributeSetterBiConsumers.put(
			"defaultLanguageId",
			(BiConsumer<JournalArticle, String>)
				JournalArticle::setDefaultLanguageId);
		attributeGetterFunctions.put(
			"layoutUuid", JournalArticle::getLayoutUuid);
		attributeSetterBiConsumers.put(
			"layoutUuid",
			(BiConsumer<JournalArticle, String>)JournalArticle::setLayoutUuid);
		attributeGetterFunctions.put(
			"displayDate", JournalArticle::getDisplayDate);
		attributeSetterBiConsumers.put(
			"displayDate",
			(BiConsumer<JournalArticle, Date>)JournalArticle::setDisplayDate);
		attributeGetterFunctions.put(
			"expirationDate", JournalArticle::getExpirationDate);
		attributeSetterBiConsumers.put(
			"expirationDate",
			(BiConsumer<JournalArticle, Date>)
				JournalArticle::setExpirationDate);
		attributeGetterFunctions.put(
			"reviewDate", JournalArticle::getReviewDate);
		attributeSetterBiConsumers.put(
			"reviewDate",
			(BiConsumer<JournalArticle, Date>)JournalArticle::setReviewDate);
		attributeGetterFunctions.put("indexable", JournalArticle::getIndexable);
		attributeSetterBiConsumers.put(
			"indexable",
			(BiConsumer<JournalArticle, Boolean>)JournalArticle::setIndexable);
		attributeGetterFunctions.put(
			"smallImage", JournalArticle::getSmallImage);
		attributeSetterBiConsumers.put(
			"smallImage",
			(BiConsumer<JournalArticle, Boolean>)JournalArticle::setSmallImage);
		attributeGetterFunctions.put(
			"smallImageId", JournalArticle::getSmallImageId);
		attributeSetterBiConsumers.put(
			"smallImageId",
			(BiConsumer<JournalArticle, Long>)JournalArticle::setSmallImageId);
		attributeGetterFunctions.put(
			"smallImageURL", JournalArticle::getSmallImageURL);
		attributeSetterBiConsumers.put(
			"smallImageURL",
			(BiConsumer<JournalArticle, String>)
				JournalArticle::setSmallImageURL);
		attributeGetterFunctions.put(
			"lastPublishDate", JournalArticle::getLastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<JournalArticle, Date>)
				JournalArticle::setLastPublishDate);
		attributeGetterFunctions.put("status", JournalArticle::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<JournalArticle, Integer>)JournalArticle::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", JournalArticle::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<JournalArticle, Long>)
				JournalArticle::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", JournalArticle::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<JournalArticle, String>)
				JournalArticle::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", JournalArticle::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<JournalArticle, Date>)JournalArticle::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalValues[UUID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[UUID_COLUMN_INDEX] = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		Object originalValue = _originalValues[UUID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _uuid;
		}

		return GetterUtil.getString(originalValue);
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getResourcePrimKey() {
		return _resourcePrimKey;
	}

	@Override
	public void setResourcePrimKey(long resourcePrimKey) {
		if (_originalValues[RESOURCEPRIMKEY_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[RESOURCEPRIMKEY_COLUMN_INDEX] = _resourcePrimKey;
		}

		_resourcePrimKey = resourcePrimKey;
	}

	@Override
	public boolean isResourceMain() {
		return true;
	}

	public long getOriginalResourcePrimKey() {
		Object originalValue = _originalValues[RESOURCEPRIMKEY_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _resourcePrimKey;
		}

		return (long)originalValue;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_originalValues[GROUPID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[GROUPID_COLUMN_INDEX] = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		Object originalValue = _originalValues[GROUPID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _groupId;
		}

		return (long)originalValue;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_originalValues[COMPANYID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[COMPANYID_COLUMN_INDEX] = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		Object originalValue = _originalValues[COMPANYID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _companyId;
		}

		return (long)originalValue;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_originalValues[USERID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[USERID_COLUMN_INDEX] = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		Object originalValue = _originalValues[USERID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _userId;
		}

		return (long)originalValue;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getFolderId() {
		return _folderId;
	}

	@Override
	public void setFolderId(long folderId) {
		if (_originalValues[FOLDERID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[FOLDERID_COLUMN_INDEX] = _folderId;
		}

		_folderId = folderId;
	}

	public long getOriginalFolderId() {
		Object originalValue = _originalValues[FOLDERID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _folderId;
		}

		return (long)originalValue;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_originalValues[CLASSNAMEID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[CLASSNAMEID_COLUMN_INDEX] = _classNameId;
		}

		_classNameId = classNameId;
	}

	public long getOriginalClassNameId() {
		Object originalValue = _originalValues[CLASSNAMEID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _classNameId;
		}

		return (long)originalValue;
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_originalValues[CLASSPK_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[CLASSPK_COLUMN_INDEX] = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		Object originalValue = _originalValues[CLASSPK_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _classPK;
		}

		return (long)originalValue;
	}

	@JSON
	@Override
	public String getTreePath() {
		if (_treePath == null) {
			return "";
		}
		else {
			return _treePath;
		}
	}

	@Override
	public void setTreePath(String treePath) {
		_treePath = treePath;
	}

	@JSON
	@Override
	public String getArticleId() {
		if (_articleId == null) {
			return "";
		}
		else {
			return _articleId;
		}
	}

	@Override
	public void setArticleId(String articleId) {
		_columnBitmask = -1L;

		if (_originalValues[ARTICLEID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[ARTICLEID_COLUMN_INDEX] = _articleId;
		}

		_articleId = articleId;
	}

	public String getOriginalArticleId() {
		Object originalValue = _originalValues[ARTICLEID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _articleId;
		}

		return GetterUtil.getString(originalValue);
	}

	@JSON
	@Override
	public double getVersion() {
		return _version;
	}

	@Override
	public void setVersion(double version) {
		_columnBitmask = -1L;

		if (_originalValues[VERSION_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[VERSION_COLUMN_INDEX] = _version;
		}

		_version = version;
	}

	public double getOriginalVersion() {
		Object originalValue = _originalValues[VERSION_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _version;
		}

		return (double)originalValue;
	}

	@JSON
	@Override
	public String getUrlTitle() {
		if (_urlTitle == null) {
			return "";
		}
		else {
			return _urlTitle;
		}
	}

	@Override
	public void setUrlTitle(String urlTitle) {
		if (_originalValues[URLTITLE_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[URLTITLE_COLUMN_INDEX] = _urlTitle;
		}

		_urlTitle = urlTitle;
	}

	public String getOriginalUrlTitle() {
		Object originalValue = _originalValues[URLTITLE_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _urlTitle;
		}

		return GetterUtil.getString(originalValue);
	}

	@JSON
	@Override
	public String getContent() {
		if (_content == null) {
			return "";
		}
		else {
			return _content;
		}
	}

	@Override
	public void setContent(String content) {
		_content = content;
	}

	@JSON
	@Override
	public String getDDMStructureKey() {
		if (_DDMStructureKey == null) {
			return "";
		}
		else {
			return _DDMStructureKey;
		}
	}

	@Override
	public void setDDMStructureKey(String DDMStructureKey) {
		if (_originalValues[DDMSTRUCTUREKEY_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[DDMSTRUCTUREKEY_COLUMN_INDEX] = _DDMStructureKey;
		}

		_DDMStructureKey = DDMStructureKey;
	}

	public String getOriginalDDMStructureKey() {
		Object originalValue = _originalValues[DDMSTRUCTUREKEY_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _DDMStructureKey;
		}

		return GetterUtil.getString(originalValue);
	}

	@JSON
	@Override
	public String getDDMTemplateKey() {
		if (_DDMTemplateKey == null) {
			return "";
		}
		else {
			return _DDMTemplateKey;
		}
	}

	@Override
	public void setDDMTemplateKey(String DDMTemplateKey) {
		if (_originalValues[DDMTEMPLATEKEY_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[DDMTEMPLATEKEY_COLUMN_INDEX] = _DDMTemplateKey;
		}

		_DDMTemplateKey = DDMTemplateKey;
	}

	public String getOriginalDDMTemplateKey() {
		Object originalValue = _originalValues[DDMTEMPLATEKEY_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _DDMTemplateKey;
		}

		return GetterUtil.getString(originalValue);
	}

	@JSON
	@Override
	public String getDefaultLanguageId() {
		if (_defaultLanguageId == null) {
			return "";
		}
		else {
			return _defaultLanguageId;
		}
	}

	@Override
	public void setDefaultLanguageId(String defaultLanguageId) {
		_defaultLanguageId = defaultLanguageId;
	}

	@JSON
	@Override
	public String getLayoutUuid() {
		if (_layoutUuid == null) {
			return "";
		}
		else {
			return _layoutUuid;
		}
	}

	@Override
	public void setLayoutUuid(String layoutUuid) {
		if (_originalValues[LAYOUTUUID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[LAYOUTUUID_COLUMN_INDEX] = _layoutUuid;
		}

		_layoutUuid = layoutUuid;
	}

	public String getOriginalLayoutUuid() {
		Object originalValue = _originalValues[LAYOUTUUID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _layoutUuid;
		}

		return GetterUtil.getString(originalValue);
	}

	@JSON
	@Override
	public Date getDisplayDate() {
		return _displayDate;
	}

	@Override
	public void setDisplayDate(Date displayDate) {
		if (_originalValues[DISPLAYDATE_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[DISPLAYDATE_COLUMN_INDEX] = _displayDate;
		}

		_displayDate = displayDate;
	}

	public Date getOriginalDisplayDate() {
		Object originalValue = _originalValues[DISPLAYDATE_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _displayDate;
		}

		return (Date)originalValue;
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		if (_originalValues[EXPIRATIONDATE_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[EXPIRATIONDATE_COLUMN_INDEX] = _expirationDate;
		}

		_expirationDate = expirationDate;
	}

	public Date getOriginalExpirationDate() {
		Object originalValue = _originalValues[EXPIRATIONDATE_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _expirationDate;
		}

		return (Date)originalValue;
	}

	@JSON
	@Override
	public Date getReviewDate() {
		return _reviewDate;
	}

	@Override
	public void setReviewDate(Date reviewDate) {
		_reviewDate = reviewDate;
	}

	@JSON
	@Override
	public boolean getIndexable() {
		return _indexable;
	}

	@JSON
	@Override
	public boolean isIndexable() {
		return _indexable;
	}

	@Override
	public void setIndexable(boolean indexable) {
		if (_originalValues[INDEXABLE_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[INDEXABLE_COLUMN_INDEX] = _indexable;
		}

		_indexable = indexable;
	}

	public boolean getOriginalIndexable() {
		Object originalValue = _originalValues[INDEXABLE_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _indexable;
		}

		return (boolean)originalValue;
	}

	@JSON
	@Override
	public boolean getSmallImage() {
		return _smallImage;
	}

	@JSON
	@Override
	public boolean isSmallImage() {
		return _smallImage;
	}

	@Override
	public void setSmallImage(boolean smallImage) {
		_smallImage = smallImage;
	}

	@JSON
	@Override
	public long getSmallImageId() {
		return _smallImageId;
	}

	@Override
	public void setSmallImageId(long smallImageId) {
		if (_originalValues[SMALLIMAGEID_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[SMALLIMAGEID_COLUMN_INDEX] = _smallImageId;
		}

		_smallImageId = smallImageId;
	}

	public long getOriginalSmallImageId() {
		Object originalValue = _originalValues[SMALLIMAGEID_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _smallImageId;
		}

		return (long)originalValue;
	}

	@JSON
	@Override
	public String getSmallImageURL() {
		if (_smallImageURL == null) {
			return "";
		}
		else {
			return _smallImageURL;
		}
	}

	@Override
	public void setSmallImageURL(String smallImageURL) {
		_smallImageURL = smallImageURL;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		if (_originalValues[STATUS_COLUMN_INDEX] == INITIAL_MARKER) {
			_originalValues[STATUS_COLUMN_INDEX] = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		Object originalValue = _originalValues[STATUS_COLUMN_INDEX];

		if (originalValue == INITIAL_MARKER) {
			originalValue = _status;
		}

		return (int)originalValue;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	public com.liferay.portal.kernel.xml.Document getDocument() {
		return null;
	}

	public void setDocument(com.liferay.portal.kernel.xml.Document document) {
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(JournalArticle.class.getName()),
			getClassNameId());
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		if (_columnBitmask == null) {
			long columnBitmask = 0;

			for (int i = 0; i < _originalValues.length; i++) {
				if (_originalValues[i] != INITIAL_MARKER) {
					columnBitmask |= MathUtil.base2Pow(i);
				}
			}

			_columnBitmask = columnBitmask;
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), JournalArticle.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public JournalArticle toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, JournalArticle>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JournalArticleImpl journalArticleImpl = new JournalArticleImpl();

		journalArticleImpl.setMvccVersion(getMvccVersion());
		journalArticleImpl.setCtCollectionId(getCtCollectionId());
		journalArticleImpl.setUuid(getUuid());
		journalArticleImpl.setId(getId());
		journalArticleImpl.setResourcePrimKey(getResourcePrimKey());
		journalArticleImpl.setGroupId(getGroupId());
		journalArticleImpl.setCompanyId(getCompanyId());
		journalArticleImpl.setUserId(getUserId());
		journalArticleImpl.setUserName(getUserName());
		journalArticleImpl.setCreateDate(getCreateDate());
		journalArticleImpl.setModifiedDate(getModifiedDate());
		journalArticleImpl.setFolderId(getFolderId());
		journalArticleImpl.setClassNameId(getClassNameId());
		journalArticleImpl.setClassPK(getClassPK());
		journalArticleImpl.setTreePath(getTreePath());
		journalArticleImpl.setArticleId(getArticleId());
		journalArticleImpl.setVersion(getVersion());
		journalArticleImpl.setUrlTitle(getUrlTitle());
		journalArticleImpl.setContent(getContent());
		journalArticleImpl.setDDMStructureKey(getDDMStructureKey());
		journalArticleImpl.setDDMTemplateKey(getDDMTemplateKey());
		journalArticleImpl.setDefaultLanguageId(getDefaultLanguageId());
		journalArticleImpl.setLayoutUuid(getLayoutUuid());
		journalArticleImpl.setDisplayDate(getDisplayDate());
		journalArticleImpl.setExpirationDate(getExpirationDate());
		journalArticleImpl.setReviewDate(getReviewDate());
		journalArticleImpl.setIndexable(isIndexable());
		journalArticleImpl.setSmallImage(isSmallImage());
		journalArticleImpl.setSmallImageId(getSmallImageId());
		journalArticleImpl.setSmallImageURL(getSmallImageURL());
		journalArticleImpl.setLastPublishDate(getLastPublishDate());
		journalArticleImpl.setStatus(getStatus());
		journalArticleImpl.setStatusByUserId(getStatusByUserId());
		journalArticleImpl.setStatusByUserName(getStatusByUserName());
		journalArticleImpl.setStatusDate(getStatusDate());

		journalArticleImpl.resetOriginalValues();

		return journalArticleImpl;
	}

	@Override
	public int compareTo(JournalArticle journalArticle) {
		int value = 0;

		value = getArticleId().compareTo(journalArticle.getArticleId());

		if (value != 0) {
			return value;
		}

		if (getVersion() < journalArticle.getVersion()) {
			value = -1;
		}
		else if (getVersion() > journalArticle.getVersion()) {
			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof JournalArticle)) {
			return false;
		}

		JournalArticle journalArticle = (JournalArticle)obj;

		long primaryKey = journalArticle.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		JournalArticleModelImpl journalArticleModelImpl = this;

		journalArticleModelImpl._setModifiedDate = false;

		Arrays.fill(_originalValues, INITIAL_MARKER);

		setDocument(null);

		journalArticleModelImpl._columnBitmask = null;
	}

	@Override
	public CacheModel<JournalArticle> toCacheModel() {
		JournalArticleCacheModel journalArticleCacheModel =
			new JournalArticleCacheModel();

		journalArticleCacheModel.mvccVersion = getMvccVersion();

		journalArticleCacheModel.ctCollectionId = getCtCollectionId();

		journalArticleCacheModel.uuid = getUuid();

		String uuid = journalArticleCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			journalArticleCacheModel.uuid = null;
		}

		journalArticleCacheModel.id = getId();

		journalArticleCacheModel.resourcePrimKey = getResourcePrimKey();

		journalArticleCacheModel.groupId = getGroupId();

		journalArticleCacheModel.companyId = getCompanyId();

		journalArticleCacheModel.userId = getUserId();

		journalArticleCacheModel.userName = getUserName();

		String userName = journalArticleCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			journalArticleCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			journalArticleCacheModel.createDate = createDate.getTime();
		}
		else {
			journalArticleCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			journalArticleCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			journalArticleCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		journalArticleCacheModel.folderId = getFolderId();

		journalArticleCacheModel.classNameId = getClassNameId();

		journalArticleCacheModel.classPK = getClassPK();

		journalArticleCacheModel.treePath = getTreePath();

		String treePath = journalArticleCacheModel.treePath;

		if ((treePath != null) && (treePath.length() == 0)) {
			journalArticleCacheModel.treePath = null;
		}

		journalArticleCacheModel.articleId = getArticleId();

		String articleId = journalArticleCacheModel.articleId;

		if ((articleId != null) && (articleId.length() == 0)) {
			journalArticleCacheModel.articleId = null;
		}

		journalArticleCacheModel.version = getVersion();

		journalArticleCacheModel.urlTitle = getUrlTitle();

		String urlTitle = journalArticleCacheModel.urlTitle;

		if ((urlTitle != null) && (urlTitle.length() == 0)) {
			journalArticleCacheModel.urlTitle = null;
		}

		journalArticleCacheModel.content = getContent();

		String content = journalArticleCacheModel.content;

		if ((content != null) && (content.length() == 0)) {
			journalArticleCacheModel.content = null;
		}

		journalArticleCacheModel.DDMStructureKey = getDDMStructureKey();

		String DDMStructureKey = journalArticleCacheModel.DDMStructureKey;

		if ((DDMStructureKey != null) && (DDMStructureKey.length() == 0)) {
			journalArticleCacheModel.DDMStructureKey = null;
		}

		journalArticleCacheModel.DDMTemplateKey = getDDMTemplateKey();

		String DDMTemplateKey = journalArticleCacheModel.DDMTemplateKey;

		if ((DDMTemplateKey != null) && (DDMTemplateKey.length() == 0)) {
			journalArticleCacheModel.DDMTemplateKey = null;
		}

		journalArticleCacheModel.defaultLanguageId = getDefaultLanguageId();

		String defaultLanguageId = journalArticleCacheModel.defaultLanguageId;

		if ((defaultLanguageId != null) && (defaultLanguageId.length() == 0)) {
			journalArticleCacheModel.defaultLanguageId = null;
		}

		journalArticleCacheModel.layoutUuid = getLayoutUuid();

		String layoutUuid = journalArticleCacheModel.layoutUuid;

		if ((layoutUuid != null) && (layoutUuid.length() == 0)) {
			journalArticleCacheModel.layoutUuid = null;
		}

		Date displayDate = getDisplayDate();

		if (displayDate != null) {
			journalArticleCacheModel.displayDate = displayDate.getTime();
		}
		else {
			journalArticleCacheModel.displayDate = Long.MIN_VALUE;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			journalArticleCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			journalArticleCacheModel.expirationDate = Long.MIN_VALUE;
		}

		Date reviewDate = getReviewDate();

		if (reviewDate != null) {
			journalArticleCacheModel.reviewDate = reviewDate.getTime();
		}
		else {
			journalArticleCacheModel.reviewDate = Long.MIN_VALUE;
		}

		journalArticleCacheModel.indexable = isIndexable();

		journalArticleCacheModel.smallImage = isSmallImage();

		journalArticleCacheModel.smallImageId = getSmallImageId();

		journalArticleCacheModel.smallImageURL = getSmallImageURL();

		String smallImageURL = journalArticleCacheModel.smallImageURL;

		if ((smallImageURL != null) && (smallImageURL.length() == 0)) {
			journalArticleCacheModel.smallImageURL = null;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			journalArticleCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			journalArticleCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		journalArticleCacheModel.status = getStatus();

		journalArticleCacheModel.statusByUserId = getStatusByUserId();

		journalArticleCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = journalArticleCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			journalArticleCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			journalArticleCacheModel.statusDate = statusDate.getTime();
		}
		else {
			journalArticleCacheModel.statusDate = Long.MIN_VALUE;
		}

		journalArticleCacheModel._document = getDocument();

		return journalArticleCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<JournalArticle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<JournalArticle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JournalArticle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((JournalArticle)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<JournalArticle, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<JournalArticle, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<JournalArticle, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((JournalArticle)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, JournalArticle>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _id;
	private long _resourcePrimKey;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _folderId;
	private long _classNameId;
	private long _classPK;
	private String _treePath;
	private String _articleId;
	private double _version;
	private String _urlTitle;
	private String _content;
	private String _DDMStructureKey;
	private String _DDMTemplateKey;
	private String _defaultLanguageId;
	private String _layoutUuid;
	private Date _displayDate;
	private Date _expirationDate;
	private Date _reviewDate;
	private boolean _indexable;
	private boolean _smallImage;
	private long _smallImageId;
	private String _smallImageURL;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private Object[] _originalValues = new Object[36];
	private Long _columnBitmask;
	private JournalArticle _escapedModel;

}