/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.documentlibrary.model.impl;

import com.liferay.document.library.kernel.model.DLFolder;
import com.liferay.document.library.kernel.model.DLFolderModel;
import com.liferay.document.library.kernel.model.DLFolderSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.NoSuchModelException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ContainerModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.TrashedModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DLFolder service. Represents a row in the &quot;DLFolder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DLFolderModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DLFolderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DLFolderImpl
 * @generated
 */
@JSON(strict = true)
public class DLFolderModelImpl
	extends BaseModelImpl<DLFolder> implements DLFolderModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a document library folder model instance should use the <code>DLFolder</code> interface instead.
	 */
	public static final String TABLE_NAME = "DLFolder";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"folderId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"repositoryId", Types.BIGINT}, {"mountPoint", Types.BOOLEAN},
		{"parentFolderId", Types.BIGINT}, {"treePath", Types.VARCHAR},
		{"name", Types.VARCHAR}, {"description", Types.VARCHAR},
		{"lastPostDate", Types.TIMESTAMP},
		{"defaultFileEntryTypeId", Types.BIGINT}, {"hidden_", Types.BOOLEAN},
		{"restrictionType", Types.INTEGER},
		{"lastPublishDate", Types.TIMESTAMP}, {"status", Types.INTEGER},
		{"statusByUserId", Types.BIGINT}, {"statusByUserName", Types.VARCHAR},
		{"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("folderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("repositoryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mountPoint", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("parentFolderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("treePath", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastPostDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("defaultFileEntryTypeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hidden_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("restrictionType", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DLFolder (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,folderId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,repositoryId LONG,mountPoint BOOLEAN,parentFolderId LONG,treePath STRING null,name VARCHAR(255) null,description STRING null,lastPostDate DATE null,defaultFileEntryTypeId LONG,hidden_ BOOLEAN,restrictionType INTEGER,lastPublishDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,primary key (folderId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table DLFolder";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dlFolder.parentFolderId ASC, dlFolder.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DLFolder.parentFolderId ASC, DLFolder.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	public static final long MVCCVERSION_COLUMN_BITMASK = 1L;

	public static final long CTCOLLECTIONID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long FOLDERID_COLUMN_BITMASK = 8L;

	public static final long GROUPID_COLUMN_BITMASK = 16L;

	public static final long COMPANYID_COLUMN_BITMASK = 32L;

	public static final long USERID_COLUMN_BITMASK = 64L;

	public static final long USERNAME_COLUMN_BITMASK = 128L;

	public static final long CREATEDATE_COLUMN_BITMASK = 256L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 512L;

	public static final long REPOSITORYID_COLUMN_BITMASK = 1024L;

	public static final long MOUNTPOINT_COLUMN_BITMASK = 2048L;

	public static final long PARENTFOLDERID_COLUMN_BITMASK = 4096L;

	public static final long TREEPATH_COLUMN_BITMASK = 8192L;

	public static final long NAME_COLUMN_BITMASK = 16384L;

	public static final long DESCRIPTION_COLUMN_BITMASK = 32768L;

	public static final long LASTPOSTDATE_COLUMN_BITMASK = 65536L;

	public static final long DEFAULTFILEENTRYTYPEID_COLUMN_BITMASK = 131072L;

	public static final long HIDDEN_COLUMN_BITMASK = 262144L;

	public static final long RESTRICTIONTYPE_COLUMN_BITMASK = 524288L;

	public static final long LASTPUBLISHDATE_COLUMN_BITMASK = 1048576L;

	public static final long STATUS_COLUMN_BITMASK = 2097152L;

	public static final long STATUSBYUSERID_COLUMN_BITMASK = 4194304L;

	public static final long STATUSBYUSERNAME_COLUMN_BITMASK = 8388608L;

	public static final long STATUSDATE_COLUMN_BITMASK = 16777216L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DLFolder toModel(DLFolderSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DLFolder model = new DLFolderImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setCtCollectionId(soapModel.getCtCollectionId());
		model.setUuid(soapModel.getUuid());
		model.setFolderId(soapModel.getFolderId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setRepositoryId(soapModel.getRepositoryId());
		model.setMountPoint(soapModel.isMountPoint());
		model.setParentFolderId(soapModel.getParentFolderId());
		model.setTreePath(soapModel.getTreePath());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setLastPostDate(soapModel.getLastPostDate());
		model.setDefaultFileEntryTypeId(soapModel.getDefaultFileEntryTypeId());
		model.setHidden(soapModel.isHidden());
		model.setRestrictionType(soapModel.getRestrictionType());
		model.setLastPublishDate(soapModel.getLastPublishDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DLFolder> toModels(DLFolderSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DLFolder> models = new ArrayList<DLFolder>(soapModels.length);

		for (DLFolderSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final String MAPPING_TABLE_DLFILEENTRYTYPES_DLFOLDERS_NAME =
		"DLFileEntryTypes_DLFolders";

	public static final Object[][]
		MAPPING_TABLE_DLFILEENTRYTYPES_DLFOLDERS_COLUMNS = {
			{"companyId", Types.BIGINT}, {"fileEntryTypeId", Types.BIGINT},
			{"folderId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_DLFILEENTRYTYPES_DLFOLDERS_SQL_CREATE =
			"create table DLFileEntryTypes_DLFolders (companyId LONG not null,fileEntryTypeId LONG not null,folderId LONG not null,ctCollectionId LONG default 0 not null,ctChangeType BOOLEAN,primary key (fileEntryTypeId, folderId, ctCollectionId))";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean
		FINDER_CACHE_ENABLED_DLFILEENTRYTYPES_DLFOLDERS = true;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.document.library.kernel.model.DLFolder"));

	public DLFolderModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _folderId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFolderId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _folderId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DLFolder.class;
	}

	@Override
	public String getModelClassName() {
		return DLFolder.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DLFolder, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DLFolder, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DLFolder, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((DLFolder)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DLFolder, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DLFolder, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DLFolder)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DLFolder, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DLFolder, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DLFolder>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DLFolder.class.getClassLoader(), DLFolder.class,
			ModelWrapper.class);

		try {
			Constructor<DLFolder> constructor =
				(Constructor<DLFolder>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	public <T> T getAttribute(String attribute) {
		Function<DLFolder, Object> function = _attributeGetterFunctions.get(
			attribute);

		if (function == null) {
			return null;
		}

		return (T)function.apply((DLFolder)this);
	}

	public <T> T getCacheModelAttribute(String attribute) {
		Function<DLFolderCacheModel, Object> function =
			_cacheModelGetterFunctions.get(attribute);

		if (function == null) {
			return null;
		}

		if (_dlFolderCacheModel == null) {
			return null;
		}

		return (T)function.apply(_dlFolderCacheModel);
	}

	private static final Map<String, Function<DLFolder, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DLFolder, Object>>
		_attributeSetterBiConsumers;
	private static final Map<String, Function<DLFolderCacheModel, Object>>
		_cacheModelGetterFunctions;

	static {
		Map<String, Function<DLFolder, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DLFolder, Object>>();
		Map<String, BiConsumer<DLFolder, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DLFolder, ?>>();
		Map<String, Function<DLFolderCacheModel, Object>>
			cacheModelGetterFunctions =
				new LinkedHashMap
					<String, Function<DLFolderCacheModel, Object>>();

		attributeGetterFunctions.put("mvccVersion", DLFolder::getMvccVersion);

		cacheModelGetterFunctions.put(
			"mvccVersion",
			dlFolderCacheModel -> dlFolderCacheModel.mvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<DLFolder, Long>)DLFolder::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", DLFolder::getCtCollectionId);

		cacheModelGetterFunctions.put(
			"ctCollectionId",
			dlFolderCacheModel -> dlFolderCacheModel.ctCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<DLFolder, Long>)DLFolder::setCtCollectionId);
		attributeGetterFunctions.put("uuid", DLFolder::getUuid);

		cacheModelGetterFunctions.put(
			"uuid", dlFolderCacheModel -> dlFolderCacheModel.uuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<DLFolder, String>)DLFolder::setUuid);
		attributeGetterFunctions.put("folderId", DLFolder::getFolderId);

		cacheModelGetterFunctions.put(
			"folderId", dlFolderCacheModel -> dlFolderCacheModel.folderId);
		attributeSetterBiConsumers.put(
			"folderId", (BiConsumer<DLFolder, Long>)DLFolder::setFolderId);
		attributeGetterFunctions.put("groupId", DLFolder::getGroupId);

		cacheModelGetterFunctions.put(
			"groupId", dlFolderCacheModel -> dlFolderCacheModel.groupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<DLFolder, Long>)DLFolder::setGroupId);
		attributeGetterFunctions.put("companyId", DLFolder::getCompanyId);

		cacheModelGetterFunctions.put(
			"companyId", dlFolderCacheModel -> dlFolderCacheModel.companyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<DLFolder, Long>)DLFolder::setCompanyId);
		attributeGetterFunctions.put("userId", DLFolder::getUserId);

		cacheModelGetterFunctions.put(
			"userId", dlFolderCacheModel -> dlFolderCacheModel.userId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<DLFolder, Long>)DLFolder::setUserId);
		attributeGetterFunctions.put("userName", DLFolder::getUserName);

		cacheModelGetterFunctions.put(
			"userName", dlFolderCacheModel -> dlFolderCacheModel.userName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<DLFolder, String>)DLFolder::setUserName);
		attributeGetterFunctions.put("createDate", DLFolder::getCreateDate);

		cacheModelGetterFunctions.put(
			"createDate", dlFolderCacheModel -> dlFolderCacheModel.createDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<DLFolder, Date>)DLFolder::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", DLFolder::getModifiedDate);

		cacheModelGetterFunctions.put(
			"modifiedDate",
			dlFolderCacheModel -> dlFolderCacheModel.modifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DLFolder, Date>)DLFolder::setModifiedDate);
		attributeGetterFunctions.put("repositoryId", DLFolder::getRepositoryId);

		cacheModelGetterFunctions.put(
			"repositoryId",
			dlFolderCacheModel -> dlFolderCacheModel.repositoryId);
		attributeSetterBiConsumers.put(
			"repositoryId",
			(BiConsumer<DLFolder, Long>)DLFolder::setRepositoryId);
		attributeGetterFunctions.put("mountPoint", DLFolder::getMountPoint);

		cacheModelGetterFunctions.put(
			"mountPoint", dlFolderCacheModel -> dlFolderCacheModel.mountPoint);
		attributeSetterBiConsumers.put(
			"mountPoint",
			(BiConsumer<DLFolder, Boolean>)DLFolder::setMountPoint);
		attributeGetterFunctions.put(
			"parentFolderId", DLFolder::getParentFolderId);

		cacheModelGetterFunctions.put(
			"parentFolderId",
			dlFolderCacheModel -> dlFolderCacheModel.parentFolderId);
		attributeSetterBiConsumers.put(
			"parentFolderId",
			(BiConsumer<DLFolder, Long>)DLFolder::setParentFolderId);
		attributeGetterFunctions.put("treePath", DLFolder::getTreePath);

		cacheModelGetterFunctions.put(
			"treePath", dlFolderCacheModel -> dlFolderCacheModel.treePath);
		attributeSetterBiConsumers.put(
			"treePath", (BiConsumer<DLFolder, String>)DLFolder::setTreePath);
		attributeGetterFunctions.put("name", DLFolder::getName);

		cacheModelGetterFunctions.put(
			"name", dlFolderCacheModel -> dlFolderCacheModel.name);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<DLFolder, String>)DLFolder::setName);
		attributeGetterFunctions.put("description", DLFolder::getDescription);

		cacheModelGetterFunctions.put(
			"description",
			dlFolderCacheModel -> dlFolderCacheModel.description);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<DLFolder, String>)DLFolder::setDescription);
		attributeGetterFunctions.put("lastPostDate", DLFolder::getLastPostDate);

		cacheModelGetterFunctions.put(
			"lastPostDate",
			dlFolderCacheModel -> dlFolderCacheModel.lastPostDate);
		attributeSetterBiConsumers.put(
			"lastPostDate",
			(BiConsumer<DLFolder, Date>)DLFolder::setLastPostDate);
		attributeGetterFunctions.put(
			"defaultFileEntryTypeId", DLFolder::getDefaultFileEntryTypeId);

		cacheModelGetterFunctions.put(
			"defaultFileEntryTypeId",
			dlFolderCacheModel -> dlFolderCacheModel.defaultFileEntryTypeId);
		attributeSetterBiConsumers.put(
			"defaultFileEntryTypeId",
			(BiConsumer<DLFolder, Long>)DLFolder::setDefaultFileEntryTypeId);
		attributeGetterFunctions.put("hidden", DLFolder::getHidden);

		cacheModelGetterFunctions.put(
			"hidden", dlFolderCacheModel -> dlFolderCacheModel.hidden);
		attributeSetterBiConsumers.put(
			"hidden", (BiConsumer<DLFolder, Boolean>)DLFolder::setHidden);
		attributeGetterFunctions.put(
			"restrictionType", DLFolder::getRestrictionType);

		cacheModelGetterFunctions.put(
			"restrictionType",
			dlFolderCacheModel -> dlFolderCacheModel.restrictionType);
		attributeSetterBiConsumers.put(
			"restrictionType",
			(BiConsumer<DLFolder, Integer>)DLFolder::setRestrictionType);
		attributeGetterFunctions.put(
			"lastPublishDate", DLFolder::getLastPublishDate);

		cacheModelGetterFunctions.put(
			"lastPublishDate",
			dlFolderCacheModel -> dlFolderCacheModel.lastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<DLFolder, Date>)DLFolder::setLastPublishDate);
		attributeGetterFunctions.put("status", DLFolder::getStatus);

		cacheModelGetterFunctions.put(
			"status", dlFolderCacheModel -> dlFolderCacheModel.status);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<DLFolder, Integer>)DLFolder::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", DLFolder::getStatusByUserId);

		cacheModelGetterFunctions.put(
			"statusByUserId",
			dlFolderCacheModel -> dlFolderCacheModel.statusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<DLFolder, Long>)DLFolder::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", DLFolder::getStatusByUserName);

		cacheModelGetterFunctions.put(
			"statusByUserName",
			dlFolderCacheModel -> dlFolderCacheModel.statusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<DLFolder, String>)DLFolder::setStatusByUserName);
		attributeGetterFunctions.put("statusDate", DLFolder::getStatusDate);

		cacheModelGetterFunctions.put(
			"statusDate", dlFolderCacheModel -> dlFolderCacheModel.statusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<DLFolder, Date>)DLFolder::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
		_cacheModelGetterFunctions = Collections.unmodifiableMap(
			cacheModelGetterFunctions);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_columnBitmask |= MVCCVERSION_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		_columnBitmask |= CTCOLLECTIONID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getCacheModelAttribute("uuid");
	}

	@JSON
	@Override
	public long getFolderId() {
		return _folderId;
	}

	@Override
	public void setFolderId(long folderId) {
		_columnBitmask |= FOLDERID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_folderId = folderId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalFolderId() {
		return getCacheModelAttribute("folderId");
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return getCacheModelAttribute("groupId");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return getCacheModelAttribute("companyId");
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_columnBitmask |= USERNAME_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask |= CREATEDATE_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask |= MODIFIEDDATE_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getRepositoryId() {
		return _repositoryId;
	}

	@Override
	public void setRepositoryId(long repositoryId) {
		_columnBitmask |= REPOSITORYID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_repositoryId = repositoryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalRepositoryId() {
		return getCacheModelAttribute("repositoryId");
	}

	@JSON
	@Override
	public boolean getMountPoint() {
		return _mountPoint;
	}

	@JSON
	@Override
	public boolean isMountPoint() {
		return _mountPoint;
	}

	@Override
	public void setMountPoint(boolean mountPoint) {
		_columnBitmask |= MOUNTPOINT_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_mountPoint = mountPoint;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public boolean getOriginalMountPoint() {
		return getCacheModelAttribute("mountPoint");
	}

	@JSON
	@Override
	public long getParentFolderId() {
		return _parentFolderId;
	}

	@Override
	public void setParentFolderId(long parentFolderId) {
		_columnBitmask |= PARENTFOLDERID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_parentFolderId = parentFolderId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalParentFolderId() {
		return getCacheModelAttribute("parentFolderId");
	}

	@JSON
	@Override
	public String getTreePath() {
		if (_treePath == null) {
			return "";
		}
		else {
			return _treePath;
		}
	}

	@Override
	public void setTreePath(String treePath) {
		_columnBitmask |= TREEPATH_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_treePath = treePath;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalTreePath() {
		return getCacheModelAttribute("treePath");
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getCacheModelAttribute("name");
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_columnBitmask |= DESCRIPTION_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_description = description;
	}

	@JSON
	@Override
	public Date getLastPostDate() {
		return _lastPostDate;
	}

	@Override
	public void setLastPostDate(Date lastPostDate) {
		_columnBitmask |= LASTPOSTDATE_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_lastPostDate = lastPostDate;
	}

	@JSON
	@Override
	public long getDefaultFileEntryTypeId() {
		return _defaultFileEntryTypeId;
	}

	@Override
	public void setDefaultFileEntryTypeId(long defaultFileEntryTypeId) {
		_columnBitmask |= DEFAULTFILEENTRYTYPEID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_defaultFileEntryTypeId = defaultFileEntryTypeId;
	}

	@JSON
	@Override
	public boolean getHidden() {
		return _hidden;
	}

	@JSON
	@Override
	public boolean isHidden() {
		return _hidden;
	}

	@Override
	public void setHidden(boolean hidden) {
		_columnBitmask |= HIDDEN_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_hidden = hidden;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public boolean getOriginalHidden() {
		return getCacheModelAttribute("hidden");
	}

	@JSON
	@Override
	public int getRestrictionType() {
		return _restrictionType;
	}

	@Override
	public void setRestrictionType(int restrictionType) {
		_columnBitmask |= RESTRICTIONTYPE_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_restrictionType = restrictionType;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_columnBitmask |= LASTPUBLISHDATE_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_lastPublishDate = lastPublishDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_status = status;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public int getOriginalStatus() {
		return getCacheModelAttribute("status");
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_columnBitmask |= STATUSBYUSERID_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_columnBitmask |= STATUSBYUSERNAME_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_columnBitmask |= STATUSDATE_COLUMN_BITMASK;

		if (!isNew() && (_dlFolderCacheModel == null)) {
			_dlFolderCacheModel = (DLFolderCacheModel)toCacheModel();
		}

		_statusDate = statusDate;
	}

	@Override
	public long getContainerModelId() {
		return getFolderId();
	}

	@Override
	public void setContainerModelId(long containerModelId) {
		_folderId = containerModelId;
	}

	@Override
	public long getParentContainerModelId() {
		return getParentFolderId();
	}

	@Override
	public void setParentContainerModelId(long parentContainerModelId) {
		_parentFolderId = parentContainerModelId;
	}

	@Override
	public String getContainerModelName() {
		return String.valueOf(getName());
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DLFolder.class.getName()));
	}

	@Override
	public com.liferay.trash.kernel.model.TrashEntry getTrashEntry()
		throws PortalException {

		if (!isInTrash()) {
			return null;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return trashEntry;
		}

		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if (Validator.isNotNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			ContainerModel containerModel = null;

			try {
				containerModel = trashHandler.getParentContainerModel(this);
			}
			catch (NoSuchModelException noSuchModelException) {
				return null;
			}

			while (containerModel != null) {
				if (containerModel instanceof TrashedModel) {
					TrashedModel trashedModel = (TrashedModel)containerModel;

					return trashedModel.getTrashEntry();
				}

				trashHandler =
					com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
						getTrashHandler(
							trashHandler.getContainerModelClassName(
								containerModel.getContainerModelId()));

				if (trashHandler == null) {
					return null;
				}

				containerModel = trashHandler.getContainerModel(
					containerModel.getParentContainerModelId());
			}
		}

		return null;
	}

	@Override
	public long getTrashEntryClassPK() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Judson (7.1.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public com.liferay.portal.kernel.trash.TrashHandler getTrashHandler() {
		return com.liferay.portal.kernel.trash.TrashHandlerRegistryUtil.
			getTrashHandler(getModelClassName());
	}

	@Override
	public boolean isInTrash() {
		if (getStatus() == WorkflowConstants.STATUS_IN_TRASH) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInTrashContainer() {
		com.liferay.portal.kernel.trash.TrashHandler trashHandler =
			getTrashHandler();

		if ((trashHandler == null) ||
			Validator.isNull(
				trashHandler.getContainerModelClassName(getPrimaryKey()))) {

			return false;
		}

		try {
			ContainerModel containerModel =
				trashHandler.getParentContainerModel(this);

			if (containerModel == null) {
				return false;
			}

			if (containerModel instanceof TrashedModel) {
				return ((TrashedModel)containerModel).isInTrash();
			}
		}
		catch (Exception exception) {
		}

		return false;
	}

	@Override
	public boolean isInTrashExplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return true;
		}

		return false;
	}

	@Override
	public boolean isInTrashImplicitly() {
		if (!isInTrash()) {
			return false;
		}

		com.liferay.trash.kernel.model.TrashEntry trashEntry =
			com.liferay.trash.kernel.service.TrashEntryLocalServiceUtil.
				fetchEntry(getModelClassName(), getTrashEntryClassPK());

		if (trashEntry != null) {
			return false;
		}

		return true;
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DLFolder.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DLFolder toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DLFolder>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DLFolderImpl dlFolderImpl = new DLFolderImpl();

		dlFolderImpl.setMvccVersion(getMvccVersion());
		dlFolderImpl.setCtCollectionId(getCtCollectionId());
		dlFolderImpl.setUuid(getUuid());
		dlFolderImpl.setFolderId(getFolderId());
		dlFolderImpl.setGroupId(getGroupId());
		dlFolderImpl.setCompanyId(getCompanyId());
		dlFolderImpl.setUserId(getUserId());
		dlFolderImpl.setUserName(getUserName());
		dlFolderImpl.setCreateDate(getCreateDate());
		dlFolderImpl.setModifiedDate(getModifiedDate());
		dlFolderImpl.setRepositoryId(getRepositoryId());
		dlFolderImpl.setMountPoint(isMountPoint());
		dlFolderImpl.setParentFolderId(getParentFolderId());
		dlFolderImpl.setTreePath(getTreePath());
		dlFolderImpl.setName(getName());
		dlFolderImpl.setDescription(getDescription());
		dlFolderImpl.setLastPostDate(getLastPostDate());
		dlFolderImpl.setDefaultFileEntryTypeId(getDefaultFileEntryTypeId());
		dlFolderImpl.setHidden(isHidden());
		dlFolderImpl.setRestrictionType(getRestrictionType());
		dlFolderImpl.setLastPublishDate(getLastPublishDate());
		dlFolderImpl.setStatus(getStatus());
		dlFolderImpl.setStatusByUserId(getStatusByUserId());
		dlFolderImpl.setStatusByUserName(getStatusByUserName());
		dlFolderImpl.setStatusDate(getStatusDate());

		dlFolderImpl.resetOriginalValues();

		return dlFolderImpl;
	}

	@Override
	public int compareTo(DLFolder dlFolder) {
		int value = 0;

		if (getParentFolderId() < dlFolder.getParentFolderId()) {
			value = -1;
		}
		else if (getParentFolderId() > dlFolder.getParentFolderId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		value = getName().compareToIgnoreCase(dlFolder.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DLFolder)) {
			return false;
		}

		DLFolder dlFolder = (DLFolder)object;

		long primaryKey = dlFolder.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;

		_columnBitmask = 0;

		_dlFolderCacheModel = null;
	}

	@Override
	public CacheModel<DLFolder> toCacheModel() {
		DLFolderCacheModel dlFolderCacheModel = new DLFolderCacheModel();

		dlFolderCacheModel.mvccVersion = getMvccVersion();

		dlFolderCacheModel.ctCollectionId = getCtCollectionId();

		dlFolderCacheModel.uuid = getUuid();

		String uuid = dlFolderCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dlFolderCacheModel.uuid = null;
		}

		dlFolderCacheModel.folderId = getFolderId();

		dlFolderCacheModel.groupId = getGroupId();

		dlFolderCacheModel.companyId = getCompanyId();

		dlFolderCacheModel.userId = getUserId();

		dlFolderCacheModel.userName = getUserName();

		String userName = dlFolderCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dlFolderCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dlFolderCacheModel.createDate = createDate.getTime();
		}
		else {
			dlFolderCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dlFolderCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dlFolderCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dlFolderCacheModel.repositoryId = getRepositoryId();

		dlFolderCacheModel.mountPoint = isMountPoint();

		dlFolderCacheModel.parentFolderId = getParentFolderId();

		dlFolderCacheModel.treePath = getTreePath();

		String treePath = dlFolderCacheModel.treePath;

		if ((treePath != null) && (treePath.length() == 0)) {
			dlFolderCacheModel.treePath = null;
		}

		dlFolderCacheModel.name = getName();

		String name = dlFolderCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			dlFolderCacheModel.name = null;
		}

		dlFolderCacheModel.description = getDescription();

		String description = dlFolderCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			dlFolderCacheModel.description = null;
		}

		Date lastPostDate = getLastPostDate();

		if (lastPostDate != null) {
			dlFolderCacheModel.lastPostDate = lastPostDate.getTime();
		}
		else {
			dlFolderCacheModel.lastPostDate = Long.MIN_VALUE;
		}

		dlFolderCacheModel.defaultFileEntryTypeId = getDefaultFileEntryTypeId();

		dlFolderCacheModel.hidden = isHidden();

		dlFolderCacheModel.restrictionType = getRestrictionType();

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			dlFolderCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			dlFolderCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		dlFolderCacheModel.status = getStatus();

		dlFolderCacheModel.statusByUserId = getStatusByUserId();

		dlFolderCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = dlFolderCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			dlFolderCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			dlFolderCacheModel.statusDate = statusDate.getTime();
		}
		else {
			dlFolderCacheModel.statusDate = Long.MIN_VALUE;
		}

		return dlFolderCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DLFolder, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DLFolder, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DLFolder, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DLFolder)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DLFolder, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DLFolder, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DLFolder, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DLFolder)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DLFolder>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _folderId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _repositoryId;
	private boolean _mountPoint;
	private long _parentFolderId;
	private String _treePath;
	private String _name;
	private String _description;
	private Date _lastPostDate;
	private long _defaultFileEntryTypeId;
	private boolean _hidden;
	private int _restrictionType;
	private Date _lastPublishDate;
	private int _status;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private long _columnBitmask;
	private DLFolder _escapedModel;
	private DLFolderCacheModel _dlFolderCacheModel;

}