/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.OrgLabor;
import com.liferay.portal.kernel.model.OrgLaborModel;
import com.liferay.portal.kernel.model.OrgLaborSoap;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the OrgLabor service. Represents a row in the &quot;OrgLabor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>OrgLaborModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OrgLaborImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OrgLaborImpl
 * @generated
 */
@JSON(strict = true)
public class OrgLaborModelImpl
	extends BaseModelImpl<OrgLabor> implements OrgLaborModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a org labor model instance should use the <code>OrgLabor</code> interface instead.
	 */
	public static final String TABLE_NAME = "OrgLabor";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"orgLaborId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"organizationId", Types.BIGINT},
		{"typeId", Types.BIGINT}, {"sunOpen", Types.INTEGER},
		{"sunClose", Types.INTEGER}, {"monOpen", Types.INTEGER},
		{"monClose", Types.INTEGER}, {"tueOpen", Types.INTEGER},
		{"tueClose", Types.INTEGER}, {"wedOpen", Types.INTEGER},
		{"wedClose", Types.INTEGER}, {"thuOpen", Types.INTEGER},
		{"thuClose", Types.INTEGER}, {"friOpen", Types.INTEGER},
		{"friClose", Types.INTEGER}, {"satOpen", Types.INTEGER},
		{"satClose", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("orgLaborId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("typeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sunOpen", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("sunClose", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("monOpen", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("monClose", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("tueOpen", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("tueClose", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("wedOpen", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("wedClose", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("thuOpen", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("thuClose", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("friOpen", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("friClose", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("satOpen", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("satClose", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OrgLabor (mvccVersion LONG default 0 not null,orgLaborId LONG not null primary key,companyId LONG,organizationId LONG,typeId LONG,sunOpen INTEGER,sunClose INTEGER,monOpen INTEGER,monClose INTEGER,tueOpen INTEGER,tueClose INTEGER,wedOpen INTEGER,wedClose INTEGER,thuOpen INTEGER,thuClose INTEGER,friOpen INTEGER,friClose INTEGER,satOpen INTEGER,satClose INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table OrgLabor";

	public static final String ORDER_BY_JPQL =
		" ORDER BY orgLabor.organizationId ASC, orgLabor.typeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OrgLabor.organizationId ASC, OrgLabor.typeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	public static final long MVCCVERSION_COLUMN_BITMASK = 1L;

	public static final long ORGLABORID_COLUMN_BITMASK = 2L;

	public static final long COMPANYID_COLUMN_BITMASK = 4L;

	public static final long ORGANIZATIONID_COLUMN_BITMASK = 8L;

	public static final long TYPEID_COLUMN_BITMASK = 16L;

	public static final long SUNOPEN_COLUMN_BITMASK = 32L;

	public static final long SUNCLOSE_COLUMN_BITMASK = 64L;

	public static final long MONOPEN_COLUMN_BITMASK = 128L;

	public static final long MONCLOSE_COLUMN_BITMASK = 256L;

	public static final long TUEOPEN_COLUMN_BITMASK = 512L;

	public static final long TUECLOSE_COLUMN_BITMASK = 1024L;

	public static final long WEDOPEN_COLUMN_BITMASK = 2048L;

	public static final long WEDCLOSE_COLUMN_BITMASK = 4096L;

	public static final long THUOPEN_COLUMN_BITMASK = 8192L;

	public static final long THUCLOSE_COLUMN_BITMASK = 16384L;

	public static final long FRIOPEN_COLUMN_BITMASK = 32768L;

	public static final long FRICLOSE_COLUMN_BITMASK = 65536L;

	public static final long SATOPEN_COLUMN_BITMASK = 131072L;

	public static final long SATCLOSE_COLUMN_BITMASK = 262144L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OrgLabor toModel(OrgLaborSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OrgLabor model = new OrgLaborImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setOrgLaborId(soapModel.getOrgLaborId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setTypeId(soapModel.getTypeId());
		model.setSunOpen(soapModel.getSunOpen());
		model.setSunClose(soapModel.getSunClose());
		model.setMonOpen(soapModel.getMonOpen());
		model.setMonClose(soapModel.getMonClose());
		model.setTueOpen(soapModel.getTueOpen());
		model.setTueClose(soapModel.getTueClose());
		model.setWedOpen(soapModel.getWedOpen());
		model.setWedClose(soapModel.getWedClose());
		model.setThuOpen(soapModel.getThuOpen());
		model.setThuClose(soapModel.getThuClose());
		model.setFriOpen(soapModel.getFriOpen());
		model.setFriClose(soapModel.getFriClose());
		model.setSatOpen(soapModel.getSatOpen());
		model.setSatClose(soapModel.getSatClose());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OrgLabor> toModels(OrgLaborSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OrgLabor> models = new ArrayList<OrgLabor>(soapModels.length);

		for (OrgLaborSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.portal.kernel.model.OrgLabor"));

	public OrgLaborModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _orgLaborId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setOrgLaborId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _orgLaborId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OrgLabor.class;
	}

	@Override
	public String getModelClassName() {
		return OrgLabor.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<OrgLabor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<OrgLabor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OrgLabor, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((OrgLabor)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<OrgLabor, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<OrgLabor, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(OrgLabor)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<OrgLabor, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<OrgLabor, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, OrgLabor>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			OrgLabor.class.getClassLoader(), OrgLabor.class,
			ModelWrapper.class);

		try {
			Constructor<OrgLabor> constructor =
				(Constructor<OrgLabor>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	public <T> T getOriginalAttributeValue(String attributeName) {
		if ((_orgLaborCacheModel == null) ||
			(_orgLaborCacheModel == _dummyOrgLaborCacheModel)) {

			return null;
		}

		Function<OrgLaborCacheModel, Object> function =
			_cacheModelGetterFunctions.get(attributeName);

		if (function == null) {
			return null;
		}

		return (T)function.apply(_orgLaborCacheModel);
	}

	private static final Map<String, Function<OrgLaborCacheModel, Object>>
		_cacheModelGetterFunctions;
	private static final Map<String, Function<OrgLabor, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<OrgLabor, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<OrgLabor, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<OrgLabor, Object>>();
		Map<String, BiConsumer<OrgLabor, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<OrgLabor, ?>>();
		Map<String, Function<OrgLaborCacheModel, Object>>
			cacheModelGetterFunctions =
				new LinkedHashMap
					<String, Function<OrgLaborCacheModel, Object>>();

		attributeGetterFunctions.put("mvccVersion", OrgLabor::getMvccVersion);

		cacheModelGetterFunctions.put(
			"mvccVersion",
			orgLaborCacheModel -> orgLaborCacheModel.mvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<OrgLabor, Long>)OrgLabor::setMvccVersion);
		attributeGetterFunctions.put("orgLaborId", OrgLabor::getOrgLaborId);

		cacheModelGetterFunctions.put(
			"orgLaborId", orgLaborCacheModel -> orgLaborCacheModel.orgLaborId);
		attributeSetterBiConsumers.put(
			"orgLaborId", (BiConsumer<OrgLabor, Long>)OrgLabor::setOrgLaborId);
		attributeGetterFunctions.put("companyId", OrgLabor::getCompanyId);

		cacheModelGetterFunctions.put(
			"companyId", orgLaborCacheModel -> orgLaborCacheModel.companyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<OrgLabor, Long>)OrgLabor::setCompanyId);
		attributeGetterFunctions.put(
			"organizationId", OrgLabor::getOrganizationId);

		cacheModelGetterFunctions.put(
			"organizationId",
			orgLaborCacheModel -> orgLaborCacheModel.organizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<OrgLabor, Long>)OrgLabor::setOrganizationId);
		attributeGetterFunctions.put("typeId", OrgLabor::getTypeId);

		cacheModelGetterFunctions.put(
			"typeId", orgLaborCacheModel -> orgLaborCacheModel.typeId);
		attributeSetterBiConsumers.put(
			"typeId", (BiConsumer<OrgLabor, Long>)OrgLabor::setTypeId);
		attributeGetterFunctions.put("sunOpen", OrgLabor::getSunOpen);

		cacheModelGetterFunctions.put(
			"sunOpen", orgLaborCacheModel -> orgLaborCacheModel.sunOpen);
		attributeSetterBiConsumers.put(
			"sunOpen", (BiConsumer<OrgLabor, Integer>)OrgLabor::setSunOpen);
		attributeGetterFunctions.put("sunClose", OrgLabor::getSunClose);

		cacheModelGetterFunctions.put(
			"sunClose", orgLaborCacheModel -> orgLaborCacheModel.sunClose);
		attributeSetterBiConsumers.put(
			"sunClose", (BiConsumer<OrgLabor, Integer>)OrgLabor::setSunClose);
		attributeGetterFunctions.put("monOpen", OrgLabor::getMonOpen);

		cacheModelGetterFunctions.put(
			"monOpen", orgLaborCacheModel -> orgLaborCacheModel.monOpen);
		attributeSetterBiConsumers.put(
			"monOpen", (BiConsumer<OrgLabor, Integer>)OrgLabor::setMonOpen);
		attributeGetterFunctions.put("monClose", OrgLabor::getMonClose);

		cacheModelGetterFunctions.put(
			"monClose", orgLaborCacheModel -> orgLaborCacheModel.monClose);
		attributeSetterBiConsumers.put(
			"monClose", (BiConsumer<OrgLabor, Integer>)OrgLabor::setMonClose);
		attributeGetterFunctions.put("tueOpen", OrgLabor::getTueOpen);

		cacheModelGetterFunctions.put(
			"tueOpen", orgLaborCacheModel -> orgLaborCacheModel.tueOpen);
		attributeSetterBiConsumers.put(
			"tueOpen", (BiConsumer<OrgLabor, Integer>)OrgLabor::setTueOpen);
		attributeGetterFunctions.put("tueClose", OrgLabor::getTueClose);

		cacheModelGetterFunctions.put(
			"tueClose", orgLaborCacheModel -> orgLaborCacheModel.tueClose);
		attributeSetterBiConsumers.put(
			"tueClose", (BiConsumer<OrgLabor, Integer>)OrgLabor::setTueClose);
		attributeGetterFunctions.put("wedOpen", OrgLabor::getWedOpen);

		cacheModelGetterFunctions.put(
			"wedOpen", orgLaborCacheModel -> orgLaborCacheModel.wedOpen);
		attributeSetterBiConsumers.put(
			"wedOpen", (BiConsumer<OrgLabor, Integer>)OrgLabor::setWedOpen);
		attributeGetterFunctions.put("wedClose", OrgLabor::getWedClose);

		cacheModelGetterFunctions.put(
			"wedClose", orgLaborCacheModel -> orgLaborCacheModel.wedClose);
		attributeSetterBiConsumers.put(
			"wedClose", (BiConsumer<OrgLabor, Integer>)OrgLabor::setWedClose);
		attributeGetterFunctions.put("thuOpen", OrgLabor::getThuOpen);

		cacheModelGetterFunctions.put(
			"thuOpen", orgLaborCacheModel -> orgLaborCacheModel.thuOpen);
		attributeSetterBiConsumers.put(
			"thuOpen", (BiConsumer<OrgLabor, Integer>)OrgLabor::setThuOpen);
		attributeGetterFunctions.put("thuClose", OrgLabor::getThuClose);

		cacheModelGetterFunctions.put(
			"thuClose", orgLaborCacheModel -> orgLaborCacheModel.thuClose);
		attributeSetterBiConsumers.put(
			"thuClose", (BiConsumer<OrgLabor, Integer>)OrgLabor::setThuClose);
		attributeGetterFunctions.put("friOpen", OrgLabor::getFriOpen);

		cacheModelGetterFunctions.put(
			"friOpen", orgLaborCacheModel -> orgLaborCacheModel.friOpen);
		attributeSetterBiConsumers.put(
			"friOpen", (BiConsumer<OrgLabor, Integer>)OrgLabor::setFriOpen);
		attributeGetterFunctions.put("friClose", OrgLabor::getFriClose);

		cacheModelGetterFunctions.put(
			"friClose", orgLaborCacheModel -> orgLaborCacheModel.friClose);
		attributeSetterBiConsumers.put(
			"friClose", (BiConsumer<OrgLabor, Integer>)OrgLabor::setFriClose);
		attributeGetterFunctions.put("satOpen", OrgLabor::getSatOpen);

		cacheModelGetterFunctions.put(
			"satOpen", orgLaborCacheModel -> orgLaborCacheModel.satOpen);
		attributeSetterBiConsumers.put(
			"satOpen", (BiConsumer<OrgLabor, Integer>)OrgLabor::setSatOpen);
		attributeGetterFunctions.put("satClose", OrgLabor::getSatClose);

		cacheModelGetterFunctions.put(
			"satClose", orgLaborCacheModel -> orgLaborCacheModel.satClose);
		attributeSetterBiConsumers.put(
			"satClose", (BiConsumer<OrgLabor, Integer>)OrgLabor::setSatClose);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
		_cacheModelGetterFunctions = Collections.unmodifiableMap(
			cacheModelGetterFunctions);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_columnBitmask |= MVCCVERSION_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getOrgLaborId() {
		return _orgLaborId;
	}

	@Override
	public void setOrgLaborId(long orgLaborId) {
		_columnBitmask |= ORGLABORID_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_orgLaborId = orgLaborId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_organizationId = organizationId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getOriginalAttributeValue(String)}
	 */
	@Deprecated
	public long getOriginalOrganizationId() {
		return getOriginalAttributeValue("organizationId");
	}

	@JSON
	@Override
	public long getTypeId() {
		return _typeId;
	}

	@Override
	public void setTypeId(long typeId) {
		_columnBitmask |= TYPEID_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_typeId = typeId;
	}

	@JSON
	@Override
	public int getSunOpen() {
		return _sunOpen;
	}

	@Override
	public void setSunOpen(int sunOpen) {
		_columnBitmask |= SUNOPEN_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_sunOpen = sunOpen;
	}

	@JSON
	@Override
	public int getSunClose() {
		return _sunClose;
	}

	@Override
	public void setSunClose(int sunClose) {
		_columnBitmask |= SUNCLOSE_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_sunClose = sunClose;
	}

	@JSON
	@Override
	public int getMonOpen() {
		return _monOpen;
	}

	@Override
	public void setMonOpen(int monOpen) {
		_columnBitmask |= MONOPEN_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_monOpen = monOpen;
	}

	@JSON
	@Override
	public int getMonClose() {
		return _monClose;
	}

	@Override
	public void setMonClose(int monClose) {
		_columnBitmask |= MONCLOSE_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_monClose = monClose;
	}

	@JSON
	@Override
	public int getTueOpen() {
		return _tueOpen;
	}

	@Override
	public void setTueOpen(int tueOpen) {
		_columnBitmask |= TUEOPEN_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_tueOpen = tueOpen;
	}

	@JSON
	@Override
	public int getTueClose() {
		return _tueClose;
	}

	@Override
	public void setTueClose(int tueClose) {
		_columnBitmask |= TUECLOSE_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_tueClose = tueClose;
	}

	@JSON
	@Override
	public int getWedOpen() {
		return _wedOpen;
	}

	@Override
	public void setWedOpen(int wedOpen) {
		_columnBitmask |= WEDOPEN_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_wedOpen = wedOpen;
	}

	@JSON
	@Override
	public int getWedClose() {
		return _wedClose;
	}

	@Override
	public void setWedClose(int wedClose) {
		_columnBitmask |= WEDCLOSE_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_wedClose = wedClose;
	}

	@JSON
	@Override
	public int getThuOpen() {
		return _thuOpen;
	}

	@Override
	public void setThuOpen(int thuOpen) {
		_columnBitmask |= THUOPEN_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_thuOpen = thuOpen;
	}

	@JSON
	@Override
	public int getThuClose() {
		return _thuClose;
	}

	@Override
	public void setThuClose(int thuClose) {
		_columnBitmask |= THUCLOSE_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_thuClose = thuClose;
	}

	@JSON
	@Override
	public int getFriOpen() {
		return _friOpen;
	}

	@Override
	public void setFriOpen(int friOpen) {
		_columnBitmask |= FRIOPEN_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_friOpen = friOpen;
	}

	@JSON
	@Override
	public int getFriClose() {
		return _friClose;
	}

	@Override
	public void setFriClose(int friClose) {
		_columnBitmask |= FRICLOSE_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_friClose = friClose;
	}

	@JSON
	@Override
	public int getSatOpen() {
		return _satOpen;
	}

	@Override
	public void setSatOpen(int satOpen) {
		_columnBitmask |= SATOPEN_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_satOpen = satOpen;
	}

	@JSON
	@Override
	public int getSatClose() {
		return _satClose;
	}

	@Override
	public void setSatClose(int satClose) {
		_columnBitmask |= SATCLOSE_COLUMN_BITMASK;

		if (_orgLaborCacheModel == _dummyOrgLaborCacheModel) {
			_orgLaborCacheModel = (OrgLaborCacheModel)toCacheModel();
		}

		_satClose = satClose;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), OrgLabor.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OrgLabor toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, OrgLabor>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OrgLaborImpl orgLaborImpl = new OrgLaborImpl();

		orgLaborImpl.setMvccVersion(getMvccVersion());
		orgLaborImpl.setOrgLaborId(getOrgLaborId());
		orgLaborImpl.setCompanyId(getCompanyId());
		orgLaborImpl.setOrganizationId(getOrganizationId());
		orgLaborImpl.setTypeId(getTypeId());
		orgLaborImpl.setSunOpen(getSunOpen());
		orgLaborImpl.setSunClose(getSunClose());
		orgLaborImpl.setMonOpen(getMonOpen());
		orgLaborImpl.setMonClose(getMonClose());
		orgLaborImpl.setTueOpen(getTueOpen());
		orgLaborImpl.setTueClose(getTueClose());
		orgLaborImpl.setWedOpen(getWedOpen());
		orgLaborImpl.setWedClose(getWedClose());
		orgLaborImpl.setThuOpen(getThuOpen());
		orgLaborImpl.setThuClose(getThuClose());
		orgLaborImpl.setFriOpen(getFriOpen());
		orgLaborImpl.setFriClose(getFriClose());
		orgLaborImpl.setSatOpen(getSatOpen());
		orgLaborImpl.setSatClose(getSatClose());

		orgLaborImpl.resetOriginalValues();

		return orgLaborImpl;
	}

	@Override
	public int compareTo(OrgLabor orgLabor) {
		int value = 0;

		if (getOrganizationId() < orgLabor.getOrganizationId()) {
			value = -1;
		}
		else if (getOrganizationId() > orgLabor.getOrganizationId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		if (getTypeId() < orgLabor.getTypeId()) {
			value = -1;
		}
		else if (getTypeId() > orgLabor.getTypeId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof OrgLabor)) {
			return false;
		}

		OrgLabor orgLabor = (OrgLabor)object;

		long primaryKey = orgLabor.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnBitmask = 0;

		_orgLaborCacheModel = _dummyOrgLaborCacheModel;
	}

	@Override
	public CacheModel<OrgLabor> toCacheModel() {
		OrgLaborCacheModel orgLaborCacheModel = new OrgLaborCacheModel();

		orgLaborCacheModel.mvccVersion = getMvccVersion();

		orgLaborCacheModel.orgLaborId = getOrgLaborId();

		orgLaborCacheModel.companyId = getCompanyId();

		orgLaborCacheModel.organizationId = getOrganizationId();

		orgLaborCacheModel.typeId = getTypeId();

		orgLaborCacheModel.sunOpen = getSunOpen();

		orgLaborCacheModel.sunClose = getSunClose();

		orgLaborCacheModel.monOpen = getMonOpen();

		orgLaborCacheModel.monClose = getMonClose();

		orgLaborCacheModel.tueOpen = getTueOpen();

		orgLaborCacheModel.tueClose = getTueClose();

		orgLaborCacheModel.wedOpen = getWedOpen();

		orgLaborCacheModel.wedClose = getWedClose();

		orgLaborCacheModel.thuOpen = getThuOpen();

		orgLaborCacheModel.thuClose = getThuClose();

		orgLaborCacheModel.friOpen = getFriOpen();

		orgLaborCacheModel.friClose = getFriClose();

		orgLaborCacheModel.satOpen = getSatOpen();

		orgLaborCacheModel.satClose = getSatClose();

		return orgLaborCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<OrgLabor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<OrgLabor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OrgLabor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((OrgLabor)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<OrgLabor, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<OrgLabor, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<OrgLabor, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((OrgLabor)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, OrgLabor>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _orgLaborId;
	private long _companyId;
	private long _organizationId;
	private long _typeId;
	private int _sunOpen;
	private int _sunClose;
	private int _monOpen;
	private int _monClose;
	private int _tueOpen;
	private int _tueClose;
	private int _wedOpen;
	private int _wedClose;
	private int _thuOpen;
	private int _thuClose;
	private int _friOpen;
	private int _friClose;
	private int _satOpen;
	private int _satClose;
	private long _columnBitmask;
	private OrgLabor _escapedModel;

	private static final OrgLaborCacheModel _dummyOrgLaborCacheModel =
		new OrgLaborCacheModel();

	private OrgLaborCacheModel _orgLaborCacheModel;

}