/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.SystemEvent;
import com.liferay.portal.kernel.model.SystemEventModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SystemEvent service. Represents a row in the &quot;SystemEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SystemEventModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SystemEventImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SystemEventImpl
 * @generated
 */
public class SystemEventModelImpl
	extends BaseModelImpl<SystemEvent> implements SystemEventModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a system event model instance should use the <code>SystemEvent</code> interface instead.
	 */
	public static final String TABLE_NAME = "SystemEvent";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"systemEventId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"classUuid", Types.VARCHAR}, {"referrerClassNameId", Types.BIGINT},
		{"parentSystemEventId", Types.BIGINT},
		{"systemEventSetKey", Types.BIGINT}, {"type_", Types.INTEGER},
		{"extraData", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("systemEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("referrerClassNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentSystemEventId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("systemEventSetKey", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("type_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("extraData", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SystemEvent (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,systemEventId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,classNameId LONG,classPK LONG,classUuid VARCHAR(75) null,referrerClassNameId LONG,parentSystemEventId LONG,systemEventSetKey LONG,type_ INTEGER,extraData TEXT null,primary key (systemEventId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table SystemEvent";

	public static final String ORDER_BY_JPQL =
		" ORDER BY systemEvent.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SystemEvent.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	public static final long MVCCVERSION_COLUMN_BITMASK = 1L;

	public static final long CTCOLLECTIONID_COLUMN_BITMASK = 2L;

	public static final long SYSTEMEVENTID_COLUMN_BITMASK = 4L;

	public static final long GROUPID_COLUMN_BITMASK = 8L;

	public static final long COMPANYID_COLUMN_BITMASK = 16L;

	public static final long USERID_COLUMN_BITMASK = 32L;

	public static final long USERNAME_COLUMN_BITMASK = 64L;

	public static final long CREATEDATE_COLUMN_BITMASK = 128L;

	public static final long CLASSNAMEID_COLUMN_BITMASK = 256L;

	public static final long CLASSPK_COLUMN_BITMASK = 512L;

	public static final long CLASSUUID_COLUMN_BITMASK = 1024L;

	public static final long REFERRERCLASSNAMEID_COLUMN_BITMASK = 2048L;

	public static final long PARENTSYSTEMEVENTID_COLUMN_BITMASK = 4096L;

	public static final long SYSTEMEVENTSETKEY_COLUMN_BITMASK = 8192L;

	public static final long TYPE_COLUMN_BITMASK = 16384L;

	public static final long EXTRADATA_COLUMN_BITMASK = 32768L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.util.PropsUtil.get(
			"lock.expiration.time.com.liferay.portal.kernel.model.SystemEvent"));

	public SystemEventModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _systemEventId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSystemEventId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _systemEventId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SystemEvent.class;
	}

	@Override
	public String getModelClassName() {
		return SystemEvent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SystemEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SystemEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SystemEvent, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((SystemEvent)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SystemEvent, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SystemEvent, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SystemEvent)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SystemEvent, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SystemEvent, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, SystemEvent>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			SystemEvent.class.getClassLoader(), SystemEvent.class,
			ModelWrapper.class);

		try {
			Constructor<SystemEvent> constructor =
				(Constructor<SystemEvent>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	public <T> T getAttribute(String attribute) {
		Function<SystemEvent, Object> function = _attributeGetterFunctions.get(
			attribute);

		if (function == null) {
			return null;
		}

		return (T)function.apply((SystemEvent)this);
	}

	public <T> T getCacheModelAttribute(String attribute) {
		Function<SystemEventCacheModel, Object> function =
			_cacheModelGetterFunctions.get(attribute);

		if (function == null) {
			return null;
		}

		if (_systemEventCacheModel == null) {
			return null;
		}

		return (T)function.apply(_systemEventCacheModel);
	}

	private static final Map<String, Function<SystemEvent, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<SystemEvent, Object>>
		_attributeSetterBiConsumers;
	private static final Map<String, Function<SystemEventCacheModel, Object>>
		_cacheModelGetterFunctions;

	static {
		Map<String, Function<SystemEvent, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<SystemEvent, Object>>();
		Map<String, BiConsumer<SystemEvent, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<SystemEvent, ?>>();
		Map<String, Function<SystemEventCacheModel, Object>>
			cacheModelGetterFunctions =
				new LinkedHashMap
					<String, Function<SystemEventCacheModel, Object>>();

		attributeGetterFunctions.put(
			"mvccVersion", SystemEvent::getMvccVersion);

		cacheModelGetterFunctions.put(
			"mvccVersion",
			systemEventCacheModel -> systemEventCacheModel.mvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<SystemEvent, Long>)SystemEvent::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", SystemEvent::getCtCollectionId);

		cacheModelGetterFunctions.put(
			"ctCollectionId",
			systemEventCacheModel -> systemEventCacheModel.ctCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<SystemEvent, Long>)SystemEvent::setCtCollectionId);
		attributeGetterFunctions.put(
			"systemEventId", SystemEvent::getSystemEventId);

		cacheModelGetterFunctions.put(
			"systemEventId",
			systemEventCacheModel -> systemEventCacheModel.systemEventId);
		attributeSetterBiConsumers.put(
			"systemEventId",
			(BiConsumer<SystemEvent, Long>)SystemEvent::setSystemEventId);
		attributeGetterFunctions.put("groupId", SystemEvent::getGroupId);

		cacheModelGetterFunctions.put(
			"groupId", systemEventCacheModel -> systemEventCacheModel.groupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<SystemEvent, Long>)SystemEvent::setGroupId);
		attributeGetterFunctions.put("companyId", SystemEvent::getCompanyId);

		cacheModelGetterFunctions.put(
			"companyId",
			systemEventCacheModel -> systemEventCacheModel.companyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<SystemEvent, Long>)SystemEvent::setCompanyId);
		attributeGetterFunctions.put("userId", SystemEvent::getUserId);

		cacheModelGetterFunctions.put(
			"userId", systemEventCacheModel -> systemEventCacheModel.userId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<SystemEvent, Long>)SystemEvent::setUserId);
		attributeGetterFunctions.put("userName", SystemEvent::getUserName);

		cacheModelGetterFunctions.put(
			"userName",
			systemEventCacheModel -> systemEventCacheModel.userName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<SystemEvent, String>)SystemEvent::setUserName);
		attributeGetterFunctions.put("createDate", SystemEvent::getCreateDate);

		cacheModelGetterFunctions.put(
			"createDate",
			systemEventCacheModel -> systemEventCacheModel.createDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<SystemEvent, Date>)SystemEvent::setCreateDate);
		attributeGetterFunctions.put(
			"classNameId", SystemEvent::getClassNameId);

		cacheModelGetterFunctions.put(
			"classNameId",
			systemEventCacheModel -> systemEventCacheModel.classNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<SystemEvent, Long>)SystemEvent::setClassNameId);
		attributeGetterFunctions.put("classPK", SystemEvent::getClassPK);

		cacheModelGetterFunctions.put(
			"classPK", systemEventCacheModel -> systemEventCacheModel.classPK);
		attributeSetterBiConsumers.put(
			"classPK", (BiConsumer<SystemEvent, Long>)SystemEvent::setClassPK);
		attributeGetterFunctions.put("classUuid", SystemEvent::getClassUuid);

		cacheModelGetterFunctions.put(
			"classUuid",
			systemEventCacheModel -> systemEventCacheModel.classUuid);
		attributeSetterBiConsumers.put(
			"classUuid",
			(BiConsumer<SystemEvent, String>)SystemEvent::setClassUuid);
		attributeGetterFunctions.put(
			"referrerClassNameId", SystemEvent::getReferrerClassNameId);

		cacheModelGetterFunctions.put(
			"referrerClassNameId",
			systemEventCacheModel -> systemEventCacheModel.referrerClassNameId);
		attributeSetterBiConsumers.put(
			"referrerClassNameId",
			(BiConsumer<SystemEvent, Long>)SystemEvent::setReferrerClassNameId);
		attributeGetterFunctions.put(
			"parentSystemEventId", SystemEvent::getParentSystemEventId);

		cacheModelGetterFunctions.put(
			"parentSystemEventId",
			systemEventCacheModel -> systemEventCacheModel.parentSystemEventId);
		attributeSetterBiConsumers.put(
			"parentSystemEventId",
			(BiConsumer<SystemEvent, Long>)SystemEvent::setParentSystemEventId);
		attributeGetterFunctions.put(
			"systemEventSetKey", SystemEvent::getSystemEventSetKey);

		cacheModelGetterFunctions.put(
			"systemEventSetKey",
			systemEventCacheModel -> systemEventCacheModel.systemEventSetKey);
		attributeSetterBiConsumers.put(
			"systemEventSetKey",
			(BiConsumer<SystemEvent, Long>)SystemEvent::setSystemEventSetKey);
		attributeGetterFunctions.put("type", SystemEvent::getType);

		cacheModelGetterFunctions.put(
			"type", systemEventCacheModel -> systemEventCacheModel.type);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<SystemEvent, Integer>)SystemEvent::setType);
		attributeGetterFunctions.put("extraData", SystemEvent::getExtraData);

		cacheModelGetterFunctions.put(
			"extraData",
			systemEventCacheModel -> systemEventCacheModel.extraData);
		attributeSetterBiConsumers.put(
			"extraData",
			(BiConsumer<SystemEvent, String>)SystemEvent::setExtraData);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
		_cacheModelGetterFunctions = Collections.unmodifiableMap(
			cacheModelGetterFunctions);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_columnBitmask |= MVCCVERSION_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		_columnBitmask |= CTCOLLECTIONID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public long getSystemEventId() {
		return _systemEventId;
	}

	@Override
	public void setSystemEventId(long systemEventId) {
		_columnBitmask |= SYSTEMEVENTID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_systemEventId = systemEventId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return getCacheModelAttribute("groupId");
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_columnBitmask |= USERNAME_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask |= CREATEDATE_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_createDate = createDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return getCacheModelAttribute("classNameId");
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return getCacheModelAttribute("classPK");
	}

	@Override
	public String getClassUuid() {
		if (_classUuid == null) {
			return "";
		}
		else {
			return _classUuid;
		}
	}

	@Override
	public void setClassUuid(String classUuid) {
		_columnBitmask |= CLASSUUID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_classUuid = classUuid;
	}

	@Override
	public long getReferrerClassNameId() {
		return _referrerClassNameId;
	}

	@Override
	public void setReferrerClassNameId(long referrerClassNameId) {
		_columnBitmask |= REFERRERCLASSNAMEID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_referrerClassNameId = referrerClassNameId;
	}

	@Override
	public long getParentSystemEventId() {
		return _parentSystemEventId;
	}

	@Override
	public void setParentSystemEventId(long parentSystemEventId) {
		_columnBitmask |= PARENTSYSTEMEVENTID_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_parentSystemEventId = parentSystemEventId;
	}

	@Override
	public long getSystemEventSetKey() {
		return _systemEventSetKey;
	}

	@Override
	public void setSystemEventSetKey(long systemEventSetKey) {
		_columnBitmask |= SYSTEMEVENTSETKEY_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_systemEventSetKey = systemEventSetKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalSystemEventSetKey() {
		return getCacheModelAttribute("systemEventSetKey");
	}

	@Override
	public int getType() {
		return _type;
	}

	@Override
	public void setType(int type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public int getOriginalType() {
		return getCacheModelAttribute("type");
	}

	@Override
	public String getExtraData() {
		if (_extraData == null) {
			return "";
		}
		else {
			return _extraData;
		}
	}

	@Override
	public void setExtraData(String extraData) {
		_columnBitmask |= EXTRADATA_COLUMN_BITMASK;

		if (!isNew() && (_systemEventCacheModel == null)) {
			_systemEventCacheModel = (SystemEventCacheModel)toCacheModel();
		}

		_extraData = extraData;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SystemEvent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SystemEvent toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SystemEvent>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SystemEventImpl systemEventImpl = new SystemEventImpl();

		systemEventImpl.setMvccVersion(getMvccVersion());
		systemEventImpl.setCtCollectionId(getCtCollectionId());
		systemEventImpl.setSystemEventId(getSystemEventId());
		systemEventImpl.setGroupId(getGroupId());
		systemEventImpl.setCompanyId(getCompanyId());
		systemEventImpl.setUserId(getUserId());
		systemEventImpl.setUserName(getUserName());
		systemEventImpl.setCreateDate(getCreateDate());
		systemEventImpl.setClassNameId(getClassNameId());
		systemEventImpl.setClassPK(getClassPK());
		systemEventImpl.setClassUuid(getClassUuid());
		systemEventImpl.setReferrerClassNameId(getReferrerClassNameId());
		systemEventImpl.setParentSystemEventId(getParentSystemEventId());
		systemEventImpl.setSystemEventSetKey(getSystemEventSetKey());
		systemEventImpl.setType(getType());
		systemEventImpl.setExtraData(getExtraData());

		systemEventImpl.resetOriginalValues();

		return systemEventImpl;
	}

	@Override
	public int compareTo(SystemEvent systemEvent) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), systemEvent.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SystemEvent)) {
			return false;
		}

		SystemEvent systemEvent = (SystemEvent)object;

		long primaryKey = systemEvent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnBitmask = 0;

		_systemEventCacheModel = null;
	}

	@Override
	public CacheModel<SystemEvent> toCacheModel() {
		SystemEventCacheModel systemEventCacheModel =
			new SystemEventCacheModel();

		systemEventCacheModel.mvccVersion = getMvccVersion();

		systemEventCacheModel.ctCollectionId = getCtCollectionId();

		systemEventCacheModel.systemEventId = getSystemEventId();

		systemEventCacheModel.groupId = getGroupId();

		systemEventCacheModel.companyId = getCompanyId();

		systemEventCacheModel.userId = getUserId();

		systemEventCacheModel.userName = getUserName();

		String userName = systemEventCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			systemEventCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			systemEventCacheModel.createDate = createDate.getTime();
		}
		else {
			systemEventCacheModel.createDate = Long.MIN_VALUE;
		}

		systemEventCacheModel.classNameId = getClassNameId();

		systemEventCacheModel.classPK = getClassPK();

		systemEventCacheModel.classUuid = getClassUuid();

		String classUuid = systemEventCacheModel.classUuid;

		if ((classUuid != null) && (classUuid.length() == 0)) {
			systemEventCacheModel.classUuid = null;
		}

		systemEventCacheModel.referrerClassNameId = getReferrerClassNameId();

		systemEventCacheModel.parentSystemEventId = getParentSystemEventId();

		systemEventCacheModel.systemEventSetKey = getSystemEventSetKey();

		systemEventCacheModel.type = getType();

		systemEventCacheModel.extraData = getExtraData();

		String extraData = systemEventCacheModel.extraData;

		if ((extraData != null) && (extraData.length() == 0)) {
			systemEventCacheModel.extraData = null;
		}

		return systemEventCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SystemEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SystemEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SystemEvent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((SystemEvent)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<SystemEvent, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<SystemEvent, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SystemEvent, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((SystemEvent)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SystemEvent>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private long _systemEventId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private long _classNameId;
	private long _classPK;
	private String _classUuid;
	private long _referrerClassNameId;
	private long _parentSystemEventId;
	private long _systemEventSetKey;
	private int _type;
	private String _extraData;
	private long _columnBitmask;
	private SystemEvent _escapedModel;
	private SystemEventCacheModel _systemEventCacheModel;

}