/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.DSLQueryLinkEntry;
import com.liferay.portal.tools.service.builder.test.service.DSLQueryLinkEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.persistence.DSLQueryLinkEntryPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dsl query link entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.DSLQueryLinkEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.DSLQueryLinkEntryLocalServiceImpl
 * @generated
 */
public abstract class DSLQueryLinkEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements DSLQueryLinkEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>DSLQueryLinkEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.tools.service.builder.test.service.DSLQueryLinkEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the dsl query link entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DSLQueryLinkEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dslQueryLinkEntry the dsl query link entry
	 * @return the dsl query link entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DSLQueryLinkEntry addDSLQueryLinkEntry(
		DSLQueryLinkEntry dslQueryLinkEntry) {

		dslQueryLinkEntry.setNew(true);

		return dslQueryLinkEntryPersistence.update(dslQueryLinkEntry);
	}

	/**
	 * Creates a new dsl query link entry with the primary key. Does not add the dsl query link entry to the database.
	 *
	 * @param dslQueryLinkEntryId the primary key for the new dsl query link entry
	 * @return the new dsl query link entry
	 */
	@Override
	@Transactional(enabled = false)
	public DSLQueryLinkEntry createDSLQueryLinkEntry(long dslQueryLinkEntryId) {
		return dslQueryLinkEntryPersistence.create(dslQueryLinkEntryId);
	}

	/**
	 * Deletes the dsl query link entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DSLQueryLinkEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dslQueryLinkEntryId the primary key of the dsl query link entry
	 * @return the dsl query link entry that was removed
	 * @throws PortalException if a dsl query link entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DSLQueryLinkEntry deleteDSLQueryLinkEntry(long dslQueryLinkEntryId)
		throws PortalException {

		return dslQueryLinkEntryPersistence.remove(dslQueryLinkEntryId);
	}

	/**
	 * Deletes the dsl query link entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DSLQueryLinkEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dslQueryLinkEntry the dsl query link entry
	 * @return the dsl query link entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public DSLQueryLinkEntry deleteDSLQueryLinkEntry(
		DSLQueryLinkEntry dslQueryLinkEntry) {

		return dslQueryLinkEntryPersistence.remove(dslQueryLinkEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return dslQueryLinkEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			DSLQueryLinkEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dslQueryLinkEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DSLQueryLinkEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return dslQueryLinkEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DSLQueryLinkEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return dslQueryLinkEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dslQueryLinkEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return dslQueryLinkEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public DSLQueryLinkEntry fetchDSLQueryLinkEntry(long dslQueryLinkEntryId) {
		return dslQueryLinkEntryPersistence.fetchByPrimaryKey(
			dslQueryLinkEntryId);
	}

	/**
	 * Returns the dsl query link entry with the primary key.
	 *
	 * @param dslQueryLinkEntryId the primary key of the dsl query link entry
	 * @return the dsl query link entry
	 * @throws PortalException if a dsl query link entry with the primary key could not be found
	 */
	@Override
	public DSLQueryLinkEntry getDSLQueryLinkEntry(long dslQueryLinkEntryId)
		throws PortalException {

		return dslQueryLinkEntryPersistence.findByPrimaryKey(
			dslQueryLinkEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			dslQueryLinkEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DSLQueryLinkEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dslQueryLinkEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			dslQueryLinkEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(DSLQueryLinkEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"dslQueryLinkEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			dslQueryLinkEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(DSLQueryLinkEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dslQueryLinkEntryId");
	}

	/**
	 * @throws PortalException
	 */
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dslQueryLinkEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return dslQueryLinkEntryLocalService.deleteDSLQueryLinkEntry(
			(DSLQueryLinkEntry)persistedModel);
	}

	public BasePersistence<DSLQueryLinkEntry> getBasePersistence() {
		return dslQueryLinkEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return dslQueryLinkEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the dsl query link entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.DSLQueryLinkEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of dsl query link entries
	 * @param end the upper bound of the range of dsl query link entries (not inclusive)
	 * @return the range of dsl query link entries
	 */
	@Override
	public List<DSLQueryLinkEntry> getDSLQueryLinkEntries(int start, int end) {
		return dslQueryLinkEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dsl query link entries.
	 *
	 * @return the number of dsl query link entries
	 */
	@Override
	public int getDSLQueryLinkEntriesCount() {
		return dslQueryLinkEntryPersistence.countAll();
	}

	/**
	 * Updates the dsl query link entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect DSLQueryLinkEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param dslQueryLinkEntry the dsl query link entry
	 * @return the dsl query link entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public DSLQueryLinkEntry updateDSLQueryLinkEntry(
		DSLQueryLinkEntry dslQueryLinkEntry) {

		return dslQueryLinkEntryPersistence.update(dslQueryLinkEntry);
	}

	/**
	 * Returns the dsl query link entry local service.
	 *
	 * @return the dsl query link entry local service
	 */
	public DSLQueryLinkEntryLocalService getDSLQueryLinkEntryLocalService() {
		return dslQueryLinkEntryLocalService;
	}

	/**
	 * Sets the dsl query link entry local service.
	 *
	 * @param dslQueryLinkEntryLocalService the dsl query link entry local service
	 */
	public void setDSLQueryLinkEntryLocalService(
		DSLQueryLinkEntryLocalService dslQueryLinkEntryLocalService) {

		this.dslQueryLinkEntryLocalService = dslQueryLinkEntryLocalService;
	}

	/**
	 * Returns the dsl query link entry persistence.
	 *
	 * @return the dsl query link entry persistence
	 */
	public DSLQueryLinkEntryPersistence getDSLQueryLinkEntryPersistence() {
		return dslQueryLinkEntryPersistence;
	}

	/**
	 * Sets the dsl query link entry persistence.
	 *
	 * @param dslQueryLinkEntryPersistence the dsl query link entry persistence
	 */
	public void setDSLQueryLinkEntryPersistence(
		DSLQueryLinkEntryPersistence dslQueryLinkEntryPersistence) {

		this.dslQueryLinkEntryPersistence = dslQueryLinkEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.tools.service.builder.test.model.DSLQueryLinkEntry",
			dslQueryLinkEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.tools.service.builder.test.model.DSLQueryLinkEntry");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DSLQueryLinkEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return DSLQueryLinkEntry.class;
	}

	protected String getModelClassName() {
		return DSLQueryLinkEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				dslQueryLinkEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = DSLQueryLinkEntryLocalService.class)
	protected DSLQueryLinkEntryLocalService dslQueryLinkEntryLocalService;

	@BeanReference(type = DSLQueryLinkEntryPersistence.class)
	protected DSLQueryLinkEntryPersistence dslQueryLinkEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}