/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.EagerFinderCacheEntry;
import com.liferay.portal.tools.service.builder.test.service.EagerFinderCacheEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.EagerFinderCacheEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.EagerFinderCacheEntryPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the eager finder cache entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.EagerFinderCacheEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.EagerFinderCacheEntryLocalServiceImpl
 * @generated
 */
public abstract class EagerFinderCacheEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements EagerFinderCacheEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>EagerFinderCacheEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>EagerFinderCacheEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the eager finder cache entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EagerFinderCacheEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eagerFinderCacheEntry the eager finder cache entry
	 * @return the eager finder cache entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EagerFinderCacheEntry addEagerFinderCacheEntry(
		EagerFinderCacheEntry eagerFinderCacheEntry) {

		eagerFinderCacheEntry.setNew(true);

		return eagerFinderCacheEntryPersistence.update(eagerFinderCacheEntry);
	}

	/**
	 * Creates a new eager finder cache entry with the primary key. Does not add the eager finder cache entry to the database.
	 *
	 * @param eagerFinderCacheEntryId the primary key for the new eager finder cache entry
	 * @return the new eager finder cache entry
	 */
	@Override
	@Transactional(enabled = false)
	public EagerFinderCacheEntry createEagerFinderCacheEntry(
		long eagerFinderCacheEntryId) {

		return eagerFinderCacheEntryPersistence.create(eagerFinderCacheEntryId);
	}

	/**
	 * Deletes the eager finder cache entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EagerFinderCacheEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eagerFinderCacheEntryId the primary key of the eager finder cache entry
	 * @return the eager finder cache entry that was removed
	 * @throws PortalException if a eager finder cache entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EagerFinderCacheEntry deleteEagerFinderCacheEntry(
			long eagerFinderCacheEntryId)
		throws PortalException {

		return eagerFinderCacheEntryPersistence.remove(eagerFinderCacheEntryId);
	}

	/**
	 * Deletes the eager finder cache entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EagerFinderCacheEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eagerFinderCacheEntry the eager finder cache entry
	 * @return the eager finder cache entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EagerFinderCacheEntry deleteEagerFinderCacheEntry(
		EagerFinderCacheEntry eagerFinderCacheEntry) {

		return eagerFinderCacheEntryPersistence.remove(eagerFinderCacheEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return eagerFinderCacheEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			EagerFinderCacheEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return eagerFinderCacheEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerFinderCacheEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return eagerFinderCacheEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerFinderCacheEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return eagerFinderCacheEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return eagerFinderCacheEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return eagerFinderCacheEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public EagerFinderCacheEntry fetchEagerFinderCacheEntry(
		long eagerFinderCacheEntryId) {

		return eagerFinderCacheEntryPersistence.fetchByPrimaryKey(
			eagerFinderCacheEntryId);
	}

	/**
	 * Returns the eager finder cache entry with the primary key.
	 *
	 * @param eagerFinderCacheEntryId the primary key of the eager finder cache entry
	 * @return the eager finder cache entry
	 * @throws PortalException if a eager finder cache entry with the primary key could not be found
	 */
	@Override
	public EagerFinderCacheEntry getEagerFinderCacheEntry(
			long eagerFinderCacheEntryId)
		throws PortalException {

		return eagerFinderCacheEntryPersistence.findByPrimaryKey(
			eagerFinderCacheEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			eagerFinderCacheEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EagerFinderCacheEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"eagerFinderCacheEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			eagerFinderCacheEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			EagerFinderCacheEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"eagerFinderCacheEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			eagerFinderCacheEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EagerFinderCacheEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"eagerFinderCacheEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return eagerFinderCacheEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return eagerFinderCacheEntryLocalService.deleteEagerFinderCacheEntry(
			(EagerFinderCacheEntry)persistedModel);
	}

	@Override
	public BasePersistence<EagerFinderCacheEntry> getBasePersistence() {
		return eagerFinderCacheEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return eagerFinderCacheEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the eager finder cache entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerFinderCacheEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of eager finder cache entries
	 * @param end the upper bound of the range of eager finder cache entries (not inclusive)
	 * @return the range of eager finder cache entries
	 */
	@Override
	public List<EagerFinderCacheEntry> getEagerFinderCacheEntries(
		int start, int end) {

		return eagerFinderCacheEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of eager finder cache entries.
	 *
	 * @return the number of eager finder cache entries
	 */
	@Override
	public int getEagerFinderCacheEntriesCount() {
		return eagerFinderCacheEntryPersistence.countAll();
	}

	/**
	 * Updates the eager finder cache entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect EagerFinderCacheEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param eagerFinderCacheEntry the eager finder cache entry
	 * @return the eager finder cache entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EagerFinderCacheEntry updateEagerFinderCacheEntry(
		EagerFinderCacheEntry eagerFinderCacheEntry) {

		return eagerFinderCacheEntryPersistence.update(eagerFinderCacheEntry);
	}

	/**
	 * Returns the eager finder cache entry local service.
	 *
	 * @return the eager finder cache entry local service
	 */
	public EagerFinderCacheEntryLocalService
		getEagerFinderCacheEntryLocalService() {

		return eagerFinderCacheEntryLocalService;
	}

	/**
	 * Sets the eager finder cache entry local service.
	 *
	 * @param eagerFinderCacheEntryLocalService the eager finder cache entry local service
	 */
	public void setEagerFinderCacheEntryLocalService(
		EagerFinderCacheEntryLocalService eagerFinderCacheEntryLocalService) {

		this.eagerFinderCacheEntryLocalService =
			eagerFinderCacheEntryLocalService;
	}

	/**
	 * Returns the eager finder cache entry persistence.
	 *
	 * @return the eager finder cache entry persistence
	 */
	public EagerFinderCacheEntryPersistence
		getEagerFinderCacheEntryPersistence() {

		return eagerFinderCacheEntryPersistence;
	}

	/**
	 * Sets the eager finder cache entry persistence.
	 *
	 * @param eagerFinderCacheEntryPersistence the eager finder cache entry persistence
	 */
	public void setEagerFinderCacheEntryPersistence(
		EagerFinderCacheEntryPersistence eagerFinderCacheEntryPersistence) {

		this.eagerFinderCacheEntryPersistence =
			eagerFinderCacheEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.tools.service.builder.test.model.EagerFinderCacheEntry",
			eagerFinderCacheEntryLocalService);

		_setLocalServiceUtilService(eagerFinderCacheEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.tools.service.builder.test.model.EagerFinderCacheEntry");

		_setLocalServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EagerFinderCacheEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EagerFinderCacheEntry.class;
	}

	protected String getModelClassName() {
		return EagerFinderCacheEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				eagerFinderCacheEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		EagerFinderCacheEntryLocalService eagerFinderCacheEntryLocalService) {

		try {
			Field field =
				EagerFinderCacheEntryLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, eagerFinderCacheEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(type = EagerFinderCacheEntryLocalService.class)
	protected EagerFinderCacheEntryLocalService
		eagerFinderCacheEntryLocalService;

	@BeanReference(type = EagerFinderCacheEntryPersistence.class)
	protected EagerFinderCacheEntryPersistence eagerFinderCacheEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}