/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.FinderPath;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.LoadFinderCacheEntry;
import com.liferay.portal.tools.service.builder.test.service.LoadFinderCacheEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.LoadFinderCacheEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.LoadFinderCacheEntryPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the load finder cache entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.LoadFinderCacheEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.LoadFinderCacheEntryLocalServiceImpl
 * @generated
 */
public abstract class LoadFinderCacheEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, LoadFinderCacheEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>LoadFinderCacheEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>LoadFinderCacheEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the load finder cache entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoadFinderCacheEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loadFinderCacheEntry the load finder cache entry
	 * @return the load finder cache entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LoadFinderCacheEntry addLoadFinderCacheEntry(
		LoadFinderCacheEntry loadFinderCacheEntry) {

		loadFinderCacheEntry.setNew(true);

		return loadFinderCacheEntryPersistence.update(loadFinderCacheEntry);
	}

	/**
	 * Creates a new load finder cache entry with the primary key. Does not add the load finder cache entry to the database.
	 *
	 * @param loadFinderCacheEntryId the primary key for the new load finder cache entry
	 * @return the new load finder cache entry
	 */
	@Override
	@Transactional(enabled = false)
	public LoadFinderCacheEntry createLoadFinderCacheEntry(
		long loadFinderCacheEntryId) {

		return loadFinderCacheEntryPersistence.create(loadFinderCacheEntryId);
	}

	/**
	 * Deletes the load finder cache entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoadFinderCacheEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loadFinderCacheEntryId the primary key of the load finder cache entry
	 * @return the load finder cache entry that was removed
	 * @throws PortalException if a load finder cache entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LoadFinderCacheEntry deleteLoadFinderCacheEntry(
			long loadFinderCacheEntryId)
		throws PortalException {

		return loadFinderCacheEntryPersistence.remove(loadFinderCacheEntryId);
	}

	/**
	 * Deletes the load finder cache entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoadFinderCacheEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loadFinderCacheEntry the load finder cache entry
	 * @return the load finder cache entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public LoadFinderCacheEntry deleteLoadFinderCacheEntry(
		LoadFinderCacheEntry loadFinderCacheEntry) {

		return loadFinderCacheEntryPersistence.remove(loadFinderCacheEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return loadFinderCacheEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			LoadFinderCacheEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return loadFinderCacheEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.LoadFinderCacheEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return loadFinderCacheEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.LoadFinderCacheEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return loadFinderCacheEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return loadFinderCacheEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return loadFinderCacheEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public LoadFinderCacheEntry fetchLoadFinderCacheEntry(
		long loadFinderCacheEntryId) {

		return loadFinderCacheEntryPersistence.fetchByPrimaryKey(
			loadFinderCacheEntryId);
	}

	/**
	 * Returns the load finder cache entry with the primary key.
	 *
	 * @param loadFinderCacheEntryId the primary key of the load finder cache entry
	 * @return the load finder cache entry
	 * @throws PortalException if a load finder cache entry with the primary key could not be found
	 */
	@Override
	public LoadFinderCacheEntry getLoadFinderCacheEntry(
			long loadFinderCacheEntryId)
		throws PortalException {

		return loadFinderCacheEntryPersistence.findByPrimaryKey(
			loadFinderCacheEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			loadFinderCacheEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LoadFinderCacheEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"loadFinderCacheEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			loadFinderCacheEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			LoadFinderCacheEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"loadFinderCacheEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			loadFinderCacheEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(LoadFinderCacheEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"loadFinderCacheEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return loadFinderCacheEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement LoadFinderCacheEntryLocalServiceImpl#deleteLoadFinderCacheEntry(LoadFinderCacheEntry) to avoid orphaned data");
		}

		return loadFinderCacheEntryLocalService.deleteLoadFinderCacheEntry(
			(LoadFinderCacheEntry)persistedModel);
	}

	@Override
	public BasePersistence<LoadFinderCacheEntry> getBasePersistence() {
		return loadFinderCacheEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return loadFinderCacheEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the load finder cache entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.LoadFinderCacheEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of load finder cache entries
	 * @param end the upper bound of the range of load finder cache entries (not inclusive)
	 * @return the range of load finder cache entries
	 */
	@Override
	public List<LoadFinderCacheEntry> getLoadFinderCacheEntries(
		int start, int end) {

		return loadFinderCacheEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of load finder cache entries.
	 *
	 * @return the number of load finder cache entries
	 */
	@Override
	public int getLoadFinderCacheEntriesCount() {
		return loadFinderCacheEntryPersistence.countAll();
	}

	@Override
	public void loadFinderCache(FinderPath[] finderPaths) {
		loadFinderCacheEntryPersistence.loadFinderCache(finderPaths);
	}

	/**
	 * Updates the load finder cache entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect LoadFinderCacheEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param loadFinderCacheEntry the load finder cache entry
	 * @return the load finder cache entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public LoadFinderCacheEntry updateLoadFinderCacheEntry(
		LoadFinderCacheEntry loadFinderCacheEntry) {

		return loadFinderCacheEntryPersistence.update(loadFinderCacheEntry);
	}

	/**
	 * Returns the load finder cache entry local service.
	 *
	 * @return the load finder cache entry local service
	 */
	public LoadFinderCacheEntryLocalService
		getLoadFinderCacheEntryLocalService() {

		return loadFinderCacheEntryLocalService;
	}

	/**
	 * Sets the load finder cache entry local service.
	 *
	 * @param loadFinderCacheEntryLocalService the load finder cache entry local service
	 */
	public void setLoadFinderCacheEntryLocalService(
		LoadFinderCacheEntryLocalService loadFinderCacheEntryLocalService) {

		this.loadFinderCacheEntryLocalService =
			loadFinderCacheEntryLocalService;
	}

	/**
	 * Returns the load finder cache entry persistence.
	 *
	 * @return the load finder cache entry persistence
	 */
	public LoadFinderCacheEntryPersistence
		getLoadFinderCacheEntryPersistence() {

		return loadFinderCacheEntryPersistence;
	}

	/**
	 * Sets the load finder cache entry persistence.
	 *
	 * @param loadFinderCacheEntryPersistence the load finder cache entry persistence
	 */
	public void setLoadFinderCacheEntryPersistence(
		LoadFinderCacheEntryPersistence loadFinderCacheEntryPersistence) {

		this.loadFinderCacheEntryPersistence = loadFinderCacheEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register(
			"com.liferay.portal.tools.service.builder.test.model.LoadFinderCacheEntry",
			loadFinderCacheEntryLocalService);

		_setLocalServiceUtilService(loadFinderCacheEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.portal.tools.service.builder.test.model.LoadFinderCacheEntry");

		_setLocalServiceUtilService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LoadFinderCacheEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LoadFinderCacheEntry.class;
	}

	protected String getModelClassName() {
		return LoadFinderCacheEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				loadFinderCacheEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		LoadFinderCacheEntryLocalService loadFinderCacheEntryLocalService) {

		try {
			Field field =
				LoadFinderCacheEntryLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, loadFinderCacheEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@BeanReference(type = LoadFinderCacheEntryLocalService.class)
	protected LoadFinderCacheEntryLocalService loadFinderCacheEntryLocalService;

	@BeanReference(type = LoadFinderCacheEntryPersistence.class)
	protected LoadFinderCacheEntryPersistence loadFinderCacheEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		LoadFinderCacheEntryLocalServiceBaseImpl.class);

	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry
		persistedModelLocalServiceRegistry;

}