/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.TimestampTypeEntry;
import com.liferay.portal.tools.service.builder.test.service.TimestampTypeEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.TimestampTypeEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.TimestampTypeEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the timestamp type entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.TimestampTypeEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.TimestampTypeEntryLocalServiceImpl
 * @generated
 */
public abstract class TimestampTypeEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService, TimestampTypeEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>TimestampTypeEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>TimestampTypeEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the timestamp type entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TimestampTypeEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param timestampTypeEntry the timestamp type entry
	 * @return the timestamp type entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TimestampTypeEntry addTimestampTypeEntry(
		TimestampTypeEntry timestampTypeEntry) {

		timestampTypeEntry.setNew(true);

		return timestampTypeEntryPersistence.update(timestampTypeEntry);
	}

	/**
	 * Creates a new timestamp type entry with the primary key. Does not add the timestamp type entry to the database.
	 *
	 * @param timestampTypeEntryId the primary key for the new timestamp type entry
	 * @return the new timestamp type entry
	 */
	@Override
	@Transactional(enabled = false)
	public TimestampTypeEntry createTimestampTypeEntry(
		long timestampTypeEntryId) {

		return timestampTypeEntryPersistence.create(timestampTypeEntryId);
	}

	/**
	 * Deletes the timestamp type entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TimestampTypeEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param timestampTypeEntryId the primary key of the timestamp type entry
	 * @return the timestamp type entry that was removed
	 * @throws PortalException if a timestamp type entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TimestampTypeEntry deleteTimestampTypeEntry(
			long timestampTypeEntryId)
		throws PortalException {

		return timestampTypeEntryPersistence.remove(timestampTypeEntryId);
	}

	/**
	 * Deletes the timestamp type entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TimestampTypeEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param timestampTypeEntry the timestamp type entry
	 * @return the timestamp type entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public TimestampTypeEntry deleteTimestampTypeEntry(
		TimestampTypeEntry timestampTypeEntry) {

		return timestampTypeEntryPersistence.remove(timestampTypeEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return timestampTypeEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			TimestampTypeEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return timestampTypeEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.TimestampTypeEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return timestampTypeEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.TimestampTypeEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return timestampTypeEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return timestampTypeEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return timestampTypeEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public TimestampTypeEntry fetchTimestampTypeEntry(
		long timestampTypeEntryId) {

		return timestampTypeEntryPersistence.fetchByPrimaryKey(
			timestampTypeEntryId);
	}

	/**
	 * Returns the timestamp type entry with the primary key.
	 *
	 * @param timestampTypeEntryId the primary key of the timestamp type entry
	 * @return the timestamp type entry
	 * @throws PortalException if a timestamp type entry with the primary key could not be found
	 */
	@Override
	public TimestampTypeEntry getTimestampTypeEntry(long timestampTypeEntryId)
		throws PortalException {

		return timestampTypeEntryPersistence.findByPrimaryKey(
			timestampTypeEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			timestampTypeEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(TimestampTypeEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"timestampTypeEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			timestampTypeEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(TimestampTypeEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"timestampTypeEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			timestampTypeEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(TimestampTypeEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"timestampTypeEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return timestampTypeEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement TimestampTypeEntryLocalServiceImpl#deleteTimestampTypeEntry(TimestampTypeEntry) to avoid orphaned data");
		}

		return timestampTypeEntryLocalService.deleteTimestampTypeEntry(
			(TimestampTypeEntry)persistedModel);
	}

	@Override
	public BasePersistence<TimestampTypeEntry> getBasePersistence() {
		return timestampTypeEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return timestampTypeEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the timestamp type entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.TimestampTypeEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of timestamp type entries
	 * @param end the upper bound of the range of timestamp type entries (not inclusive)
	 * @return the range of timestamp type entries
	 */
	@Override
	public List<TimestampTypeEntry> getTimestampTypeEntries(
		int start, int end) {

		return timestampTypeEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of timestamp type entries.
	 *
	 * @return the number of timestamp type entries
	 */
	@Override
	public int getTimestampTypeEntriesCount() {
		return timestampTypeEntryPersistence.countAll();
	}

	/**
	 * Updates the timestamp type entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect TimestampTypeEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param timestampTypeEntry the timestamp type entry
	 * @return the timestamp type entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public TimestampTypeEntry updateTimestampTypeEntry(
		TimestampTypeEntry timestampTypeEntry) {

		return timestampTypeEntryPersistence.update(timestampTypeEntry);
	}

	/**
	 * Returns the timestamp type entry local service.
	 *
	 * @return the timestamp type entry local service
	 */
	public TimestampTypeEntryLocalService getTimestampTypeEntryLocalService() {
		return timestampTypeEntryLocalService;
	}

	/**
	 * Sets the timestamp type entry local service.
	 *
	 * @param timestampTypeEntryLocalService the timestamp type entry local service
	 */
	public void setTimestampTypeEntryLocalService(
		TimestampTypeEntryLocalService timestampTypeEntryLocalService) {

		this.timestampTypeEntryLocalService = timestampTypeEntryLocalService;
	}

	/**
	 * Returns the timestamp type entry persistence.
	 *
	 * @return the timestamp type entry persistence
	 */
	public TimestampTypeEntryPersistence getTimestampTypeEntryPersistence() {
		return timestampTypeEntryPersistence;
	}

	/**
	 * Sets the timestamp type entry persistence.
	 *
	 * @param timestampTypeEntryPersistence the timestamp type entry persistence
	 */
	public void setTimestampTypeEntryPersistence(
		TimestampTypeEntryPersistence timestampTypeEntryPersistence) {

		this.timestampTypeEntryPersistence = timestampTypeEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		TimestampTypeEntryLocalServiceUtil.setService(
			timestampTypeEntryLocalService);
	}

	public void destroy() {
		TimestampTypeEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return TimestampTypeEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return TimestampTypeEntry.class;
	}

	protected String getModelClassName() {
		return TimestampTypeEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = timestampTypeEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = TimestampTypeEntryLocalService.class)
	protected TimestampTypeEntryLocalService timestampTypeEntryLocalService;

	@BeanReference(type = TimestampTypeEntryPersistence.class)
	protected TimestampTypeEntryPersistence timestampTypeEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		TimestampTypeEntryLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:-1616577198