/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.tools.service.builder.test.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.spring.extender.service.ServiceReference;
import com.liferay.portal.tools.service.builder.test.model.UniqueIndexWithLongTypeEntry;
import com.liferay.portal.tools.service.builder.test.service.UniqueIndexWithLongTypeEntryLocalService;
import com.liferay.portal.tools.service.builder.test.service.UniqueIndexWithLongTypeEntryLocalServiceUtil;
import com.liferay.portal.tools.service.builder.test.service.persistence.UniqueIndexWithLongTypeEntryPersistence;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the unique index with long type entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.tools.service.builder.test.service.impl.UniqueIndexWithLongTypeEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.tools.service.builder.test.service.impl.UniqueIndexWithLongTypeEntryLocalServiceImpl
 * @generated
 */
public abstract class UniqueIndexWithLongTypeEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements IdentifiableOSGiService,
			   UniqueIndexWithLongTypeEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>UniqueIndexWithLongTypeEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>UniqueIndexWithLongTypeEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the unique index with long type entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UniqueIndexWithLongTypeEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param uniqueIndexWithLongTypeEntry the unique index with long type entry
	 * @return the unique index with long type entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UniqueIndexWithLongTypeEntry addUniqueIndexWithLongTypeEntry(
		UniqueIndexWithLongTypeEntry uniqueIndexWithLongTypeEntry) {

		uniqueIndexWithLongTypeEntry.setNew(true);

		return uniqueIndexWithLongTypeEntryPersistence.update(
			uniqueIndexWithLongTypeEntry);
	}

	/**
	 * Creates a new unique index with long type entry with the primary key. Does not add the unique index with long type entry to the database.
	 *
	 * @param uniqueIndexWithLongTypeEntryId the primary key for the new unique index with long type entry
	 * @return the new unique index with long type entry
	 */
	@Override
	@Transactional(enabled = false)
	public UniqueIndexWithLongTypeEntry createUniqueIndexWithLongTypeEntry(
		long uniqueIndexWithLongTypeEntryId) {

		return uniqueIndexWithLongTypeEntryPersistence.create(
			uniqueIndexWithLongTypeEntryId);
	}

	/**
	 * Deletes the unique index with long type entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UniqueIndexWithLongTypeEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param uniqueIndexWithLongTypeEntryId the primary key of the unique index with long type entry
	 * @return the unique index with long type entry that was removed
	 * @throws PortalException if a unique index with long type entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UniqueIndexWithLongTypeEntry deleteUniqueIndexWithLongTypeEntry(
			long uniqueIndexWithLongTypeEntryId)
		throws PortalException {

		return uniqueIndexWithLongTypeEntryPersistence.remove(
			uniqueIndexWithLongTypeEntryId);
	}

	/**
	 * Deletes the unique index with long type entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UniqueIndexWithLongTypeEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param uniqueIndexWithLongTypeEntry the unique index with long type entry
	 * @return the unique index with long type entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public UniqueIndexWithLongTypeEntry deleteUniqueIndexWithLongTypeEntry(
		UniqueIndexWithLongTypeEntry uniqueIndexWithLongTypeEntry) {

		return uniqueIndexWithLongTypeEntryPersistence.remove(
			uniqueIndexWithLongTypeEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return uniqueIndexWithLongTypeEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			UniqueIndexWithLongTypeEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return uniqueIndexWithLongTypeEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.UniqueIndexWithLongTypeEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return uniqueIndexWithLongTypeEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.UniqueIndexWithLongTypeEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return uniqueIndexWithLongTypeEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return uniqueIndexWithLongTypeEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return uniqueIndexWithLongTypeEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public UniqueIndexWithLongTypeEntry fetchUniqueIndexWithLongTypeEntry(
		long uniqueIndexWithLongTypeEntryId) {

		return uniqueIndexWithLongTypeEntryPersistence.fetchByPrimaryKey(
			uniqueIndexWithLongTypeEntryId);
	}

	/**
	 * Returns the unique index with long type entry with the primary key.
	 *
	 * @param uniqueIndexWithLongTypeEntryId the primary key of the unique index with long type entry
	 * @return the unique index with long type entry
	 * @throws PortalException if a unique index with long type entry with the primary key could not be found
	 */
	@Override
	public UniqueIndexWithLongTypeEntry getUniqueIndexWithLongTypeEntry(
			long uniqueIndexWithLongTypeEntryId)
		throws PortalException {

		return uniqueIndexWithLongTypeEntryPersistence.findByPrimaryKey(
			uniqueIndexWithLongTypeEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			uniqueIndexWithLongTypeEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			UniqueIndexWithLongTypeEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"uniqueIndexWithLongTypeEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			uniqueIndexWithLongTypeEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			UniqueIndexWithLongTypeEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"uniqueIndexWithLongTypeEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			uniqueIndexWithLongTypeEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(
			UniqueIndexWithLongTypeEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"uniqueIndexWithLongTypeEntryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return uniqueIndexWithLongTypeEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement UniqueIndexWithLongTypeEntryLocalServiceImpl#deleteUniqueIndexWithLongTypeEntry(UniqueIndexWithLongTypeEntry) to avoid orphaned data");
		}

		return uniqueIndexWithLongTypeEntryLocalService.
			deleteUniqueIndexWithLongTypeEntry(
				(UniqueIndexWithLongTypeEntry)persistedModel);
	}

	@Override
	public BasePersistence<UniqueIndexWithLongTypeEntry> getBasePersistence() {
		return uniqueIndexWithLongTypeEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return uniqueIndexWithLongTypeEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the unique index with long type entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.tools.service.builder.test.model.impl.UniqueIndexWithLongTypeEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of unique index with long type entries
	 * @param end the upper bound of the range of unique index with long type entries (not inclusive)
	 * @return the range of unique index with long type entries
	 */
	@Override
	public List<UniqueIndexWithLongTypeEntry> getUniqueIndexWithLongTypeEntries(
		int start, int end) {

		return uniqueIndexWithLongTypeEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of unique index with long type entries.
	 *
	 * @return the number of unique index with long type entries
	 */
	@Override
	public int getUniqueIndexWithLongTypeEntriesCount() {
		return uniqueIndexWithLongTypeEntryPersistence.countAll();
	}

	/**
	 * Updates the unique index with long type entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect UniqueIndexWithLongTypeEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param uniqueIndexWithLongTypeEntry the unique index with long type entry
	 * @return the unique index with long type entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public UniqueIndexWithLongTypeEntry updateUniqueIndexWithLongTypeEntry(
		UniqueIndexWithLongTypeEntry uniqueIndexWithLongTypeEntry) {

		return uniqueIndexWithLongTypeEntryPersistence.update(
			uniqueIndexWithLongTypeEntry);
	}

	/**
	 * Returns the unique index with long type entry local service.
	 *
	 * @return the unique index with long type entry local service
	 */
	public UniqueIndexWithLongTypeEntryLocalService
		getUniqueIndexWithLongTypeEntryLocalService() {

		return uniqueIndexWithLongTypeEntryLocalService;
	}

	/**
	 * Sets the unique index with long type entry local service.
	 *
	 * @param uniqueIndexWithLongTypeEntryLocalService the unique index with long type entry local service
	 */
	public void setUniqueIndexWithLongTypeEntryLocalService(
		UniqueIndexWithLongTypeEntryLocalService
			uniqueIndexWithLongTypeEntryLocalService) {

		this.uniqueIndexWithLongTypeEntryLocalService =
			uniqueIndexWithLongTypeEntryLocalService;
	}

	/**
	 * Returns the unique index with long type entry persistence.
	 *
	 * @return the unique index with long type entry persistence
	 */
	public UniqueIndexWithLongTypeEntryPersistence
		getUniqueIndexWithLongTypeEntryPersistence() {

		return uniqueIndexWithLongTypeEntryPersistence;
	}

	/**
	 * Sets the unique index with long type entry persistence.
	 *
	 * @param uniqueIndexWithLongTypeEntryPersistence the unique index with long type entry persistence
	 */
	public void setUniqueIndexWithLongTypeEntryPersistence(
		UniqueIndexWithLongTypeEntryPersistence
			uniqueIndexWithLongTypeEntryPersistence) {

		this.uniqueIndexWithLongTypeEntryPersistence =
			uniqueIndexWithLongTypeEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService
		getCounterLocalService() {

		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService
			counterLocalService) {

		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		UniqueIndexWithLongTypeEntryLocalServiceUtil.setService(
			uniqueIndexWithLongTypeEntryLocalService);
	}

	public void destroy() {
		UniqueIndexWithLongTypeEntryLocalServiceUtil.setService(null);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return UniqueIndexWithLongTypeEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return UniqueIndexWithLongTypeEntry.class;
	}

	protected String getModelClassName() {
		return UniqueIndexWithLongTypeEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource =
			uniqueIndexWithLongTypeEntryPersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@BeanReference(type = UniqueIndexWithLongTypeEntryLocalService.class)
	protected UniqueIndexWithLongTypeEntryLocalService
		uniqueIndexWithLongTypeEntryLocalService;

	@BeanReference(type = UniqueIndexWithLongTypeEntryPersistence.class)
	protected UniqueIndexWithLongTypeEntryPersistence
		uniqueIndexWithLongTypeEntryPersistence;

	@ServiceReference(
		type = com.liferay.counter.kernel.service.CounterLocalService.class
	)
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		UniqueIndexWithLongTypeEntryLocalServiceBaseImpl.class);

}