/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EagerFinderCacheEntry service. Represents a row in the &quot;EagerFinderCacheEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerFinderCacheEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.tools.service.builder.test.model.impl.EagerFinderCacheEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EagerFinderCacheEntry
 * @generated
 */
@ProviderType
public interface EagerFinderCacheEntryModel
	extends BaseModel<EagerFinderCacheEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a eager finder cache entry model instance should use the {@link EagerFinderCacheEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this eager finder cache entry.
	 *
	 * @return the primary key of this eager finder cache entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this eager finder cache entry.
	 *
	 * @param primaryKey the primary key of this eager finder cache entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the eager finder cache entry ID of this eager finder cache entry.
	 *
	 * @return the eager finder cache entry ID of this eager finder cache entry
	 */
	public long getEagerFinderCacheEntryId();

	/**
	 * Sets the eager finder cache entry ID of this eager finder cache entry.
	 *
	 * @param eagerFinderCacheEntryId the eager finder cache entry ID of this eager finder cache entry
	 */
	public void setEagerFinderCacheEntryId(long eagerFinderCacheEntryId);

	/**
	 * Returns the group ID of this eager finder cache entry.
	 *
	 * @return the group ID of this eager finder cache entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this eager finder cache entry.
	 *
	 * @param groupId the group ID of this eager finder cache entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this eager finder cache entry.
	 *
	 * @return the company ID of this eager finder cache entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this eager finder cache entry.
	 *
	 * @param companyId the company ID of this eager finder cache entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the unique name of this eager finder cache entry.
	 *
	 * @return the unique name of this eager finder cache entry
	 */
	@AutoEscape
	public String getUniqueName();

	/**
	 * Sets the unique name of this eager finder cache entry.
	 *
	 * @param uniqueName the unique name of this eager finder cache entry
	 */
	public void setUniqueName(String uniqueName);

	@Override
	public EagerFinderCacheEntry cloneWithOriginalValues();

}