author=Liferay, Inc.
change-log=
Import-Package:\
    org.jboss.weld.module.web.el
licenses=LGPL
module-group-id=liferay
module-version=1.0.0
name=Sample Bean Portlet
page-url=http://www.liferay.com
tags=sample