/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.dynamic.data.mapping.model.impl;

import com.liferay.dynamic.data.mapping.model.DDMTemplate;
import com.liferay.dynamic.data.mapping.model.DDMTemplateModel;
import com.liferay.dynamic.data.mapping.model.DDMTemplateSoap;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.LocaleUtil;
import com.liferay.portal.kernel.util.LocalizationUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.Validator;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DDMTemplate service. Represents a row in the &quot;DDMTemplate&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DDMTemplateModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DDMTemplateImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDMTemplateImpl
 * @generated
 */
@JSON(strict = true)
public class DDMTemplateModelImpl
	extends BaseModelImpl<DDMTemplate> implements DDMTemplateModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ddm template model instance should use the <code>DDMTemplate</code> interface instead.
	 */
	public static final String TABLE_NAME = "DDMTemplate";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR}, {"templateId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"versionUserId", Types.BIGINT}, {"versionUserName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"classNameId", Types.BIGINT}, {"classPK", Types.BIGINT},
		{"resourceClassNameId", Types.BIGINT}, {"templateKey", Types.VARCHAR},
		{"version", Types.VARCHAR}, {"name", Types.CLOB},
		{"description", Types.CLOB}, {"type_", Types.VARCHAR},
		{"mode_", Types.VARCHAR}, {"language", Types.VARCHAR},
		{"script", Types.CLOB}, {"cacheable", Types.BOOLEAN},
		{"smallImage", Types.BOOLEAN}, {"smallImageId", Types.BIGINT},
		{"smallImageURL", Types.VARCHAR}, {"lastPublishDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("templateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("versionUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("versionUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("resourceClassNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("templateKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.CLOB);
		TABLE_COLUMNS_MAP.put("description", Types.CLOB);
		TABLE_COLUMNS_MAP.put("type_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("mode_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("language", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("script", Types.CLOB);
		TABLE_COLUMNS_MAP.put("cacheable", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("smallImage", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("smallImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("smallImageURL", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DDMTemplate (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,templateId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,versionUserId LONG,versionUserName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,classNameId LONG,classPK LONG,resourceClassNameId LONG,templateKey VARCHAR(75) null,version VARCHAR(75) null,name TEXT null,description TEXT null,type_ VARCHAR(75) null,mode_ VARCHAR(75) null,language VARCHAR(75) null,script TEXT null,cacheable BOOLEAN,smallImage BOOLEAN,smallImageId LONG,smallImageURL STRING null,lastPublishDate DATE null,primary key (templateId, ctCollectionId))";

	public static final String TABLE_SQL_DROP = "drop table DDMTemplate";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ddmTemplate.templateId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DDMTemplate.templateId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long MVCCVERSION_COLUMN_BITMASK = 1L;

	public static final long CTCOLLECTIONID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long TEMPLATEID_COLUMN_BITMASK = 8L;

	public static final long GROUPID_COLUMN_BITMASK = 16L;

	public static final long COMPANYID_COLUMN_BITMASK = 32L;

	public static final long USERID_COLUMN_BITMASK = 64L;

	public static final long USERNAME_COLUMN_BITMASK = 128L;

	public static final long VERSIONUSERID_COLUMN_BITMASK = 256L;

	public static final long VERSIONUSERNAME_COLUMN_BITMASK = 512L;

	public static final long CREATEDATE_COLUMN_BITMASK = 1024L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 2048L;

	public static final long CLASSNAMEID_COLUMN_BITMASK = 4096L;

	public static final long CLASSPK_COLUMN_BITMASK = 8192L;

	public static final long RESOURCECLASSNAMEID_COLUMN_BITMASK = 16384L;

	public static final long TEMPLATEKEY_COLUMN_BITMASK = 32768L;

	public static final long VERSION_COLUMN_BITMASK = 65536L;

	public static final long NAME_COLUMN_BITMASK = 131072L;

	public static final long DESCRIPTION_COLUMN_BITMASK = 262144L;

	public static final long TYPE_COLUMN_BITMASK = 524288L;

	public static final long MODE_COLUMN_BITMASK = 1048576L;

	public static final long LANGUAGE_COLUMN_BITMASK = 2097152L;

	public static final long SCRIPT_COLUMN_BITMASK = 4194304L;

	public static final long CACHEABLE_COLUMN_BITMASK = 8388608L;

	public static final long SMALLIMAGE_COLUMN_BITMASK = 16777216L;

	public static final long SMALLIMAGEID_COLUMN_BITMASK = 33554432L;

	public static final long SMALLIMAGEURL_COLUMN_BITMASK = 67108864L;

	public static final long LASTPUBLISHDATE_COLUMN_BITMASK = 134217728L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DDMTemplate toModel(DDMTemplateSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DDMTemplate model = new DDMTemplateImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setCtCollectionId(soapModel.getCtCollectionId());
		model.setUuid(soapModel.getUuid());
		model.setTemplateId(soapModel.getTemplateId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setVersionUserId(soapModel.getVersionUserId());
		model.setVersionUserName(soapModel.getVersionUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setClassNameId(soapModel.getClassNameId());
		model.setClassPK(soapModel.getClassPK());
		model.setResourceClassNameId(soapModel.getResourceClassNameId());
		model.setTemplateKey(soapModel.getTemplateKey());
		model.setVersion(soapModel.getVersion());
		model.setName(soapModel.getName());
		model.setDescription(soapModel.getDescription());
		model.setType(soapModel.getType());
		model.setMode(soapModel.getMode());
		model.setLanguage(soapModel.getLanguage());
		model.setScript(soapModel.getScript());
		model.setCacheable(soapModel.isCacheable());
		model.setSmallImage(soapModel.isSmallImage());
		model.setSmallImageId(soapModel.getSmallImageId());
		model.setSmallImageURL(soapModel.getSmallImageURL());
		model.setLastPublishDate(soapModel.getLastPublishDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DDMTemplate> toModels(DDMTemplateSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DDMTemplate> models = new ArrayList<DDMTemplate>(
			soapModels.length);

		for (DDMTemplateSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public DDMTemplateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _templateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTemplateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _templateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DDMTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return DDMTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DDMTemplate, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DDMTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DDMTemplate, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DDMTemplate)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DDMTemplate, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DDMTemplate, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DDMTemplate)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DDMTemplate, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DDMTemplate, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DDMTemplate>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DDMTemplate.class.getClassLoader(), DDMTemplate.class,
			ModelWrapper.class);

		try {
			Constructor<DDMTemplate> constructor =
				(Constructor<DDMTemplate>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	public <T> T getAttribute(String attribute) {
		Function<DDMTemplate, Object> function = _attributeGetterFunctions.get(
			attribute);

		if (function == null) {
			return null;
		}

		return (T)function.apply((DDMTemplate)this);
	}

	public <T> T getCacheModelAttribute(String attribute) {
		Function<DDMTemplateCacheModel, Object> function =
			_cacheModelGetterFunctions.get(attribute);

		if (function == null) {
			return null;
		}

		if (_ddmTemplateCacheModel == null) {
			return null;
		}

		return (T)function.apply(_ddmTemplateCacheModel);
	}

	private static final Map<String, Function<DDMTemplate, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DDMTemplate, Object>>
		_attributeSetterBiConsumers;
	private static final Map<String, Function<DDMTemplateCacheModel, Object>>
		_cacheModelGetterFunctions;

	static {
		Map<String, Function<DDMTemplate, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DDMTemplate, Object>>();
		Map<String, BiConsumer<DDMTemplate, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DDMTemplate, ?>>();
		Map<String, Function<DDMTemplateCacheModel, Object>>
			cacheModelGetterFunctions =
				new LinkedHashMap
					<String, Function<DDMTemplateCacheModel, Object>>();

		attributeGetterFunctions.put(
			"mvccVersion", DDMTemplate::getMvccVersion);

		cacheModelGetterFunctions.put(
			"mvccVersion",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.mvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<DDMTemplate, Long>)DDMTemplate::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", DDMTemplate::getCtCollectionId);

		cacheModelGetterFunctions.put(
			"ctCollectionId",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.ctCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<DDMTemplate, Long>)DDMTemplate::setCtCollectionId);
		attributeGetterFunctions.put("uuid", DDMTemplate::getUuid);

		cacheModelGetterFunctions.put(
			"uuid", ddmTemplateCacheModel -> ddmTemplateCacheModel.uuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<DDMTemplate, String>)DDMTemplate::setUuid);
		attributeGetterFunctions.put("templateId", DDMTemplate::getTemplateId);

		cacheModelGetterFunctions.put(
			"templateId",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.templateId);
		attributeSetterBiConsumers.put(
			"templateId",
			(BiConsumer<DDMTemplate, Long>)DDMTemplate::setTemplateId);
		attributeGetterFunctions.put("groupId", DDMTemplate::getGroupId);

		cacheModelGetterFunctions.put(
			"groupId", ddmTemplateCacheModel -> ddmTemplateCacheModel.groupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<DDMTemplate, Long>)DDMTemplate::setGroupId);
		attributeGetterFunctions.put("companyId", DDMTemplate::getCompanyId);

		cacheModelGetterFunctions.put(
			"companyId",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.companyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DDMTemplate, Long>)DDMTemplate::setCompanyId);
		attributeGetterFunctions.put("userId", DDMTemplate::getUserId);

		cacheModelGetterFunctions.put(
			"userId", ddmTemplateCacheModel -> ddmTemplateCacheModel.userId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<DDMTemplate, Long>)DDMTemplate::setUserId);
		attributeGetterFunctions.put("userName", DDMTemplate::getUserName);

		cacheModelGetterFunctions.put(
			"userName",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.userName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DDMTemplate, String>)DDMTemplate::setUserName);
		attributeGetterFunctions.put(
			"versionUserId", DDMTemplate::getVersionUserId);

		cacheModelGetterFunctions.put(
			"versionUserId",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.versionUserId);
		attributeSetterBiConsumers.put(
			"versionUserId",
			(BiConsumer<DDMTemplate, Long>)DDMTemplate::setVersionUserId);
		attributeGetterFunctions.put(
			"versionUserName", DDMTemplate::getVersionUserName);

		cacheModelGetterFunctions.put(
			"versionUserName",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.versionUserName);
		attributeSetterBiConsumers.put(
			"versionUserName",
			(BiConsumer<DDMTemplate, String>)DDMTemplate::setVersionUserName);
		attributeGetterFunctions.put("createDate", DDMTemplate::getCreateDate);

		cacheModelGetterFunctions.put(
			"createDate",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.createDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DDMTemplate, Date>)DDMTemplate::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DDMTemplate::getModifiedDate);

		cacheModelGetterFunctions.put(
			"modifiedDate",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.modifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DDMTemplate, Date>)DDMTemplate::setModifiedDate);
		attributeGetterFunctions.put(
			"classNameId", DDMTemplate::getClassNameId);

		cacheModelGetterFunctions.put(
			"classNameId",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.classNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<DDMTemplate, Long>)DDMTemplate::setClassNameId);
		attributeGetterFunctions.put("classPK", DDMTemplate::getClassPK);

		cacheModelGetterFunctions.put(
			"classPK", ddmTemplateCacheModel -> ddmTemplateCacheModel.classPK);
		attributeSetterBiConsumers.put(
			"classPK", (BiConsumer<DDMTemplate, Long>)DDMTemplate::setClassPK);
		attributeGetterFunctions.put(
			"resourceClassNameId", DDMTemplate::getResourceClassNameId);

		cacheModelGetterFunctions.put(
			"resourceClassNameId",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.resourceClassNameId);
		attributeSetterBiConsumers.put(
			"resourceClassNameId",
			(BiConsumer<DDMTemplate, Long>)DDMTemplate::setResourceClassNameId);
		attributeGetterFunctions.put(
			"templateKey", DDMTemplate::getTemplateKey);

		cacheModelGetterFunctions.put(
			"templateKey",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.templateKey);
		attributeSetterBiConsumers.put(
			"templateKey",
			(BiConsumer<DDMTemplate, String>)DDMTemplate::setTemplateKey);
		attributeGetterFunctions.put("version", DDMTemplate::getVersion);

		cacheModelGetterFunctions.put(
			"version", ddmTemplateCacheModel -> ddmTemplateCacheModel.version);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<DDMTemplate, String>)DDMTemplate::setVersion);
		attributeGetterFunctions.put("name", DDMTemplate::getName);

		cacheModelGetterFunctions.put(
			"name", ddmTemplateCacheModel -> ddmTemplateCacheModel.name);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<DDMTemplate, String>)DDMTemplate::setName);
		attributeGetterFunctions.put(
			"description", DDMTemplate::getDescription);

		cacheModelGetterFunctions.put(
			"description",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.description);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<DDMTemplate, String>)DDMTemplate::setDescription);
		attributeGetterFunctions.put("type", DDMTemplate::getType);

		cacheModelGetterFunctions.put(
			"type", ddmTemplateCacheModel -> ddmTemplateCacheModel.type);
		attributeSetterBiConsumers.put(
			"type", (BiConsumer<DDMTemplate, String>)DDMTemplate::setType);
		attributeGetterFunctions.put("mode", DDMTemplate::getMode);

		cacheModelGetterFunctions.put(
			"mode", ddmTemplateCacheModel -> ddmTemplateCacheModel.mode);
		attributeSetterBiConsumers.put(
			"mode", (BiConsumer<DDMTemplate, String>)DDMTemplate::setMode);
		attributeGetterFunctions.put("language", DDMTemplate::getLanguage);

		cacheModelGetterFunctions.put(
			"language",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.language);
		attributeSetterBiConsumers.put(
			"language",
			(BiConsumer<DDMTemplate, String>)DDMTemplate::setLanguage);
		attributeGetterFunctions.put("script", DDMTemplate::getScript);

		cacheModelGetterFunctions.put(
			"script", ddmTemplateCacheModel -> ddmTemplateCacheModel.script);
		attributeSetterBiConsumers.put(
			"script", (BiConsumer<DDMTemplate, String>)DDMTemplate::setScript);
		attributeGetterFunctions.put("cacheable", DDMTemplate::getCacheable);

		cacheModelGetterFunctions.put(
			"cacheable",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.cacheable);
		attributeSetterBiConsumers.put(
			"cacheable",
			(BiConsumer<DDMTemplate, Boolean>)DDMTemplate::setCacheable);
		attributeGetterFunctions.put("smallImage", DDMTemplate::getSmallImage);

		cacheModelGetterFunctions.put(
			"smallImage",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.smallImage);
		attributeSetterBiConsumers.put(
			"smallImage",
			(BiConsumer<DDMTemplate, Boolean>)DDMTemplate::setSmallImage);
		attributeGetterFunctions.put(
			"smallImageId", DDMTemplate::getSmallImageId);

		cacheModelGetterFunctions.put(
			"smallImageId",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.smallImageId);
		attributeSetterBiConsumers.put(
			"smallImageId",
			(BiConsumer<DDMTemplate, Long>)DDMTemplate::setSmallImageId);
		attributeGetterFunctions.put(
			"smallImageURL", DDMTemplate::getSmallImageURL);

		cacheModelGetterFunctions.put(
			"smallImageURL",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.smallImageURL);
		attributeSetterBiConsumers.put(
			"smallImageURL",
			(BiConsumer<DDMTemplate, String>)DDMTemplate::setSmallImageURL);
		attributeGetterFunctions.put(
			"lastPublishDate", DDMTemplate::getLastPublishDate);

		cacheModelGetterFunctions.put(
			"lastPublishDate",
			ddmTemplateCacheModel -> ddmTemplateCacheModel.lastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<DDMTemplate, Date>)DDMTemplate::setLastPublishDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
		_cacheModelGetterFunctions = Collections.unmodifiableMap(
			cacheModelGetterFunctions);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_columnBitmask |= MVCCVERSION_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		_columnBitmask |= CTCOLLECTIONID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_ctCollectionId = ctCollectionId;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getCacheModelAttribute("uuid");
	}

	@JSON
	@Override
	public long getTemplateId() {
		return _templateId;
	}

	@Override
	public void setTemplateId(long templateId) {
		_columnBitmask |= TEMPLATEID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_templateId = templateId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return getCacheModelAttribute("groupId");
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return getCacheModelAttribute("companyId");
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_columnBitmask |= USERNAME_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public long getVersionUserId() {
		return _versionUserId;
	}

	@Override
	public void setVersionUserId(long versionUserId) {
		_columnBitmask |= VERSIONUSERID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_versionUserId = versionUserId;
	}

	@Override
	public String getVersionUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getVersionUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setVersionUserUuid(String versionUserUuid) {
	}

	@JSON
	@Override
	public String getVersionUserName() {
		if (_versionUserName == null) {
			return "";
		}
		else {
			return _versionUserName;
		}
	}

	@Override
	public void setVersionUserName(String versionUserName) {
		_columnBitmask |= VERSIONUSERNAME_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_versionUserName = versionUserName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask |= CREATEDATE_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask |= MODIFIEDDATE_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@JSON
	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		_columnBitmask |= CLASSNAMEID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return getCacheModelAttribute("classNameId");
	}

	@JSON
	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		_columnBitmask |= CLASSPK_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return getCacheModelAttribute("classPK");
	}

	@JSON
	@Override
	public long getResourceClassNameId() {
		return _resourceClassNameId;
	}

	@Override
	public void setResourceClassNameId(long resourceClassNameId) {
		_columnBitmask |= RESOURCECLASSNAMEID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_resourceClassNameId = resourceClassNameId;
	}

	@JSON
	@Override
	public String getTemplateKey() {
		if (_templateKey == null) {
			return "";
		}
		else {
			return _templateKey;
		}
	}

	@Override
	public void setTemplateKey(String templateKey) {
		_columnBitmask |= TEMPLATEKEY_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_templateKey = templateKey;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalTemplateKey() {
		return getCacheModelAttribute("templateKey");
	}

	@JSON
	@Override
	public String getVersion() {
		if (_version == null) {
			return "";
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		_columnBitmask |= VERSION_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_version = version;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public String getName(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId);
	}

	@Override
	public String getName(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getName(languageId, useDefault);
	}

	@Override
	public String getName(String languageId) {
		return LocalizationUtil.getLocalization(getName(), languageId);
	}

	@Override
	public String getName(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getName(), languageId, useDefault);
	}

	@Override
	public String getNameCurrentLanguageId() {
		return _nameCurrentLanguageId;
	}

	@JSON
	@Override
	public String getNameCurrentValue() {
		Locale locale = getLocale(_nameCurrentLanguageId);

		return getName(locale);
	}

	@Override
	public Map<Locale, String> getNameMap() {
		return LocalizationUtil.getLocalizationMap(getName());
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_name = name;
	}

	@Override
	public void setName(String name, Locale locale) {
		setName(name, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setName(String name, Locale locale, Locale defaultLocale) {
		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(name)) {
			setName(
				LocalizationUtil.updateLocalization(
					getName(), "Name", name, languageId, defaultLanguageId));
		}
		else {
			setName(
				LocalizationUtil.removeLocalization(
					getName(), "Name", languageId));
		}
	}

	@Override
	public void setNameCurrentLanguageId(String languageId) {
		_nameCurrentLanguageId = languageId;
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap) {
		setNameMap(nameMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale) {
		if (nameMap == null) {
			return;
		}

		setName(
			LocalizationUtil.updateLocalization(
				nameMap, getName(), "Name",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public String getDescription(Locale locale) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId);
	}

	@Override
	public String getDescription(Locale locale, boolean useDefault) {
		String languageId = LocaleUtil.toLanguageId(locale);

		return getDescription(languageId, useDefault);
	}

	@Override
	public String getDescription(String languageId) {
		return LocalizationUtil.getLocalization(getDescription(), languageId);
	}

	@Override
	public String getDescription(String languageId, boolean useDefault) {
		return LocalizationUtil.getLocalization(
			getDescription(), languageId, useDefault);
	}

	@Override
	public String getDescriptionCurrentLanguageId() {
		return _descriptionCurrentLanguageId;
	}

	@JSON
	@Override
	public String getDescriptionCurrentValue() {
		Locale locale = getLocale(_descriptionCurrentLanguageId);

		return getDescription(locale);
	}

	@Override
	public Map<Locale, String> getDescriptionMap() {
		return LocalizationUtil.getLocalizationMap(getDescription());
	}

	@Override
	public void setDescription(String description) {
		_columnBitmask |= DESCRIPTION_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_description = description;
	}

	@Override
	public void setDescription(String description, Locale locale) {
		setDescription(description, locale, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescription(
		String description, Locale locale, Locale defaultLocale) {

		String languageId = LocaleUtil.toLanguageId(locale);
		String defaultLanguageId = LocaleUtil.toLanguageId(defaultLocale);

		if (Validator.isNotNull(description)) {
			setDescription(
				LocalizationUtil.updateLocalization(
					getDescription(), "Description", description, languageId,
					defaultLanguageId));
		}
		else {
			setDescription(
				LocalizationUtil.removeLocalization(
					getDescription(), "Description", languageId));
		}
	}

	@Override
	public void setDescriptionCurrentLanguageId(String languageId) {
		_descriptionCurrentLanguageId = languageId;
	}

	@Override
	public void setDescriptionMap(Map<Locale, String> descriptionMap) {
		setDescriptionMap(descriptionMap, LocaleUtil.getSiteDefault());
	}

	@Override
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale) {

		if (descriptionMap == null) {
			return;
		}

		setDescription(
			LocalizationUtil.updateLocalization(
				descriptionMap, getDescription(), "Description",
				LocaleUtil.toLanguageId(defaultLocale)));
	}

	@JSON
	@Override
	public String getType() {
		if (_type == null) {
			return "";
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_columnBitmask |= TYPE_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_type = type;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalType() {
		return getCacheModelAttribute("type");
	}

	@JSON
	@Override
	public String getMode() {
		if (_mode == null) {
			return "";
		}
		else {
			return _mode;
		}
	}

	@Override
	public void setMode(String mode) {
		_columnBitmask |= MODE_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_mode = mode;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalMode() {
		return getCacheModelAttribute("mode");
	}

	@JSON
	@Override
	public String getLanguage() {
		if (_language == null) {
			return "";
		}
		else {
			return _language;
		}
	}

	@Override
	public void setLanguage(String language) {
		_columnBitmask |= LANGUAGE_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_language = language;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public String getOriginalLanguage() {
		return getCacheModelAttribute("language");
	}

	@JSON
	@Override
	public String getScript() {
		if (_script == null) {
			return "";
		}
		else {
			return _script;
		}
	}

	@Override
	public void setScript(String script) {
		_columnBitmask |= SCRIPT_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_script = script;
	}

	@JSON
	@Override
	public boolean getCacheable() {
		return _cacheable;
	}

	@JSON
	@Override
	public boolean isCacheable() {
		return _cacheable;
	}

	@Override
	public void setCacheable(boolean cacheable) {
		_columnBitmask |= CACHEABLE_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_cacheable = cacheable;
	}

	@JSON
	@Override
	public boolean getSmallImage() {
		return _smallImage;
	}

	@JSON
	@Override
	public boolean isSmallImage() {
		return _smallImage;
	}

	@Override
	public void setSmallImage(boolean smallImage) {
		_columnBitmask |= SMALLIMAGE_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_smallImage = smallImage;
	}

	@JSON
	@Override
	public long getSmallImageId() {
		return _smallImageId;
	}

	@Override
	public void setSmallImageId(long smallImageId) {
		_columnBitmask |= SMALLIMAGEID_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_smallImageId = smallImageId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getCacheModelAttribute(String)}
	 */
	@Deprecated
	public long getOriginalSmallImageId() {
		return getCacheModelAttribute("smallImageId");
	}

	@JSON
	@Override
	public String getSmallImageURL() {
		if (_smallImageURL == null) {
			return "";
		}
		else {
			return _smallImageURL;
		}
	}

	@Override
	public void setSmallImageURL(String smallImageURL) {
		_columnBitmask |= SMALLIMAGEURL_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_smallImageURL = smallImageURL;
	}

	@JSON
	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_columnBitmask |= LASTPUBLISHDATE_COLUMN_BITMASK;

		if (!isNew() && (_ddmTemplateCacheModel == null)) {
			_ddmTemplateCacheModel = (DDMTemplateCacheModel)toCacheModel();
		}

		_lastPublishDate = lastPublishDate;
	}

	public String getResourceClassName() {
		return null;
	}

	public void setResourceClassName(String resourceClassName) {
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DDMTemplate.class.getName()),
			getClassNameId());
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DDMTemplate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public String[] getAvailableLanguageIds() {
		Set<String> availableLanguageIds = new TreeSet<String>();

		Map<Locale, String> nameMap = getNameMap();

		for (Map.Entry<Locale, String> entry : nameMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		Map<Locale, String> descriptionMap = getDescriptionMap();

		for (Map.Entry<Locale, String> entry : descriptionMap.entrySet()) {
			Locale locale = entry.getKey();
			String value = entry.getValue();

			if (Validator.isNotNull(value)) {
				availableLanguageIds.add(LocaleUtil.toLanguageId(locale));
			}
		}

		return availableLanguageIds.toArray(
			new String[availableLanguageIds.size()]);
	}

	@Override
	public String getDefaultLanguageId() {
		String xml = getName();

		if (xml == null) {
			return "";
		}

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		return LocalizationUtil.getDefaultLanguageId(xml, defaultLocale);
	}

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException {
		Locale defaultLocale = LocaleUtil.fromLanguageId(
			getDefaultLanguageId());

		Locale[] availableLocales = LocaleUtil.fromLanguageIds(
			getAvailableLanguageIds());

		Locale defaultImportLocale = LocalizationUtil.getDefaultImportLocale(
			DDMTemplate.class.getName(), getPrimaryKey(), defaultLocale,
			availableLocales);

		prepareLocalizedFieldsForImport(defaultImportLocale);
	}

	@Override
	@SuppressWarnings("unused")
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException {

		Locale defaultLocale = LocaleUtil.getSiteDefault();

		String modelDefaultLanguageId = getDefaultLanguageId();

		String name = getName(defaultLocale);

		if (Validator.isNull(name)) {
			setName(getName(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setName(getName(defaultLocale), defaultLocale, defaultLocale);
		}

		String description = getDescription(defaultLocale);

		if (Validator.isNull(description)) {
			setDescription(
				getDescription(modelDefaultLanguageId), defaultLocale);
		}
		else {
			setDescription(
				getDescription(defaultLocale), defaultLocale, defaultLocale);
		}
	}

	@Override
	public DDMTemplate toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DDMTemplate>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DDMTemplateImpl ddmTemplateImpl = new DDMTemplateImpl();

		ddmTemplateImpl.setNew(true);

		ddmTemplateImpl.setMvccVersion(getMvccVersion());
		ddmTemplateImpl.setCtCollectionId(getCtCollectionId());
		ddmTemplateImpl.setUuid(getUuid());
		ddmTemplateImpl.setTemplateId(getTemplateId());
		ddmTemplateImpl.setGroupId(getGroupId());
		ddmTemplateImpl.setCompanyId(getCompanyId());
		ddmTemplateImpl.setUserId(getUserId());
		ddmTemplateImpl.setUserName(getUserName());
		ddmTemplateImpl.setVersionUserId(getVersionUserId());
		ddmTemplateImpl.setVersionUserName(getVersionUserName());
		ddmTemplateImpl.setCreateDate(getCreateDate());
		ddmTemplateImpl.setModifiedDate(getModifiedDate());
		ddmTemplateImpl.setClassNameId(getClassNameId());
		ddmTemplateImpl.setClassPK(getClassPK());
		ddmTemplateImpl.setResourceClassNameId(getResourceClassNameId());
		ddmTemplateImpl.setTemplateKey(getTemplateKey());
		ddmTemplateImpl.setVersion(getVersion());
		ddmTemplateImpl.setName(getName());
		ddmTemplateImpl.setDescription(getDescription());
		ddmTemplateImpl.setType(getType());
		ddmTemplateImpl.setMode(getMode());
		ddmTemplateImpl.setLanguage(getLanguage());
		ddmTemplateImpl.setScript(getScript());
		ddmTemplateImpl.setCacheable(isCacheable());
		ddmTemplateImpl.setSmallImage(isSmallImage());
		ddmTemplateImpl.setSmallImageId(getSmallImageId());
		ddmTemplateImpl.setSmallImageURL(getSmallImageURL());
		ddmTemplateImpl.setLastPublishDate(getLastPublishDate());

		ddmTemplateImpl.resetOriginalValues();

		ddmTemplateImpl.setNew(false);

		return ddmTemplateImpl;
	}

	@Override
	public int compareTo(DDMTemplate ddmTemplate) {
		long primaryKey = ddmTemplate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DDMTemplate)) {
			return false;
		}

		DDMTemplate ddmTemplate = (DDMTemplate)object;

		long primaryKey = ddmTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;

		setResourceClassName(null);

		_columnBitmask = 0;

		_ddmTemplateCacheModel = null;
	}

	@Override
	public CacheModel<DDMTemplate> toCacheModel() {
		DDMTemplateCacheModel ddmTemplateCacheModel =
			new DDMTemplateCacheModel();

		ddmTemplateCacheModel.mvccVersion = getMvccVersion();

		ddmTemplateCacheModel.ctCollectionId = getCtCollectionId();

		ddmTemplateCacheModel.uuid = getUuid();

		String uuid = ddmTemplateCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			ddmTemplateCacheModel.uuid = null;
		}

		ddmTemplateCacheModel.templateId = getTemplateId();

		ddmTemplateCacheModel.groupId = getGroupId();

		ddmTemplateCacheModel.companyId = getCompanyId();

		ddmTemplateCacheModel.userId = getUserId();

		ddmTemplateCacheModel.userName = getUserName();

		String userName = ddmTemplateCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			ddmTemplateCacheModel.userName = null;
		}

		ddmTemplateCacheModel.versionUserId = getVersionUserId();

		ddmTemplateCacheModel.versionUserName = getVersionUserName();

		String versionUserName = ddmTemplateCacheModel.versionUserName;

		if ((versionUserName != null) && (versionUserName.length() == 0)) {
			ddmTemplateCacheModel.versionUserName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			ddmTemplateCacheModel.createDate = createDate.getTime();
		}
		else {
			ddmTemplateCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			ddmTemplateCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			ddmTemplateCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		ddmTemplateCacheModel.classNameId = getClassNameId();

		ddmTemplateCacheModel.classPK = getClassPK();

		ddmTemplateCacheModel.resourceClassNameId = getResourceClassNameId();

		ddmTemplateCacheModel.templateKey = getTemplateKey();

		String templateKey = ddmTemplateCacheModel.templateKey;

		if ((templateKey != null) && (templateKey.length() == 0)) {
			ddmTemplateCacheModel.templateKey = null;
		}

		ddmTemplateCacheModel.version = getVersion();

		String version = ddmTemplateCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			ddmTemplateCacheModel.version = null;
		}

		ddmTemplateCacheModel.name = getName();

		String name = ddmTemplateCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			ddmTemplateCacheModel.name = null;
		}

		ddmTemplateCacheModel.description = getDescription();

		String description = ddmTemplateCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			ddmTemplateCacheModel.description = null;
		}

		ddmTemplateCacheModel.type = getType();

		String type = ddmTemplateCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			ddmTemplateCacheModel.type = null;
		}

		ddmTemplateCacheModel.mode = getMode();

		String mode = ddmTemplateCacheModel.mode;

		if ((mode != null) && (mode.length() == 0)) {
			ddmTemplateCacheModel.mode = null;
		}

		ddmTemplateCacheModel.language = getLanguage();

		String language = ddmTemplateCacheModel.language;

		if ((language != null) && (language.length() == 0)) {
			ddmTemplateCacheModel.language = null;
		}

		ddmTemplateCacheModel.script = getScript();

		String script = ddmTemplateCacheModel.script;

		if ((script != null) && (script.length() == 0)) {
			ddmTemplateCacheModel.script = null;
		}

		ddmTemplateCacheModel.cacheable = isCacheable();

		ddmTemplateCacheModel.smallImage = isSmallImage();

		ddmTemplateCacheModel.smallImageId = getSmallImageId();

		ddmTemplateCacheModel.smallImageURL = getSmallImageURL();

		String smallImageURL = ddmTemplateCacheModel.smallImageURL;

		if ((smallImageURL != null) && (smallImageURL.length() == 0)) {
			ddmTemplateCacheModel.smallImageURL = null;
		}

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			ddmTemplateCacheModel.lastPublishDate = lastPublishDate.getTime();
		}
		else {
			ddmTemplateCacheModel.lastPublishDate = Long.MIN_VALUE;
		}

		ddmTemplateCacheModel._resourceClassName = getResourceClassName();

		return ddmTemplateCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DDMTemplate, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DDMTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DDMTemplate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DDMTemplate)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DDMTemplate, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DDMTemplate, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DDMTemplate, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DDMTemplate)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DDMTemplate>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _templateId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private long _versionUserId;
	private String _versionUserName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _classNameId;
	private long _classPK;
	private long _resourceClassNameId;
	private String _templateKey;
	private String _version;
	private String _name;
	private String _nameCurrentLanguageId;
	private String _description;
	private String _descriptionCurrentLanguageId;
	private String _type;
	private String _mode;
	private String _language;
	private String _script;
	private boolean _cacheable;
	private boolean _smallImage;
	private long _smallImageId;
	private String _smallImageURL;
	private Date _lastPublishDate;
	private long _columnBitmask;
	private DDMTemplate _escapedModel;
	private DDMTemplateCacheModel _ddmTemplateCacheModel;

}