/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.rolling.restart.sample.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.rolling.restart.sample.model.RollingRestartSampleEntry;
import com.liferay.portal.rolling.restart.sample.service.RollingRestartSampleEntryLocalService;
import com.liferay.portal.rolling.restart.sample.service.RollingRestartSampleEntryLocalServiceUtil;
import com.liferay.portal.rolling.restart.sample.service.persistence.RollingRestartSampleEntryPersistence;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the rolling restart sample entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.rolling.restart.sample.service.impl.RollingRestartSampleEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.rolling.restart.sample.service.impl.RollingRestartSampleEntryLocalServiceImpl
 * @generated
 */
public abstract class RollingRestartSampleEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   RollingRestartSampleEntryLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RollingRestartSampleEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>RollingRestartSampleEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the rolling restart sample entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RollingRestartSampleEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rollingRestartSampleEntry the rolling restart sample entry
	 * @return the rolling restart sample entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RollingRestartSampleEntry addRollingRestartSampleEntry(
		RollingRestartSampleEntry rollingRestartSampleEntry) {

		rollingRestartSampleEntry.setNew(true);

		return rollingRestartSampleEntryPersistence.update(
			rollingRestartSampleEntry);
	}

	/**
	 * Creates a new rolling restart sample entry with the primary key. Does not add the rolling restart sample entry to the database.
	 *
	 * @param entryId the primary key for the new rolling restart sample entry
	 * @return the new rolling restart sample entry
	 */
	@Override
	@Transactional(enabled = false)
	public RollingRestartSampleEntry createRollingRestartSampleEntry(
		long entryId) {

		return rollingRestartSampleEntryPersistence.create(entryId);
	}

	/**
	 * Deletes the rolling restart sample entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RollingRestartSampleEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param entryId the primary key of the rolling restart sample entry
	 * @return the rolling restart sample entry that was removed
	 * @throws PortalException if a rolling restart sample entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RollingRestartSampleEntry deleteRollingRestartSampleEntry(
			long entryId)
		throws PortalException {

		return rollingRestartSampleEntryPersistence.remove(entryId);
	}

	/**
	 * Deletes the rolling restart sample entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RollingRestartSampleEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rollingRestartSampleEntry the rolling restart sample entry
	 * @return the rolling restart sample entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RollingRestartSampleEntry deleteRollingRestartSampleEntry(
		RollingRestartSampleEntry rollingRestartSampleEntry) {

		return rollingRestartSampleEntryPersistence.remove(
			rollingRestartSampleEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return rollingRestartSampleEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			RollingRestartSampleEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return rollingRestartSampleEntryPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.rolling.restart.sample.model.impl.RollingRestartSampleEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return rollingRestartSampleEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.rolling.restart.sample.model.impl.RollingRestartSampleEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return rollingRestartSampleEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return rollingRestartSampleEntryPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return rollingRestartSampleEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public RollingRestartSampleEntry fetchRollingRestartSampleEntry(
		long entryId) {

		return rollingRestartSampleEntryPersistence.fetchByPrimaryKey(entryId);
	}

	/**
	 * Returns the rolling restart sample entry with the primary key.
	 *
	 * @param entryId the primary key of the rolling restart sample entry
	 * @return the rolling restart sample entry
	 * @throws PortalException if a rolling restart sample entry with the primary key could not be found
	 */
	@Override
	public RollingRestartSampleEntry getRollingRestartSampleEntry(long entryId)
		throws PortalException {

		return rollingRestartSampleEntryPersistence.findByPrimaryKey(entryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			rollingRestartSampleEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RollingRestartSampleEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("entryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			rollingRestartSampleEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			RollingRestartSampleEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("entryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			rollingRestartSampleEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RollingRestartSampleEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("entryId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rollingRestartSampleEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return rollingRestartSampleEntryLocalService.
			deleteRollingRestartSampleEntry(
				(RollingRestartSampleEntry)persistedModel);
	}

	@Override
	public BasePersistence<RollingRestartSampleEntry> getBasePersistence() {
		return rollingRestartSampleEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return rollingRestartSampleEntryPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the rolling restart sample entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.rolling.restart.sample.model.impl.RollingRestartSampleEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of rolling restart sample entries
	 * @param end the upper bound of the range of rolling restart sample entries (not inclusive)
	 * @return the range of rolling restart sample entries
	 */
	@Override
	public List<RollingRestartSampleEntry> getRollingRestartSampleEntries(
		int start, int end) {

		return rollingRestartSampleEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rolling restart sample entries.
	 *
	 * @return the number of rolling restart sample entries
	 */
	@Override
	public int getRollingRestartSampleEntriesCount() {
		return rollingRestartSampleEntryPersistence.countAll();
	}

	/**
	 * Updates the rolling restart sample entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect RollingRestartSampleEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param rollingRestartSampleEntry the rolling restart sample entry
	 * @return the rolling restart sample entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RollingRestartSampleEntry updateRollingRestartSampleEntry(
		RollingRestartSampleEntry rollingRestartSampleEntry) {

		return rollingRestartSampleEntryPersistence.update(
			rollingRestartSampleEntry);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RollingRestartSampleEntryLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		rollingRestartSampleEntryLocalService =
			(RollingRestartSampleEntryLocalService)aopProxy;

		_setLocalServiceUtilService(rollingRestartSampleEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RollingRestartSampleEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RollingRestartSampleEntry.class;
	}

	protected String getModelClassName() {
		return RollingRestartSampleEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				rollingRestartSampleEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		RollingRestartSampleEntryLocalService
			rollingRestartSampleEntryLocalService) {

		try {
			Field field =
				RollingRestartSampleEntryLocalServiceUtil.class.
					getDeclaredField("_service");

			field.setAccessible(true);

			field.set(null, rollingRestartSampleEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected RollingRestartSampleEntryLocalService
		rollingRestartSampleEntryLocalService;

	@Reference
	protected RollingRestartSampleEntryPersistence
		rollingRestartSampleEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}