/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.rolling.restart.sample.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.rolling.restart.sample.model.RollingRestartSampleEntry;
import com.liferay.portal.rolling.restart.sample.service.RollingRestartSampleEntryService;
import com.liferay.portal.rolling.restart.sample.service.RollingRestartSampleEntryServiceUtil;
import com.liferay.portal.rolling.restart.sample.service.persistence.RollingRestartSampleEntryPersistence;

import java.lang.reflect.Field;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the rolling restart sample entry remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.rolling.restart.sample.service.impl.RollingRestartSampleEntryServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.portal.rolling.restart.sample.service.impl.RollingRestartSampleEntryServiceImpl
 * @generated
 */
public abstract class RollingRestartSampleEntryServiceBaseImpl
	extends BaseServiceImpl
	implements AopService, IdentifiableOSGiService,
			   RollingRestartSampleEntryService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>RollingRestartSampleEntryService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>RollingRestartSampleEntryServiceUtil</code>.
	 */
	@Deactivate
	protected void deactivate() {
		_setServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			RollingRestartSampleEntryService.class,
			IdentifiableOSGiService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		rollingRestartSampleEntryService =
			(RollingRestartSampleEntryService)aopProxy;

		_setServiceUtilService(rollingRestartSampleEntryService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RollingRestartSampleEntryService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RollingRestartSampleEntry.class;
	}

	protected String getModelClassName() {
		return RollingRestartSampleEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				rollingRestartSampleEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setServiceUtilService(
		RollingRestartSampleEntryService rollingRestartSampleEntryService) {

		try {
			Field field =
				RollingRestartSampleEntryServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, rollingRestartSampleEntryService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected com.liferay.portal.rolling.restart.sample.service.
		RollingRestartSampleEntryLocalService
			rollingRestartSampleEntryLocalService;

	protected RollingRestartSampleEntryService rollingRestartSampleEntryService;

	@Reference
	protected RollingRestartSampleEntryPersistence
		rollingRestartSampleEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

}