##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    line.length.excludes=\
        modules/apps/portal-scheduler/portal-scheduler/src/main/java/com/liferay/portal/scheduler/internal/SchedulerEngineHelperImpl.java@802