/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.asset.list.model.impl;

import com.liferay.asset.list.model.AssetListEntryAssetEntryRel;
import com.liferay.asset.list.model.AssetListEntryAssetEntryRelModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AssetListEntryAssetEntryRel service. Represents a row in the &quot;AssetListEntryAssetEntryRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssetListEntryAssetEntryRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetListEntryAssetEntryRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetListEntryAssetEntryRelImpl
 * @generated
 */
public class AssetListEntryAssetEntryRelModelImpl
	extends BaseModelImpl<AssetListEntryAssetEntryRel>
	implements AssetListEntryAssetEntryRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset list entry asset entry rel model instance should use the <code>AssetListEntryAssetEntryRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "AssetListEntryAssetEntryRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"ctCollectionId", Types.BIGINT},
		{"uuid_", Types.VARCHAR},
		{"assetListEntryAssetEntryRelId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"assetListEntryId", Types.BIGINT}, {"assetEntryId", Types.BIGINT},
		{"segmentsEntryId", Types.BIGINT}, {"position", Types.INTEGER},
		{"lastPublishDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ctCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assetListEntryAssetEntryRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("assetListEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("assetEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("segmentsEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("position", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("lastPublishDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AssetListEntryAssetEntryRel (mvccVersion LONG default 0 not null,ctCollectionId LONG default 0 not null,uuid_ VARCHAR(75) null,assetListEntryAssetEntryRelId LONG not null,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,assetListEntryId LONG,assetEntryId LONG,segmentsEntryId LONG,position INTEGER,lastPublishDate DATE null,primary key (assetListEntryAssetEntryRelId, ctCollectionId))";

	public static final String TABLE_SQL_DROP =
		"drop table AssetListEntryAssetEntryRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY assetListEntryAssetEntryRel.position ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AssetListEntryAssetEntryRel.position ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long MVCCVERSION_COLUMN_BITMASK = 1L;

	public static final long CTCOLLECTIONID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static final long ASSETLISTENTRYASSETENTRYRELID_COLUMN_BITMASK = 8L;

	public static final long GROUPID_COLUMN_BITMASK = 16L;

	public static final long COMPANYID_COLUMN_BITMASK = 32L;

	public static final long USERID_COLUMN_BITMASK = 64L;

	public static final long USERNAME_COLUMN_BITMASK = 128L;

	public static final long CREATEDATE_COLUMN_BITMASK = 256L;

	public static final long MODIFIEDDATE_COLUMN_BITMASK = 512L;

	public static final long ASSETLISTENTRYID_COLUMN_BITMASK = 1024L;

	public static final long ASSETENTRYID_COLUMN_BITMASK = 2048L;

	public static final long SEGMENTSENTRYID_COLUMN_BITMASK = 4096L;

	public static final long POSITION_COLUMN_BITMASK = 8192L;

	public static final long LASTPUBLISHDATE_COLUMN_BITMASK = 16384L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AssetListEntryAssetEntryRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetListEntryAssetEntryRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetListEntryAssetEntryRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetListEntryAssetEntryRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AssetListEntryAssetEntryRel.class;
	}

	@Override
	public String getModelClassName() {
		return AssetListEntryAssetEntryRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AssetListEntryAssetEntryRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AssetListEntryAssetEntryRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetListEntryAssetEntryRel, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(AssetListEntryAssetEntryRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AssetListEntryAssetEntryRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AssetListEntryAssetEntryRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AssetListEntryAssetEntryRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AssetListEntryAssetEntryRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AssetListEntryAssetEntryRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AssetListEntryAssetEntryRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AssetListEntryAssetEntryRel.class.getClassLoader(),
			AssetListEntryAssetEntryRel.class, ModelWrapper.class);

		try {
			Constructor<AssetListEntryAssetEntryRel> constructor =
				(Constructor<AssetListEntryAssetEntryRel>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	public <T> T getOriginalAttributeValue(String attributeName) {
		if ((_assetListEntryAssetEntryRelCacheModel == null) ||
			(_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel)) {

			return null;
		}

		Function<AssetListEntryAssetEntryRelCacheModel, Object> function =
			_cacheModelGetterFunctions.get(attributeName);

		if (function == null) {
			return null;
		}

		return (T)function.apply(_assetListEntryAssetEntryRelCacheModel);
	}

	private static final Map
		<String, Function<AssetListEntryAssetEntryRelCacheModel, Object>>
			_cacheModelGetterFunctions;
	private static final Map
		<String, Function<AssetListEntryAssetEntryRel, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<AssetListEntryAssetEntryRel, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<AssetListEntryAssetEntryRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AssetListEntryAssetEntryRel, Object>>();
		Map<String, BiConsumer<AssetListEntryAssetEntryRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<AssetListEntryAssetEntryRel, ?>>();
		Map<String, Function<AssetListEntryAssetEntryRelCacheModel, Object>>
			cacheModelGetterFunctions =
				new LinkedHashMap
					<String,
					 Function<AssetListEntryAssetEntryRelCacheModel, Object>>();

		attributeGetterFunctions.put(
			"mvccVersion", AssetListEntryAssetEntryRel::getMvccVersion);

		cacheModelGetterFunctions.put(
			"mvccVersion",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.mvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setMvccVersion);
		attributeGetterFunctions.put(
			"ctCollectionId", AssetListEntryAssetEntryRel::getCtCollectionId);

		cacheModelGetterFunctions.put(
			"ctCollectionId",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.ctCollectionId);
		attributeSetterBiConsumers.put(
			"ctCollectionId",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setCtCollectionId);
		attributeGetterFunctions.put(
			"uuid", AssetListEntryAssetEntryRel::getUuid);

		cacheModelGetterFunctions.put(
			"uuid",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.uuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<AssetListEntryAssetEntryRel, String>)
				AssetListEntryAssetEntryRel::setUuid);
		attributeGetterFunctions.put(
			"assetListEntryAssetEntryRelId",
			AssetListEntryAssetEntryRel::getAssetListEntryAssetEntryRelId);

		cacheModelGetterFunctions.put(
			"assetListEntryAssetEntryRelId",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.
					assetListEntryAssetEntryRelId);
		attributeSetterBiConsumers.put(
			"assetListEntryAssetEntryRelId",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setAssetListEntryAssetEntryRelId);
		attributeGetterFunctions.put(
			"groupId", AssetListEntryAssetEntryRel::getGroupId);

		cacheModelGetterFunctions.put(
			"groupId",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.groupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setGroupId);
		attributeGetterFunctions.put(
			"companyId", AssetListEntryAssetEntryRel::getCompanyId);

		cacheModelGetterFunctions.put(
			"companyId",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.companyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setCompanyId);
		attributeGetterFunctions.put(
			"userId", AssetListEntryAssetEntryRel::getUserId);

		cacheModelGetterFunctions.put(
			"userId",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.userId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setUserId);
		attributeGetterFunctions.put(
			"userName", AssetListEntryAssetEntryRel::getUserName);

		cacheModelGetterFunctions.put(
			"userName",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.userName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<AssetListEntryAssetEntryRel, String>)
				AssetListEntryAssetEntryRel::setUserName);
		attributeGetterFunctions.put(
			"createDate", AssetListEntryAssetEntryRel::getCreateDate);

		cacheModelGetterFunctions.put(
			"createDate",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.createDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<AssetListEntryAssetEntryRel, Date>)
				AssetListEntryAssetEntryRel::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", AssetListEntryAssetEntryRel::getModifiedDate);

		cacheModelGetterFunctions.put(
			"modifiedDate",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.modifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<AssetListEntryAssetEntryRel, Date>)
				AssetListEntryAssetEntryRel::setModifiedDate);
		attributeGetterFunctions.put(
			"assetListEntryId",
			AssetListEntryAssetEntryRel::getAssetListEntryId);

		cacheModelGetterFunctions.put(
			"assetListEntryId",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.assetListEntryId);
		attributeSetterBiConsumers.put(
			"assetListEntryId",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setAssetListEntryId);
		attributeGetterFunctions.put(
			"assetEntryId", AssetListEntryAssetEntryRel::getAssetEntryId);

		cacheModelGetterFunctions.put(
			"assetEntryId",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.assetEntryId);
		attributeSetterBiConsumers.put(
			"assetEntryId",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setAssetEntryId);
		attributeGetterFunctions.put(
			"segmentsEntryId", AssetListEntryAssetEntryRel::getSegmentsEntryId);

		cacheModelGetterFunctions.put(
			"segmentsEntryId",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.segmentsEntryId);
		attributeSetterBiConsumers.put(
			"segmentsEntryId",
			(BiConsumer<AssetListEntryAssetEntryRel, Long>)
				AssetListEntryAssetEntryRel::setSegmentsEntryId);
		attributeGetterFunctions.put(
			"position", AssetListEntryAssetEntryRel::getPosition);

		cacheModelGetterFunctions.put(
			"position",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.position);
		attributeSetterBiConsumers.put(
			"position",
			(BiConsumer<AssetListEntryAssetEntryRel, Integer>)
				AssetListEntryAssetEntryRel::setPosition);
		attributeGetterFunctions.put(
			"lastPublishDate", AssetListEntryAssetEntryRel::getLastPublishDate);

		cacheModelGetterFunctions.put(
			"lastPublishDate",
			assetListEntryAssetEntryRelCacheModel ->
				assetListEntryAssetEntryRelCacheModel.lastPublishDate);
		attributeSetterBiConsumers.put(
			"lastPublishDate",
			(BiConsumer<AssetListEntryAssetEntryRel, Date>)
				AssetListEntryAssetEntryRel::setLastPublishDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
		_cacheModelGetterFunctions = Collections.unmodifiableMap(
			cacheModelGetterFunctions);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_columnBitmask |= MVCCVERSION_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getCtCollectionId() {
		return _ctCollectionId;
	}

	@Override
	public void setCtCollectionId(long ctCollectionId) {
		_columnBitmask |= CTCOLLECTIONID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_ctCollectionId = ctCollectionId;
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getOriginalAttributeValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getOriginalAttributeValue("uuid");
	}

	@Override
	public long getAssetListEntryAssetEntryRelId() {
		return _assetListEntryAssetEntryRelId;
	}

	@Override
	public void setAssetListEntryAssetEntryRelId(
		long assetListEntryAssetEntryRelId) {

		_columnBitmask |= ASSETLISTENTRYASSETENTRYRELID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_assetListEntryAssetEntryRelId = assetListEntryAssetEntryRelId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getOriginalAttributeValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return getOriginalAttributeValue("groupId");
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getOriginalAttributeValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return getOriginalAttributeValue("companyId");
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_columnBitmask |= USERNAME_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask |= CREATEDATE_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_columnBitmask |= MODIFIEDDATE_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getAssetListEntryId() {
		return _assetListEntryId;
	}

	@Override
	public void setAssetListEntryId(long assetListEntryId) {
		_columnBitmask |= ASSETLISTENTRYID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_assetListEntryId = assetListEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getOriginalAttributeValue(String)}
	 */
	@Deprecated
	public long getOriginalAssetListEntryId() {
		return getOriginalAttributeValue("assetListEntryId");
	}

	@Override
	public long getAssetEntryId() {
		return _assetEntryId;
	}

	@Override
	public void setAssetEntryId(long assetEntryId) {
		_columnBitmask |= ASSETENTRYID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_assetEntryId = assetEntryId;
	}

	@Override
	public long getSegmentsEntryId() {
		return _segmentsEntryId;
	}

	@Override
	public void setSegmentsEntryId(long segmentsEntryId) {
		_columnBitmask |= SEGMENTSENTRYID_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_segmentsEntryId = segmentsEntryId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getOriginalAttributeValue(String)}
	 */
	@Deprecated
	public long getOriginalSegmentsEntryId() {
		return getOriginalAttributeValue("segmentsEntryId");
	}

	@Override
	public int getPosition() {
		return _position;
	}

	@Override
	public void setPosition(int position) {
		_columnBitmask |= POSITION_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_position = position;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getOriginalAttributeValue(String)}
	 */
	@Deprecated
	public int getOriginalPosition() {
		return getOriginalAttributeValue("position");
	}

	@Override
	public Date getLastPublishDate() {
		return _lastPublishDate;
	}

	@Override
	public void setLastPublishDate(Date lastPublishDate) {
		_columnBitmask |= LASTPUBLISHDATE_COLUMN_BITMASK;

		if (_assetListEntryAssetEntryRelCacheModel ==
				_dummyAssetListEntryAssetEntryRelCacheModel) {

			_assetListEntryAssetEntryRelCacheModel =
				(AssetListEntryAssetEntryRelCacheModel)toCacheModel();
		}

		_lastPublishDate = lastPublishDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(
				AssetListEntryAssetEntryRel.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AssetListEntryAssetEntryRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AssetListEntryAssetEntryRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AssetListEntryAssetEntryRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetListEntryAssetEntryRelImpl assetListEntryAssetEntryRelImpl =
			new AssetListEntryAssetEntryRelImpl();

		assetListEntryAssetEntryRelImpl.setMvccVersion(getMvccVersion());
		assetListEntryAssetEntryRelImpl.setCtCollectionId(getCtCollectionId());
		assetListEntryAssetEntryRelImpl.setUuid(getUuid());
		assetListEntryAssetEntryRelImpl.setAssetListEntryAssetEntryRelId(
			getAssetListEntryAssetEntryRelId());
		assetListEntryAssetEntryRelImpl.setGroupId(getGroupId());
		assetListEntryAssetEntryRelImpl.setCompanyId(getCompanyId());
		assetListEntryAssetEntryRelImpl.setUserId(getUserId());
		assetListEntryAssetEntryRelImpl.setUserName(getUserName());
		assetListEntryAssetEntryRelImpl.setCreateDate(getCreateDate());
		assetListEntryAssetEntryRelImpl.setModifiedDate(getModifiedDate());
		assetListEntryAssetEntryRelImpl.setAssetListEntryId(
			getAssetListEntryId());
		assetListEntryAssetEntryRelImpl.setAssetEntryId(getAssetEntryId());
		assetListEntryAssetEntryRelImpl.setSegmentsEntryId(
			getSegmentsEntryId());
		assetListEntryAssetEntryRelImpl.setPosition(getPosition());
		assetListEntryAssetEntryRelImpl.setLastPublishDate(
			getLastPublishDate());

		assetListEntryAssetEntryRelImpl.resetOriginalValues();

		return assetListEntryAssetEntryRelImpl;
	}

	@Override
	public int compareTo(
		AssetListEntryAssetEntryRel assetListEntryAssetEntryRel) {

		int value = 0;

		if (getPosition() < assetListEntryAssetEntryRel.getPosition()) {
			value = -1;
		}
		else if (getPosition() > assetListEntryAssetEntryRel.getPosition()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AssetListEntryAssetEntryRel)) {
			return false;
		}

		AssetListEntryAssetEntryRel assetListEntryAssetEntryRel =
			(AssetListEntryAssetEntryRel)object;

		long primaryKey = assetListEntryAssetEntryRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_setModifiedDate = false;

		_columnBitmask = 0;

		_assetListEntryAssetEntryRelCacheModel =
			_dummyAssetListEntryAssetEntryRelCacheModel;
	}

	@Override
	public CacheModel<AssetListEntryAssetEntryRel> toCacheModel() {
		AssetListEntryAssetEntryRelCacheModel
			assetListEntryAssetEntryRelCacheModel =
				new AssetListEntryAssetEntryRelCacheModel();

		assetListEntryAssetEntryRelCacheModel.mvccVersion = getMvccVersion();

		assetListEntryAssetEntryRelCacheModel.ctCollectionId =
			getCtCollectionId();

		assetListEntryAssetEntryRelCacheModel.uuid = getUuid();

		String uuid = assetListEntryAssetEntryRelCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assetListEntryAssetEntryRelCacheModel.uuid = null;
		}

		assetListEntryAssetEntryRelCacheModel.assetListEntryAssetEntryRelId =
			getAssetListEntryAssetEntryRelId();

		assetListEntryAssetEntryRelCacheModel.groupId = getGroupId();

		assetListEntryAssetEntryRelCacheModel.companyId = getCompanyId();

		assetListEntryAssetEntryRelCacheModel.userId = getUserId();

		assetListEntryAssetEntryRelCacheModel.userName = getUserName();

		String userName = assetListEntryAssetEntryRelCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			assetListEntryAssetEntryRelCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			assetListEntryAssetEntryRelCacheModel.createDate =
				createDate.getTime();
		}
		else {
			assetListEntryAssetEntryRelCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			assetListEntryAssetEntryRelCacheModel.modifiedDate =
				modifiedDate.getTime();
		}
		else {
			assetListEntryAssetEntryRelCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		assetListEntryAssetEntryRelCacheModel.assetListEntryId =
			getAssetListEntryId();

		assetListEntryAssetEntryRelCacheModel.assetEntryId = getAssetEntryId();

		assetListEntryAssetEntryRelCacheModel.segmentsEntryId =
			getSegmentsEntryId();

		assetListEntryAssetEntryRelCacheModel.position = getPosition();

		Date lastPublishDate = getLastPublishDate();

		if (lastPublishDate != null) {
			assetListEntryAssetEntryRelCacheModel.lastPublishDate =
				lastPublishDate.getTime();
		}
		else {
			assetListEntryAssetEntryRelCacheModel.lastPublishDate =
				Long.MIN_VALUE;
		}

		return assetListEntryAssetEntryRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AssetListEntryAssetEntryRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AssetListEntryAssetEntryRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetListEntryAssetEntryRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(AssetListEntryAssetEntryRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AssetListEntryAssetEntryRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AssetListEntryAssetEntryRel, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AssetListEntryAssetEntryRel, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(AssetListEntryAssetEntryRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, AssetListEntryAssetEntryRel>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private long _mvccVersion;
	private long _ctCollectionId;
	private String _uuid;
	private long _assetListEntryAssetEntryRelId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _assetListEntryId;
	private long _assetEntryId;
	private long _segmentsEntryId;
	private int _position;
	private Date _lastPublishDate;
	private long _columnBitmask;
	private AssetListEntryAssetEntryRel _escapedModel;

	private static final AssetListEntryAssetEntryRelCacheModel
		_dummyAssetListEntryAssetEntryRelCacheModel =
			new AssetListEntryAssetEntryRelCacheModel();

	private AssetListEntryAssetEntryRelCacheModel
		_assetListEntryAssetEntryRelCacheModel;

}