/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.tools.service.builder.test.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.tools.service.builder.test.model.DSLQueryLinkEntry;
import com.liferay.portal.tools.service.builder.test.model.DSLQueryLinkEntryModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the DSLQueryLinkEntry service. Represents a row in the &quot;DSLQueryLinkEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>DSLQueryLinkEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DSLQueryLinkEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DSLQueryLinkEntryImpl
 * @generated
 */
public class DSLQueryLinkEntryModelImpl
	extends BaseModelImpl<DSLQueryLinkEntry> implements DSLQueryLinkEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dsl query link entry model instance should use the <code>DSLQueryLinkEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DSLQueryLinkEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"dslQueryLinkEntryId", Types.BIGINT},
		{"parentDSLQueryEntryId", Types.BIGINT},
		{"childDSLQueryEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dslQueryLinkEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("parentDSLQueryEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("childDSLQueryEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DSLQueryLinkEntry (dslQueryLinkEntryId LONG not null primary key,parentDSLQueryEntryId LONG,childDSLQueryEntryId LONG)";

	public static final String TABLE_SQL_DROP = "drop table DSLQueryLinkEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dslQueryLinkEntry.dslQueryLinkEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY DSLQueryLinkEntry.dslQueryLinkEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)
	 */
	@Deprecated
	public static final long DSLQUERYLINKENTRYID_COLUMN_BITMASK = 1L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		com.liferay.portal.tools.service.builder.test.service.util.ServiceProps.
			get(
				"lock.expiration.time.com.liferay.portal.tools.service.builder.test.model.DSLQueryLinkEntry"));

	public DSLQueryLinkEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dslQueryLinkEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDslQueryLinkEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dslQueryLinkEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DSLQueryLinkEntry.class;
	}

	@Override
	public String getModelClassName() {
		return DSLQueryLinkEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DSLQueryLinkEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DSLQueryLinkEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DSLQueryLinkEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DSLQueryLinkEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DSLQueryLinkEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DSLQueryLinkEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DSLQueryLinkEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DSLQueryLinkEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DSLQueryLinkEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DSLQueryLinkEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DSLQueryLinkEntry.class.getClassLoader(), DSLQueryLinkEntry.class,
			ModelWrapper.class);

		try {
			Constructor<DSLQueryLinkEntry> constructor =
				(Constructor<DSLQueryLinkEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<DSLQueryLinkEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DSLQueryLinkEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DSLQueryLinkEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<DSLQueryLinkEntry, Object>>();
		Map<String, BiConsumer<DSLQueryLinkEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<DSLQueryLinkEntry, ?>>();

		attributeGetterFunctions.put(
			"dslQueryLinkEntryId", DSLQueryLinkEntry::getDslQueryLinkEntryId);
		attributeSetterBiConsumers.put(
			"dslQueryLinkEntryId",
			(BiConsumer<DSLQueryLinkEntry, Long>)
				DSLQueryLinkEntry::setDslQueryLinkEntryId);
		attributeGetterFunctions.put(
			"parentDSLQueryEntryId",
			DSLQueryLinkEntry::getParentDSLQueryEntryId);
		attributeSetterBiConsumers.put(
			"parentDSLQueryEntryId",
			(BiConsumer<DSLQueryLinkEntry, Long>)
				DSLQueryLinkEntry::setParentDSLQueryEntryId);
		attributeGetterFunctions.put(
			"childDSLQueryEntryId", DSLQueryLinkEntry::getChildDSLQueryEntryId);
		attributeSetterBiConsumers.put(
			"childDSLQueryEntryId",
			(BiConsumer<DSLQueryLinkEntry, Long>)
				DSLQueryLinkEntry::setChildDSLQueryEntryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getDslQueryLinkEntryId() {
		return _dslQueryLinkEntryId;
	}

	@Override
	public void setDslQueryLinkEntryId(long dslQueryLinkEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dslQueryLinkEntryId = dslQueryLinkEntryId;
	}

	@Override
	public long getParentDSLQueryEntryId() {
		return _parentDSLQueryEntryId;
	}

	@Override
	public void setParentDSLQueryEntryId(long parentDSLQueryEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_parentDSLQueryEntryId = parentDSLQueryEntryId;
	}

	@Override
	public long getChildDSLQueryEntryId() {
		return _childDSLQueryEntryId;
	}

	@Override
	public void setChildDSLQueryEntryId(long childDSLQueryEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_childDSLQueryEntryId = childDSLQueryEntryId;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (entry.getValue() != getColumnValue(entry.getKey())) {
				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, DSLQueryLinkEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DSLQueryLinkEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DSLQueryLinkEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DSLQueryLinkEntryImpl dslQueryLinkEntryImpl =
			new DSLQueryLinkEntryImpl();

		dslQueryLinkEntryImpl.setDslQueryLinkEntryId(getDslQueryLinkEntryId());
		dslQueryLinkEntryImpl.setParentDSLQueryEntryId(
			getParentDSLQueryEntryId());
		dslQueryLinkEntryImpl.setChildDSLQueryEntryId(
			getChildDSLQueryEntryId());

		dslQueryLinkEntryImpl.resetOriginalValues();

		return dslQueryLinkEntryImpl;
	}

	@Override
	public int compareTo(DSLQueryLinkEntry dslQueryLinkEntry) {
		long primaryKey = dslQueryLinkEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof DSLQueryLinkEntry)) {
			return false;
		}

		DSLQueryLinkEntry dslQueryLinkEntry = (DSLQueryLinkEntry)object;

		long primaryKey = dslQueryLinkEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<DSLQueryLinkEntry> toCacheModel() {
		DSLQueryLinkEntryCacheModel dslQueryLinkEntryCacheModel =
			new DSLQueryLinkEntryCacheModel();

		dslQueryLinkEntryCacheModel.dslQueryLinkEntryId =
			getDslQueryLinkEntryId();

		dslQueryLinkEntryCacheModel.parentDSLQueryEntryId =
			getParentDSLQueryEntryId();

		dslQueryLinkEntryCacheModel.childDSLQueryEntryId =
			getChildDSLQueryEntryId();

		return dslQueryLinkEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DSLQueryLinkEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DSLQueryLinkEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DSLQueryLinkEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DSLQueryLinkEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DSLQueryLinkEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DSLQueryLinkEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DSLQueryLinkEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DSLQueryLinkEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DSLQueryLinkEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _dslQueryLinkEntryId;
	private long _parentDSLQueryEntryId;
	private long _childDSLQueryEntryId;

	public <T> T getColumnValue(String columnName) {
		Function<DSLQueryLinkEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((DSLQueryLinkEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	@Override
	public String getTableName() {
		return TABLE_NAME;
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("dslQueryLinkEntryId", _dslQueryLinkEntryId);
		_columnOriginalValues.put(
			"parentDSLQueryEntryId", _parentDSLQueryEntryId);
		_columnOriginalValues.put(
			"childDSLQueryEntryId", _childDSLQueryEntryId);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("dslQueryLinkEntryId", 1L);

		columnBitmasks.put("parentDSLQueryEntryId", 2L);

		columnBitmasks.put("childDSLQueryEntryId", 4L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private DSLQueryLinkEntry _escapedModel;

}