/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.dao.orm.hibernate;

/**
 * @author Tina Tian
 */
public enum CriterionType {

	ALL_EQ, AND, BETWEEN, CONJUNCTION, DISJUNCTION, EQ, EQ_PROPERTY, GE,
	GE_PROPERTY, GT, GT_PROPERTY, ILIKE, IN, IS_EMPTY, IS_NOT_EMPTY,
	IS_NOT_NULL, IS_NULL, LE, LE_PROPERTY, LIKE, LT, LT_PROPERTY, NE,
	NE_PROPERTY, NOT, OR, SIZE_EQ, SIZE_GE, SIZE_GT, SIZE_LE, SIZE_LT, SIZE_NE,
	SQL_RESTRICTION, SUBQUERY_EQ, SUBQUERY_EQ_ALL, SUBQUERY_GE, SUBQUERY_GE_ALL,
	SUBQUERY_GE_SOME, SUBQUERY_GT, SUBQUERY_GT_ALL, SUBQUERY_GT_SOME,
	SUBQUERY_IN, SUBQUERY_LE, SUBQUERY_LE_ALL, SUBQUERY_LE_SOME, SUBQUERY_LT,
	SUBQUERY_LT_ALL, SUBQUERY_LT_SOME, SUBQUERY_NE, SUBQUERY_NOT_IN

}